gaphor/gaphor

po/fr.po
Fix the bug: https://bugs.launchpad.net/ubuntu/+source/gaphor/+bug/1129135
=> Fix "LookupError: unknown encoding: CHARSET"

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Moves the templates to a .github folder. Cleans up the formatting to use GitHub's checkboxes.
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
```
Checkboxes are in code blocks and don't show up properly
They are fixed :+1: 
```
[ ] Yes
[X] No
```
=> Move issue and PR templates, fix checkboxes

README.rst
Add a note to the README about gaphor and gaphas version compatibility.
Issue Number: #66
=> add note about gaphas version compatibility

gaphor/diagram/compartment.py, gaphor/diagram/textelement.py, tests/test-model.gaphor, tests/test_gen_uml.py
Fixed a broken test. Fixed #73. 
The unit test contained invalid test data.
It looks like there were a bunch of empty LiteralSpecification entries in the model file. Those have been replaced by simple `val` entries.
=> Fix `tests/test_gen_uml`

gaphor/adapters/connectors.py, gaphor/adapters/tests/test_comment.py, gaphor/services/undomanager.py, gaphor/ui/diagrampage.py, gaphor/ui/diagramtools.py
Fix #72.
This fix avoids the problem from occurring. The root cause is not taken away, but that'll require some more investigation on how the disconnect steps interact with each other.
=> Fix test comment

docs/datamodel.txt, gaphor/UML/properties.py, gaphor/UML/tests/test_properties.py, gaphor/adapters/propertypages.py, gaphor/misc/gidlethread.py, gaphor/plugins/pynsource/__init__.py, gaphor/services/elementdispatcher.py, gaphor/storage/storage.py, gaphor/storage/tests/test_storage.py, gaphor/tests/test_transaction.py, gaphor/ui/namespace.py, gaphor/ui/tests/test_handletool.py, tests/test_gen_uml.py, tests/test_undo.py, utils/command/gen_uml.py, utils/command/pygettext.py
A couple of handle tests were failing.
Fixed test cases. We have to see to what extend they can be considered redundant anyway.]
This PR also includes the fixes from #91.
=> Fix test handletool

gaphor/adapters/editors.py, gaphor/adapters/propertypages.py, gaphor/plugins/alignment/__init__.py, gaphor/services/undomanager.py, gaphor/ui/consolewindow.py, gaphor/ui/diagrampage.py, gaphor/ui/elementeditor.py
A fix for comment editor and a fix for the modifier keys used.
=> Fix comment editor

.circleci/config.yml
=> Migrate from Travis to Circle CI

CONTRIBUTING.md
=> Update contributing guideline

gaphor/misc/__init__.py, gaphor/services/properties.py, gaphor/ui/accelmap.py, gaphor/ui/consolewindow.py
Config files are saved in `~/.local/share`
Issue Number: #110
Config files are saved in `~/.config/gaphor`
=> Use ~/.config/gaphor as config dir

gaphor/plugins/alignment/__init__.py, gaphor/ui/diagramtools.py, gaphor/ui/mainwindow.py, gaphor/ui/namespace.py
Issue Number: #107 
Diagram specific menu items are shown.
Menu actions should also be fixed.
=> Diagram specific menu items

azure-pipelines.yml, gaphor/__main__.py, gaphor/diagram/textelement.py, pyproject.toml
Fixes the Gaphor.app built so that it doesn't crash on startup.
- Allow gaphor to be run as a Python Module
- Add services as plugins to the pyproject.toml so they get installed correctly by pip when building the package
Gaphor.app immediately closes
Gaphor.app launches successfully in macOS
=> Create a Working macOS App

gaphor/adapters/profiles/stereotypepage.py, gaphor/adapters/propertypages.py, gaphor/diagram/classes/association.py, gaphor/diagram/compartment.py, gaphor/diagram/diagramitem.py, gaphor/ui/elementeditor.py, gaphor/ui/namespace.py, gaphor/ui/tests/test_namespace.py
=> Fix stereotypes

.gitignore, gaphor/UML/element.py, gaphor/UML/elementfactory.py, gaphor/UML/modelfactory.py, gaphor/UML/tests/test_elementfactory.py, gaphor/adapters/tests/test_grouping.py, gaphor/interfaces.py, gaphor/services/componentregistry.py, gaphor/services/filemanager.py, gaphor/storage/storage.py, gaphor/ui/mainwindow.py, gaphor/ui/namespace.py, gaphor/ui/tests/test_namespace.py, tests/test_issue_132.py
Should fix #106
I replaced the GenericTreeModel with a TreeStore and added code required to show an ordered tree view.
=> Namespace tree store

gaphor/plugins/alignment/__init__.py, setup.py
TypeError when loading Gaphor with packaged Windows and Flatpak Linux builds.
Issue Number: #127 
Successful launch of Gaphor
=> Fix TypeError when init alignment plugin on Gaphor load

gaphor/ui/mainwindow.py, gaphor/ui/namespace.py
Fixes #149.
Issue Number: #149
=> Fix AttributeError when Creating or Renaming a Diagram or Package

poetry.lock, pyproject.toml
=> Poetry upgrade

gaphor/action.py, gaphor/application.py, gaphor/diagram/text.py, gaphor/services/copyservice.py, gaphor/services/filemanager.py, gaphor/services/helpservice.py, gaphor/services/tests/test_actionmanager.py, gaphor/services/undomanager.py, gaphor/ui/__init__.py, gaphor/ui/consolewindow.py, gaphor/ui/diagrampage.py, gaphor/ui/diagramtoolbox.py, gaphor/ui/elementeditor.py, gaphor/ui/mainwindow.py, gaphor/ui/namespace.py, gaphor/ui/tests/test_diagramtoolbox.py, gaphor/ui/toolbox.py
See #202 
This PR changes the code to use icon names, instead of stock icons.
=> Replace all uses old stock_id with icon names

azure-pipelines.yml, win-installer/misc/create-launcher.py
Update azure pipelines to publish directly to PyPI using poetry.
=> Publish to PyPI from CI

.pre-commit-config.yaml
This PR pins mypy to version 0.730, since version 0.740 is giving a lot of errors.
=> Pin version of mypy used to fix errors with version 0.740

.azure/msys2-test.sh, azure-pipelines.yml, gaphor/diagram/classes/tests/test_class.py, poetry.lock, pyproject.toml, venv
This PR makes updates so that the tests are running in Windows on Azure Pipelines.
Issue Number: #130 
This will partially fix this issue. However https://github.com/pyinstaller/pyinstaller/pull/4417 needs to merged to allow PyInstaller to build a package.
=> Fix Windows Tests in CI

NEWS, flatpak/lockfile-depends.yaml, flatpak/org.gaphor.Gaphor.appdata.xml, gaphor/__init__.py, poetry.lock, pyproject.toml, venv, win-installer/file_version_info.txt
=> Release 1.1.1

gaphor/ui/mainwindow.py, gaphor/ui/shortcuts.glade, gaphor/ui/shortcuts.py, pyproject.toml
A dialog is added that displays all keyboard shortcuts present in Gaphor. Handy for new-comers, since not all actions can be found in the menus.
A new service (`shortcuts`) is added.
=> Add Keyboard Shortcuts window

.gitignore, gaphor/UML/tests/test_umlfmt.py, gaphor/UML/umlfmt.py
It adds a little more consistency since the format method is using it's own (dispatch) functions internally.
=> Refactor umlfmt

gaphor/storage/parser.py
Refactoring. Reducing code complexity. Hopefully.
=> Reduce parser complexity

gaphor/UML/elementdispatcher.py
=> Simplify ElementDispatcher

gaphor/services/helpservice/shortcuts.glade, gaphor/transaction.py, gaphor/ui/event.py, gaphor/ui/mainwindow.py, gaphor/ui/preferences.py
Diagrams can only be closed by clicking on the `x` button.
Add keyboard shortcut `<Ctrl/Cmd>+w` to close a diagram
Closing now happens through an event `DiagramClosed`, similar to `DiagramOpened`.
=> Close current tab

gaphor/plugins/console/console.py, pyproject.toml
Workaround for #245.
Tests work, with console window enabled.
=> Enable Console again, workaround for CI

po/it.po
=> Create it po

README.md
=> doc(readme): add link to AUR

gaphor/profiles/safety-reliability.gaphor, gaphor/profiles/sysml.gaphor
This is the first step in getting SysML support to close #138. It adds SysML and Safety & Reliability Gaphor models.
Issue Number: #138
=> Add SysML and Safety & Reliability Gaphor Models

.github/workflows/build.yml, .pre-commit-config.yaml, poetry.lock, pyproject.toml, win-installer/misc/depcheck.py
=> Update version for Flake8 and MyPy

.github/workflows/build.yml
This attempts to work around https://github.com/msys2/MSYS2-packages/issues/1960 by updating pacman prior to updating the other msys2 packages.
=> Fix Windows Build Errors caused by Missing ZST Archives

macos-dmg/gaphor, macos-dmg/package.sh
Issue Number: #323 
File save dialog works.
=> Add compiled schemas to the macOS distro

gaphor/ui/diagrampage.py
=> Fix Keybindings After Toolbox Changes

.github/workflows/build.yml
Windows build fails again.
Hopefully this works.
=> Do not perform msys system upgrade

.github/workflows/build.yml
=> Enable CodeClimate coverage reporting again

.flake8, gaphor/services/undomanager.py
- Whitespace before ':' (E203)
- Too many leading '#' for block comment (E266)
- 'from module import *' used; unable to detect undefined names (F403)
=> Enable Flake8 rules

gaphor/ui/icons/Makefile, gaphor/ui/icons/hicolor/scalable/actions/gaphor-view-editor-symbolic.svg, gaphor/ui/icons/stensil.svg, gaphor/ui/mainwindow.glade
=> New icon for editor sidebar

NEWS, pyproject.toml
This PR updates the change log and gets the project ready for another release
=> Prepare to Release Version 2.0.0

NEWS, pyproject.toml
=> Release version 2.0.1

gaphor/UML/classes/classconnect.py, gaphor/UML/classes/tests/conftest.py, gaphor/UML/classes/tests/test_associationconnect.py, gaphor/UML/classes/tests/test_classconnect.py, gaphor/UML/classes/tests/test_implementationconnect.py, gaphor/UML/tests/test_uml2.py, gaphor/UML/uml.py, gaphor/UML/umlfmt.py, gaphor/diagram/tests/fixtures.py, gaphor/ui/icons/Makefile, gaphor/ui/icons/hicolor/scalable/actions/gaphor-realization-symbolic.svg, gaphor/ui/icons/hicolor/scalable/actions/gaphor-usage-symbolic.svg, gaphor/ui/icons/stensil.svg, gaphor/ui/namespace.py, models/UML.gaphor
Dependencies are shown in the root of the diagram
Issue Number: #386
Dependencies are shown under their classifier.
Dependency.{client|supplier} is now has `[0..1]` mulriplicity.
=> Dependency namespace

.github/scripts/metadata.sh, .pre-commit-config.yaml, docs/modeldoc.sh, macos-dmg/package.sh, macos-dmg/validate.sh, venv, win-installer/build-installer.sh, win-installer/msys2-install.sh
Cleans up our bash scripts and enables pre-commit checks.
Shellcheck throws errors in our current scripts.
Issue Number: 
All errors are fixed.
=> Fix shell syntax issues and enable shellcheck pre-commit

gaphor/UML/states/copypaste.py, gaphor/UML/states/tests/test_copypaste.py
Transition items are copied without a guard clause.
The `guard` Constraint is also copied.
=> Fix copy/paste for Transition

gaphor/ui/namespace.py, gaphor/ui/namespaceview.py
Now it's hard to find the selected element in the tree view. Esp. if the model gets bigger, such as the UML model.
When an element is focused in a diagram, it is selected in the tree view.
=> Auto select in tree view

poetry.lock, pyproject.toml, venv
Poetry updated to version 1.1.0, this updates to the latest and greatest 🥂 
=> Update poetry version

.github/workflows/build.yml, win-installer/msys2-install.sh
=> Use msys2-setup GitHub Action for Windows Builds

gaphor/plugins/diagramexport/__init__.py, gaphor/plugins/xmiexport/__init__.py, gaphor/ui/appfilemanager.py, gaphor/ui/errorhandler.py, gaphor/ui/filedialog.py, gaphor/ui/filemanager.py
Error messages used to be technical and hard to understand for non-technical users.
Issue Number: #387 
Human readable error dialog when a model does not load:
Or saved:
When overwriting a file:
=> Improve file load/save dialogs

gaphor/SysML/propertypages.py, gaphor/UML/classes/association.py, gaphor/UML/components/artifact.py, gaphor/core/styling/selectors.py, gaphor/diagram/text.py, gaphor/plugins/console/console.py, gaphor/plugins/xmiexport/exportmodel.py, gaphor/services/undomanager.py, gaphor/storage/parser.py, gaphor/transaction.py, gaphor/ui/gidlethread.py
Fix issues as identified on https://lgtm.com/projects/g/gaphor/gaphor/
=> Fix LGTM/CodeQL issues

gaphor/ui/diagrampage.py, gaphor/ui/event.py, gaphor/ui/mainwindow.glade, gaphor/ui/mainwindow.py, gaphor/ui/notification.py, gaphor/ui/tests/test_notifier.py
DnD to the diagram is not supported for all element. A message is only shown in the console, not to the user.
Issue Number: #386 
When you drag something like an Action to the diagram, a notification is shown that this behavior is not yet supported.
=> In-app notification

win-installer/build-installer.sh
=> Update pyinstaller to version 4.1.0

poetry.lock, pyproject.toml, win-installer/msys2-install.sh
=> Release version 2.1.0

.flake8, .pre-commit-config.yaml, gaphor/UML/actions/activitynodes.py, gaphor/UML/actions/flowconnect.py, gaphor/UML/classes/association.py, gaphor/UML/classes/tests/test_class.py, gaphor/UML/classes/tests/test_classconnect.py, gaphor/UML/classes/tests/test_interface.py, gaphor/UML/components/tests/test_connect.py, gaphor/UML/umlfmt.py, gaphor/UML/umllex.py, gaphor/UML/umloverrides.py, gaphor/codegen/uml_coder.py, gaphor/codegen/writer.py, gaphor/core/modeling/elementdispatcher.py, gaphor/core/modeling/tests/test_elementdispatcher.py, gaphor/core/modeling/tests/test_properties.py, gaphor/core/styling/parser.py, gaphor/diagram/general/tests/test_comment.py, gaphor/diagram/propertypages.py, gaphor/services/tests/test_undomanager.py, gaphor/storage/storage.py, gaphor/storage/tests/test_storage.py, tests/test_load_model.py
This PR enables flake8-eradicate which checks for committing commented out code.
There was some commented out code.
The commented out code has been removed.
=> Eradicate commented out code

gaphor/diagram/diagramtools/__init__.py, gaphor/diagram/diagramtools/grayout.py, gaphor/diagram/painter.py, gaphor/diagram/selection.py
It's not clear for users what a model element (such as Association, Generalization) can connect with.
Issue Number: #390 
Items are grayed out if a handle can not connect with any of its ports.
=> Gray out unconnectable elements

docs/modeling_language.md, docs/style_sheets.md, gaphor/UML/usecases/actor.py, gaphor/diagram/text.py, gaphor/ui/elementeditor.glade, win-installer/misc/win_installer.nsi
=> Fix misspelled words in docs

gaphor/core/modeling/diagram.py, gaphor/core/modeling/stylesheet.py, gaphor/core/modeling/tests/test_diagram.py, gaphor/core/modeling/tests/test_diagram_style.py, gaphor/storage/storage.py, gaphor/storage/tests/test_storage.py, gaphor/storage/tests/test_storage_uml_2_5_upgrade.py, gaphor/ui/appfilemanager.py, gaphor/ui/tests/test_diagrampage.py
`StyleSheet` was created instantly, by `Diagram`. This could cause issues when iterating the element factory (causing the elements dict to change unexpectedly.
Issue Number: #578 
Do no longer create it instantly, as it can cause problems with model loading.
Also the default style is set as a default attribute value.
=> Create style sheet on load and on new model

gaphor/UML/classes/tests/test_interfaceconnect.py, gaphor/UML/components/connectorconnect.py, gaphor/UML/components/tests/test_connect.py, gaphor/UML/interactions/interactionsconnect.py, gaphor/UML/interactions/tests/test_messageconnect.py, gaphor/UML/interactions/tests/test_ordering.py, gaphor/diagram/diagramtools/connector.py, gaphor/diagram/diagramtools/dropzone.py, gaphor/diagram/presentation.py, gaphor/diagram/tests/fixtures.py, gaphor/storage/tests/test_storage.py, gaphor/tests/testcase.py, gaphor/ui/tests/test_handletool.py, poetry.lock
Lines only connect when handles are connected to the edge of an element.
Issue Number: #390 
A line will connect to an element (shape) even if the mouse cursor is dragged inside the element.
=> In element select

gaphor/UML/sanitizerservice.py, gaphor/core/modeling/element.py, gaphor/core/modeling/properties.py, gaphor/services/tests/test_undo_presentation.py, gaphor/services/undomanager.py, gaphor/transaction.py, tests/test_undo.py
Undoing deleted items breaks easily.
Issue Number: #631 
The undo mechanism makes sure items are created first, then associations and attributes are set and lastly elements are unlinked.
=> Order undo events

gaphor/SysML/blocks/block.py, gaphor/SysML/blocks/property.py, gaphor/SysML/requirements/relationships.py, gaphor/SysML/requirements/requirement.py, gaphor/UML/actions/action.py, gaphor/UML/actions/activitynodes.py, gaphor/UML/actions/objectnode.py, gaphor/UML/classes/interface.py, gaphor/UML/classes/klass.py, gaphor/UML/classes/package.py, gaphor/UML/classes/tests/test_class.py, gaphor/UML/components/artifact.py, gaphor/UML/components/component.py, gaphor/UML/components/node.py, gaphor/UML/interactions/interaction.py, gaphor/UML/interactions/lifeline.py, gaphor/UML/states/finalstate.py, gaphor/UML/states/pseudostates.py, gaphor/UML/states/state.py, gaphor/UML/usecases/actor.py, gaphor/UML/usecases/usecase.py, gaphor/diagram/presentation.py, gaphor/diagram/tests/test_presentation.py, tests/test_undo.py
Inline styles are used to ensure mininal width and height for diagram items.
Clean up the code, minimize the use of inline styles (I'd like to move towards CSS classes instead). Many of these style statements proved not ro provide any use at all.
=> Cleanup inline styles

packaging/windows/msys2-install.sh
Testing to see if adding wheel as a Windows dependency speeds up the Python dependency installation step.
=> Add wheel as a Windows dependency

CONTRIBUTING.md, po/Makefile, po/hr.po
- Adding Croatian translation
- Adding informations about contributing translations
=> Croatian translation

gaphor/SysML/requirements/requirementstoolbox.py, gaphor/SysML/requirements/tests/conftest.py, gaphor/SysML/requirements/tests/test_connectors.py, gaphor/UML/classes/__init__.py, gaphor/UML/classes/classestoolbox.py, gaphor/UML/classes/containment.py, gaphor/UML/classes/containmentconnect.py, gaphor/UML/classes/tests/test_containmentconnect.py, gaphor/UML/tests/test_diagramitems.py, gaphor/UML/uml.py, gaphor/diagram/shapes.py, gaphor/ui/icons/Makefile, gaphor/ui/icons/hicolor/scalable/actions/gaphor-containment-symbolic.svg, gaphor/ui/icons/stensil.svg, models/UML.gaphor
This PR adds support for the containment relationship with UML/SysML.
It is possible to nest objects under a package, but the containment relationship is not supported.
Issue Number: #690 
Support for the containment relationship for those elements that can currently be nested.
=> Add Support for Containment Relationship

gaphor/ui/appfilemanager.py, gaphor/ui/mainwindow.py
It's hard to unset the file name.
_New from Template_ behaves the same as _Open_.
The _New from Template_ entry has been removed from the menu.
=> Remove the New From Template option

gaphor/application.py, gaphor/tests/test_application.py, gaphor/ui/__init__.py, gaphor/ui/appfilemanager.py
If an already opened model is opened again, it's loaded in a new window.
Issue Number: #482
When an already opened model is "opened", the window is focused.
* `gaphor.ui.event.FileLoaded/Saved` have been replaced by `gaphor.event.ModelLoaded/Saved`
=> Focus already opened model

gaphor/ui/layout.css, gaphor/ui/toolbox.py
`Gtk.ToolPalette` is not part of GTK 4.
Issue Number: #618 
Replace the `GtkToolPalette` by a `Gtk.Expander` and `Gtk.FlowBox`.
=> Gtk4 toolbox

packaging/Makefile
PyInstaller 4.3 was just released, this PR updates our packaging to use the latest version.
PyInstaller 4.2
PyInstaller 4.3
=> Upgrade PyInstaller to version 4.3

gaphor/UML/classes/classespropertypages.py, gaphor/UML/classes/tests/test_classespropertypages.py, gaphor/UML/classes/tests/test_propertypages.py, gaphor/core/modeling/collection.py, gaphor/diagram/propertypages.py
Attributes and operations do not reorder when reordered with drag-and-drop.
Issue Number: #777
The model is updated if items are reordered via DnD.
Also changed the abstract methods not to be protected (starting with a `_`).
=> DnD for element editor lists

.github/workflows/build.yml
On macOS it's easier to install GTK4 than on Ubuntu ;)
=> Add GTK4 build on macos

gaphor/C4Model/diagramitems/__init__.py, gaphor/C4Model/diagramitems/database.py, gaphor/C4Model/grouping.py, gaphor/C4Model/tests/test_modelinglanguage.py, gaphor/C4Model/toolbox.py, gaphor/storage/storage.py, gaphor/storage/tests/test_storage_c4_upgrades.py
The C4 Database item can not be styled properly. This is due to it's current name: `C4ContainerDatabaseItem`.
Issue Number: #828 
C4 Database item can be styles as expected:
```css
c4database [
color: blue;
}
```
=> Rename C4ContainerDatabaseItem to C4DatabaseItem

gaphor/SysML/blocks/proxyport.py, gaphor/UML/actions/activitynodes.py, gaphor/UML/interactions/executionspecification.py, gaphor/core/modeling/presentation.py, gaphor/storage/parser.py, gaphor/storage/storage.py, gaphor/storage/tests/test_parser.py, gaphor/storage/tests/test_storage_c4_upgrades.py, gaphor/storage/tests/test_storage_upgrades.py, gaphor/storage/upgrade_canvasitem.py, test-models/node-component-v2.1.gaphor
Code related to canvas items has been cleaned up, since diagram items are treated the same as model elements.
* `matrix` is loaded in `Presentation`
* matrix triggers are created properly, so 
* Pre-2.5 upgrades to diagram items are done during parsing
=> Cleanup model loading

.github/workflows/build.yml
Restores code signing for released versions.
The CI pipeline only codesigns when the reference is the master branch.
Codesigning is also enabled when the reference is a version tag.
=> Restore signing for tagged versions

gaphor/ui/namespacemodel.py
Model elements disappear on Windows.
Issue Number: #865 
They no longer disappear.
Seems to work on Windows, Linux and macOS.
=> Fix disappearing elements from tree view on Windows

docs/windows.md, packaging/windows/msys2-install.sh
Updates the Windows dev environment instructions to install and configure Poetry in a virtualenv.
Error loading shared library
Issue Number: #872 
Gaphor runs correctly
=> Fix Windows Dev Env Docs

CONTRIBUTING.md, docs/linux.md
This PR:
- Add clarifications/steps to linux dev-install docs 
- References the above dev-docs from `CONTRIBUTORS.md`
=> Developer documentation tweaks

.github/workflows/build.yml, packaging/Makefile, packaging/gaphor.spec.in, packaging/hooks/hook-gi.repository.GtkosxApplication.py, packaging/hooks/pre_safe_import_module/hook-gi.repository.GtkosxApplication.py
Upgrades PyInstaller to Version 4.4 including:
- Removes hooks pushed upstream
- Makes use of PyInstaller's new code sign capability
=> Upgrade PyInstaller to Version 4.4

gaphor/diagram/diagramtools/__init__.py, gaphor/ui/diagrams.py, poetry.lock
Mouse support is not as good as it can be
Issue Number: #877 
* zoom in has been simplified to Ctrl+=
* Zoom in with Ctrl+middle button scroll
* Pan with Button2 + drag
=> Improve zoom and pan for mouse

gaphor/UML/uml.py, models/UML.gaphor
Information flow is not supported.
Issue Number: #840
=> Add information flows to UML model

models/UML.gaphor
=> Fix typo in UML.gaphor

po/ca.po, po/es.po, po/fr.po, po/gaphor.pot, po/hr.po, po/it.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sv.po
We haven't rebuilt our translations in a while.
Would it be worth setting up a pre-commit hook or lint check to ensure that they are always current?
=> Rebuild translation portable objects

po/babel.ini, po/ca.po, po/es.po, po/fi.po, po/fr.po, po/gaphor.pot, po/hr.po, po/hu.po, po/it.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sv.po
.ui files are not scanned for translatable text
Issue Number: #941
Also scan .ui files.
=> Translations from UI files

README.md
Added location of the Desktop Entry Comment.
=> Update the README on How to Translate the Flatpak String

po/ko.po
=> Add a new Korean translation

gaphor/UML/classes/classconnect.py, gaphor/UML/classes/generalization.py, gaphor/UML/classes/tests/test_classconnect.py, gaphor/UML/classes/tests/test_copypaste.py, gaphor/storage/storage.py, gaphor/storage/tests/test_storage_c4_upgrades.py, gaphor/storage/tests/test_storage_upgrades.py, poetry.lock
This PR aligns Gaphor with other UML tools so that:
- Generalization relationships are created by going from specific to general
Generalizations are drawn from general to specific.
Issue Number: #929
Generalizations are drawn from specific to general.
Migration added for the breaking change.
=> Swap Generalization Arrow Directions

.github/actions/setup_and_test/action.yml, gaphor/i18n.py, po/build-babel.py, pyproject.toml
Translations do not seem to work.
Issue Number: #1024 
.mo file compilaton is part of the build and .mo files are included in the distribution.
=> Fix translations

gaphor/diagram/propertypages.py, gaphor/diagram/tests/test_uibuilder.py, gaphor/diagram/uibuilder.py, gaphor/plugins/console/console.py, gaphor/plugins/console/consolewindow.py, gaphor/services/helpservice/__init__.py, gaphor/ui/mainwindow.glade, gaphor/ui/mainwindow.py, po/nl.po
Parts of the application are translated, others are not.
I found out that the translatable text from the UI files was not translated.
Issue Number: #1027 
We use the `locale` library. This lib is using libintl (the C library). Now translations are also picked up by `Gtk.Builder`.
Does this also work on Windows?
=> Fix localization in UI files

gaphor/diagram/diagramtools/placement.py, gaphor/diagram/inlineeditors.py, gaphor/ui/diagrampage.py
When an item is created you'll have to double click to edit the name
Issue Number: #886
When a new item is created, the edit popup immediately.
=> Edit element name on create

.github/workflows/full-build.yml, .github/workflows/test.yml
- Bump harfbuzz, libtiff, glib, pkgconf, and fontconfig versions.
- Uses Meson to build fontconfig.
gvsbuild is out of date.
gvsbuild is current
=> Update to latest gvsbuild

gaphor/C4Model/toolbox.py, gaphor/RAAML/fta/ftatoolbox.py, gaphor/UML/actions/actionstoolbox.py, gaphor/UML/actions/objectnode.py, gaphor/UML/interactions/interactionstoolbox.py, gaphor/UML/states/statestoolbox.py, gaphor/diagram/diagramtoolbox.py, gaphor/diagram/presentation.py, gaphor/services/copyservice.py, gaphor/ui/diagrampage.py, gaphor/ui/mainwindow.py, gaphor/ui/namespace.py, gaphor/ui/recentfiles.py, po/ca.po, po/es.po, po/fi.po, po/fr.po, po/gaphor.pot, po/gl.po, po/hr.po, po/hu.po, po/it.po, po/ja.po, po/ko.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sv.po
Some text are not translated an remain in English.
Issue Number: #1090
More text is translated.
=> Translated messages

gaphor/UML/interactions/interactionstoolbox.py, gaphor/UML/interactions/message.py, gaphor/ui/icons/Makefile, gaphor/ui/icons/hicolor/scalable/actions/gaphor-reflexive-message-symbolic.svg, gaphor/ui/icons/stensil.svg
If you want to create a mesage that points back to the same lifeline (or execution spec) you have to lots of manual dragging.
Issue Number: #1006 
Add a Reflexive message to the toolbox.
=> Add Reflexive Message item

gaphor/UML/actions/actionstoolbox.py, gaphor/UML/states/statestoolbox.py, po/ca.po, po/es.po, po/fi.po, po/fr.po, po/gaphor.pot, po/gl.po, po/hr.po, po/hu.po, po/it.po, po/ja.po, po/ko.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sv.po
A name was provide for all initial/final actions and states and decision/fork nodes.
I think a default name is not required for these elements.
No name is provided by default.
=> No name for initial/final nodes

examples/decision-node.gaphor, gaphor/UML/actions/actionspropertypages.py, gaphor/UML/actions/activitynodes.py, gaphor/UML/actions/propertypages.glade, gaphor/UML/actions/propertypages.ui, gaphor/UML/actions/tests/test_actionspropertypages.py
It's not explicit wherther a decision node contains a DecisionNode, a MergeNode, or both.
Issue Number: #977 
The node type is printed right under the node, in small font. It can be shown/hidden from the property page.
=> Show underlaying DecisionNode type

gaphor/plugins/console/console.py, gaphor/plugins/console/consolewindow.py, poetry.lock, pyproject.toml
We use `rlcompleter`, which has two issues: auto-complete does not work smooth, and it's causing crashes on our CI machine (probably due to the readline library).
We use [Jedi](https://github.com/davidhalter/jedi) for auto-complete. In general auto-complete is a lot better now. It's easier to discover the model now.
This PR also contains a bunch of UX improvements for the console.
=> Use Jedi for auto-complete in the Python Console

gaphor/C4Model/toolbox.py, gaphor/RAAML/fta/ftatoolbox.py, gaphor/RAAML/stpa/stpatoolbox.py, gaphor/UML/classes/classestoolbox.py, gaphor/UML/classes/dependency.py, gaphor/UML/classes/generalization.py, gaphor/UML/profiles/packageimport.py, gaphor/UML/profiles/profilestoolbox.py, gaphor/UML/usecases/extend.py, gaphor/UML/usecases/include.py, gaphor/UML/usecases/usecasetoolbox.py
Some relationships are drawn in an unexpected direction. E.g. Generalization is drawn from specific to general type
Issue Number: #929
Directions have been inverted when drawing. This should feel more natural.
=> Swap relationship direction for Generalization, Dependency, Import, Include, and Extend

.github/actions/setup_and_test/action.yml, .github/workflows/full-build.yml, .github/workflows/test.yml
Updates harfbuzz to version 1.3.1 in Windows (and various other gvsbuild updates) and poetry to 1.1.12.
Out of date dependencies
Updates
=> Update gvsbuild and poetry version

gaphor/UML/classes/classestoolbox.py
For a couple of relationships, the direction was somewhat counter intuitive. A bunch of those have been fixed with #1129.
Issue Number: #929, #1197
Composite and Shared associations are now created from owner to owned element.
In addition, the created association are placed in the package of the diagram the association is created in.
=> Invert association creation

gaphor/diagram/grouping.py, gaphor/diagram/tools/dropzone.py, gaphor/diagram/tools/placement.py, gaphor/diagram/tools/tests/test_dropzone.py
Items can be dropped inside other items (like a Component in a Node), but the component will most likely be partly outside the node, since the node does not adapt its size.
Issue Number:  #1189
Resize the node whenever a (new) item is dropped on it.
=> Grow item when an item is dropped on it

gaphor/SysML/blocks/block.py, gaphor/SysML/requirements/requirement.py, gaphor/UML/classes/enumeration.py, gaphor/UML/classes/klass.py, gaphor/UML/classes/stereotype.py
Somewhere along the lines, empty compartments were not shown (height = 0).
Now an empty compartment is visible again.
=> Set a minimal height for compartments

gaphor/C4Model/modelinglanguage.py, gaphor/C4Model/toolbox.py, gaphor/RAAML/modelinglanguage.py, gaphor/RAAML/toolbox.py, gaphor/SysML/modelinglanguage.py, gaphor/SysML/toolbox.py, gaphor/UML/modelinglanguage.py, gaphor/UML/toolbox.py, gaphor/abc.py, gaphor/core/modeling/diagram.py, gaphor/core/modeling/modelinglanguage.py, gaphor/diagram/diagramtoolbox.py, gaphor/diagram/export.py, gaphor/diagram/painter.py, gaphor/services/modelinglanguage.py, gaphor/ui/diagrampage.py, gaphor/ui/diagrams.py, gaphor/ui/event.py, gaphor/ui/mainwindow.glade, gaphor/ui/mainwindow.py, gaphor/ui/mainwindow.ui, gaphor/ui/namespace.py, gaphor/ui/tests/test_namespace.py, gaphor/ui/tests/test_toolbox.py, gaphor/ui/toolbox.py, models/Core.gaphor
We only had one diagram type. The request has come up several times for specific diagrams. 
Fixes ##973.
Apart from the generic type, modeling language specific modeling types can be selected.
=> Diagram types

gaphor/ui/flowbox.py, gaphor/ui/greeter.py, gaphor/ui/styling.css, gaphor/ui/tests/conftest.py, gaphor/ui/toolbox.py
Clicking on a tool twice deselects it.
Selection is handled by Gtk.FlowBox. It allows us to better style the toolbox as well.
=> Clean up Toolbox

gaphor/UML/__init__.py, gaphor/UML/deletable.py, gaphor/core/modeling/coremodel.py, gaphor/diagram/deletable.py, gaphor/ui/namespace.py, models/Core.gaphor
It is not possible to simply delete an element from the tree view.
Issue Number: #1247
All Elements can be removed from the tree view. Exception rules can be defined where elements should not be allowed to be deleted, e.g. a property that acts as an association end.
Q: Are all cases covered?
=> Allow for deleting elements in the tree view

examples/sysml-brake-system.gaphor, gaphor/SysML/propertypages.glade, gaphor/SysML/propertypages.py, gaphor/SysML/propertypages.ui, gaphor/SysML/tests/test_propertypages.py, gaphor/UML/actions/partitionpage.py, gaphor/UML/components/componentspropertypage.py, gaphor/UML/components/connector.py, gaphor/UML/deletable.py, gaphor/UML/profiles/metaclasspropertypage.py, gaphor/UML/profiles/propertypages.glade, gaphor/UML/profiles/propertypages.ui, gaphor/diagram/propertypages.py, test-models/information-flow.gaphor
Issue Number: #841
Add example for car braking system.
=> Stereotypes for ItemFlow properties

gaphor/babel.py, po/bn.po, po/ca.po, po/de.po, po/es.po, po/fi.po, po/fr.po, po/gaphor.pot, po/gl.po, po/hr.po, po/hu.po, po/it.po, po/ja.po, po/ko.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sv.po, po/zh_Hans.po
Type values (`date`, `String`) are not translated
Issue Number: #1308 
`typeValue` properties are also translatable.
=> Translate typeValue in properties

gaphor/UML/classes/containmentconnect.py, gaphor/UML/classes/copypaste.py, gaphor/UML/classes/tests/test_containmentconnect.py, gaphor/UML/copypaste.py, gaphor/UML/deployments/copypaste.py, gaphor/UML/interactions/copypaste.py, gaphor/UML/modelinglanguage.py, gaphor/UML/states/copypaste.py, gaphor/UML/tests/test_copypaste.py, gaphor/core/modeling/__init__.py, gaphor/core/modeling/diagram.py, gaphor/core/modeling/element.py, gaphor/diagram/copypaste.py, gaphor/diagram/tests/test_copypaste_full.py, gaphor/diagram/tests/test_copypaste_link.py, gaphor/ui/namespacemodel.py, tests/conftest.py, tests/test_model_consistency.py
Fix issues uncovered by the Hypothesis tests, and extend the test coverage:
- model inconsistency due to copy/pasting a connected element
- fix cyclic dependency issues with Containment relation
- fix possible infinite loop in qualified name function
- Move `NamedElement` copy/paste functions to `gaphor.UML`
=> Extend Hypothesis Test Coverage and Fix Uncovered Bugs

gaphor/core/modeling/element.py, gaphor/core/modeling/elementdispatcher.py, gaphor/core/modeling/listmixins.py, gaphor/core/modeling/properties.py, gaphor/core/modeling/tests/test_properties.py
A few `try..except` clauses have been replaced by `if` clauses.
=> Refactor: replace try..except with if clauses

docs/design_principles.md, docs/index.rst
I wrote down some principles I've been using over the past years to guide Gaphor. Thing I like, and dislike (e.g. dialogs).
Does it contain enough rationale?
Are there topics that should be addressed as well?
=> Design principles

gaphor/SysML/blocks/connectors.py, gaphor/SysML/requirements/connectors.py, gaphor/UML/actions/flowconnect.py, gaphor/UML/classes/classconnect.py, gaphor/UML/profiles/extensionconnect.py, gaphor/UML/profiles/packageimportconnect.py, gaphor/UML/states/vertexconnect.py, gaphor/UML/usecases/usecaseconnect.py, gaphor/diagram/connectors.py
The names should now better reflect the intent.
As discussed [on Matrix](https://matrix.to/#/!maFZnGxzqXqppVZrTd:gitter.im/$UwE-dOrLZyQDhRUuuLaJxVB59hqACwBaKmqYDp5bkEM?via=gitter.im&via=matrix.org).
=> Rename relationship connector base classes

gaphor/UML/actions/partitionpage.py, gaphor/UML/tests/test_umllex.py, gaphor/ui/diagrampage.py, gaphor/ui/diagrams.py, gaphor/ui/elementeditor.py, gaphor/ui/filedialog.py, gaphor/ui/filemanager.py, gaphor/ui/mainwindow.py, gaphor/ui/namespace.py, gaphor/ui/statuswindow.py, gaphor/ui/toolbox.py
This PR does some refactoring using Sourcery:
- Use named expressions
- Separate out some functions and methods
- Remove a mutable default value in a method
=> Refactor Using Sourcery

.github/workflows/full-build.yml, .github/workflows/test.yml, docs/windows.md
This PR updates gvsbuild which has received a lot of updates including support for Visual Studio 2022 and fewer extra options are needed for a basic build.
Some libraries being used for Windows are out of date.
Everything should be pretty close to fully updated.
=> Update gvsbuild and simplify syntax

gaphor/RAAML/raaml.py, gaphor/SysML/sysml.py, gaphor/UML/uml.py, gaphor/codegen/coder.py, gaphor/codegen/tests/test_coder.py, pyproject.toml, tests/test_models_up_to_date.py
For code generation only models can be loaded that use the UML language.
Issue Number: #1486
* The code generator uses `ModelingLanguage`s to find the class from super models
* In addition to the UML language, additional languages can be loaded. (not sure if we need this)
=> Codegen use all defined modeling languages

gaphor/conftest.py, gaphor/core/modeling/element.py, gaphor/core/modeling/presentation.py, gaphor/storage/storage.py, gaphor/storage/tests/test_storage.py, gaphor/storage/xmlwriter.py, gaphor/ui/filemanager.py, tests/test_model_consistency.py
`gaphor.storage.save()` requires an `XMLWriter`.
Simplify the interface by requiring just a filename, similar to `load()`.
=> Storage cleanup

gaphor/plugins/console/console.py, gaphor/plugins/errorreports/__init__.py, gaphor/plugins/errorreports/errorreports.glade, gaphor/plugins/errorreports/errorreports.py, gaphor/plugins/errorreports/tests/test_errorreport.py, gaphor/ui/menufragment.py, gaphor/ui/tests/test_lifecycle.py, poetry.lock, pyproject.toml
Users do not see uncaught exceptions. However, they may be really valuable when diagnosing a problem
Issue Number: #1519
All uncaught exceptions are collected by an Error Reports service. Tools -> Error Reports. These errors can be looked up and attached to a GitHub issue.
A notification is created on the active session window to notify the user such an exception happened.
This allows us to uncover errors, even when the application is ran on Windows or from a Flatpak.
To make this work the Console had to do a little smarter exception handling.
=> Error Reports window

.github/workflows/full-build.yml, gaphor/__main__.py, gaphor/plugins/errorreports/errorreports.py, gaphor/ui/__init__.py, gaphor/ui/selftest.py, gaphor/ui/tests/test_selftest.py, pyproject.toml
We (Dan and me) have to manually check if a packaged version of Gaphor will actually start. 
To be new behavior:
=> Let Gaphor check for it's own health

gaphor/UML/actions/propertypages.ui, gaphor/UML/classes/propertypages.glade, gaphor/UML/classes/propertypages.ui, gaphor/UML/tests/test_umlfmt.py, gaphor/UML/tests/test_umllex.py, gaphor/UML/umllex.py, po/bn.po, po/ca.po, po/de.po, po/es.po, po/fi.po, po/fr.po, po/gaphor.pot, po/gl.po, po/hr.po, po/hu.po, po/it.po, po/ja.po, po/ko.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sv.po, po/zh_Hans.po
A union type can't be expressed. Example: `str | int`
Fixes Issue Number: #1563
Union types can be expressed.
=> Union types

gaphor/SysML/blocks/blockstoolbox.py, gaphor/UML/classes/enumeration.py
UML's Enumeration is made available in the SysML profile. However, Enumeration is not really supported. It should be a ValueType.
Issue Number: #1485
When you create an enumeration with the SysML profile selected, it displays a ValueType stereotype to the Enumeration.
=> Make SysML Enumerations also ValueTypes

.github/actions/linux_dependencies/action.yml, .github/actions/macos_dependencies/action.yml, .github/workflows/codeql-analysis.yml, .github/workflows/full-build.yml, _packaging/gaphor.spec, _packaging/hooks/hook-gi.repository.HarfBuzz.py, docs/linux.md, docs/macos.md, docs/windows.md, gaphor/UML/actions/partitionpage.py, gaphor/codegen/__init__.py, gaphor/plugins/console/console.py, gaphor/plugins/console/consolewindow.py, gaphor/services/helpservice/about.ui, gaphor/ui/__init__.py, gaphor/ui/elementeditor.py, gaphor/ui/elementeditor.ui, gaphor/ui/tests/conftest.py, gaphor/ui/tests/test_toolbox.py, gaphor/ui/uipreview.py
This PR:
- Switches to making GTK4 the default version
- Enables GtkSourceView for CSS highlighting with GTK4
- Enables libadwaita with GTK4
GTK version 3 is the default
Issue Number: #618 
GTK version 4 is the default
=> Make GTK4 the Default Version and Enable Adwaita

.github/workflows/full-build.yml
gvsbuild is now published to PyPI. This PR replaces checking out gvsbuild from source with the published version.
Update git hash to update the gvsbuild version
Bump the version using the published version.
=> Install gvsbuild with pip

gaphor/UML/actions/partition.py
When a partition is resized, the actions stay in the same place.
Issue Number: Fixes #1014
When a partition is resized, the actions are moved accordingly.
=> Resize of partition keeps actions in the same swimlane

docs/windows.md
This PR updates the docs to install gvsbuild and poetry with pipx in Windows.
=> Setup Windows dev environment using pipx

.readthedocs.yaml
Updates the Ubuntu version to 22.04 and the Python version to 3.10 for readthedocs.
=> Update Python and Ubuntu distro for readthedocs

.github/actions/setup_and_test/action.yml, .github/workflows/codeql-analysis.yml, poetry.lock
This PR updates Poetry to version 1.1.15
=> Update poetry to version 1.1.15

gaphor/SysML/blocks/connectors.py, gaphor/UML/actions/activityconnect.py, gaphor/UML/actions/pinconnect.py, gaphor/UML/classes/classconnect.py, gaphor/UML/classes/containmentconnect.py, gaphor/UML/deployments/connectorconnect.py, gaphor/UML/interactions/interactionsconnect.py, gaphor/UML/recipes.py, gaphor/UML/states/vertexconnect.py, gaphor/UML/usecases/tests/test_connect.py, gaphor/diagram/connectors.py, gaphor/services/undomanager.py
The application allows associations between class/block and actor/usecase, but the actual connection fails.
Issue Number: #1704
1. Creating a Connector object does not fail (needed for proper undo)
2. (todo) fix connection behavior.
=> Fix model corruption when connecting a Block to an Actor

gaphor/core/modeling/modelinglanguage.py, gaphor/ui/tests/test_treecomponent.py, gaphor/ui/tests/test_treesearch.py, gaphor/ui/treecomponent.py, gaphor/ui/treesearch.py
A filter is applied to all visible items in the tree view. This is not very useful, since we pretty much always want to find elements that are not yet visible.
Issue Number: #1696 
The search box performs as a proper search. It does directly select on type and searches the whole model.
The actual searching is encoded in `SearchEngine` (`treecomponent.py`) and the `treesearch.py` module.
=> Full tree search (GTK4)

gaphor/core/modeling/presentation.py, gaphor/diagram/general/tests/test_comment.py, gaphor/diagram/tests/test_presentation.py, tests/test_undo.py
When an element is removed, all it's relations stay on the diagram (albeit not backed by a model element).
Issue Number: #1009
When an element is removed from a diagram, all elements connecting to it will be removed as well.
E.g. when a class is removed, also remove the connected associations and dependencies.
=> Remove connected items from the diagram

.github/actions/setup_and_test/action.yml, .github/workflows/codeql-analysis.yml
Updates Poetry to version 1.2.1
=> Update poetry to version 1.2.1

.github/workflows/full-build.yml
Monthly update of gvsbuild including GTK 4.8.1 and gtksourceview 5.6.0.
=> Update gvsbuild to version 2022.3.0

gaphor/C4Model/diagramitems/database.py, gaphor/RAAML/fta/basicevent.py, gaphor/UML/actions/activitynodes.py, gaphor/UML/states/finalstate.py, gaphor/UML/states/pseudostates.py, gaphor/UML/usecases/usecase.py, gaphor/diagram/general/simpleitem.py, gaphor/diagram/shapes.py
We use the ellipse function from Gaphas. This one does not work when width or height is 0, something that happens initially for elements.
Issue Number: #1713 
For Use Case we already used a bezier based ellipse. Now this ellipse algorithm is used for all ellipse and circle shapes.
In addition, the API for this function is closer to the rest of our shape api's. The ellipse algorithm has been tweaked to make a perfectly round circle.
=> Fix invalid matrix error when creating use case

gaphor/services/helpservice/shortcuts.ui, gaphor/ui/appfilemanager.py, gaphor/ui/greeter.py
* Added Cut
* Fixed shortcuts for opening and new model
* Add Search to shortcuts window
The Shortcuts window is not complete.
Now shortcuts are correct and grouped more logically. Inspired by Builder.
=> Update Shortcuts window

gaphor/diagram/tests/test_merge.py, gaphor/diagram/tools/connector.py, poetry.lock
Issue Number: #1760
Improved callback.
=> Fix error when disconnecting line with multiple segments

models/RAAML.gaphor
There were some tweaks to the RAAML spec between the beta version and the official 1.0 release. This PR updates the comments in each diagram with the correct diagram IDs from the spec
=> Update RAAML diagram numbers

.github/actions/setup_and_test/action.yml
This PR updates poetry to version 1.2.2
=> Update poetry to version 1.2.2

.github/actions/windows_executables/action.yml, .github/workflows/full-build.yml
This PR switches to make GTK4 the default on Windows. It also updates gvsbuild to the current release.
Gaphor is packaged with GTK3 on Windows
Gaphor is packaged with GTK4 on Windows
=> Build Windows installers with GTK4

gaphor/services/helpservice/__init__.py, gaphor/services/helpservice/about.glade, gaphor/services/helpservice/about.ui
This PR upgrades the about dialog to use libadwaita.
=> Upgrade about dialog to libadwaita with GTK4

gaphor/diagram/tools/__init__.py, poetry.lock
Ctrl-scroll wheel zoom does no longer work since scrolling was properly fixed.
Issue Number: #1798 
Ctrl-scroll wheel does zoom the diagram.
Requires new Gaphas release
=> Fix zoom with mouse

_packaging/gaphor.spec, _packaging/hook-pydot.py, gaphor/plugins/autolayout/pydot.py, gaphor/plugins/autolayout/pydot_patch.py, gaphor/ui/selftest.py
Package Graphviz with the PyInstaller builds, to enable auto-layout without the need to have Graphviz installed separately.
NB. For now this PR is based on the `pydot-experiment` branch. Should change to `main` before merging.
Simply packaging all of Graphviz does not work, since it'll take (an older?) version of libcairo from the installed choco package.
=> Package Graphviz with PyInstaller builds

gaphor/ui/diagrampage.py, gaphor/ui/diagrams.py, gaphor/ui/tests/test_mainwindow.py
Gaphor on GTK4 still uses the good old Notebook.
Fixes #802
Use fancy new [Adw.TabView](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.2/class.TabView.html) and TabBar.
=> Adwaita tab view

.readthedocs.yaml, docs/_static/css/custom.css, docs/conf.py, docs/gaphor-services.md, docs/index.rst, docs/scripting.md, gaphor/UML/classes/association.py, gaphor/UML/classes/dependency.py, gaphor/UML/recipes.py, gaphor/codegen/coder.py, gaphor/diagram/export.py, gaphor/diagram/tests/test_export.py, gaphor/extensions/ipython.py, gaphor/extensions/sphinx.py, gaphor/extensions/tests/test_ipython.py, gaphor/plugins/autolayout/__init__.py, gaphor/plugins/autolayout/pydot.py, gaphor/plugins/autolayout/tests/test_pydot.py, gaphor/plugins/diagramexport/__init__.py, gaphor/services/modelinglanguage.py, gaphor/ui/diagrampage.py, poetry.lock, pyproject.toml
Gaphor has a lot of API. Provide some tutorials on the most common tasks.
I use [MyST-NB](https://myst-nb.readthedocs.io/en/latest/) to generate Jupyter Notebooks in markdown. This way I can provide examples and the readers can directly see the output.
A preview can be found on https://gaphor.readthedocs.io/en/docs-scripting/scripting.html.
Fixes #1746.
* `ModelingLanguageService` no longer requires an `EventManager`.
* I reworked some export functions. Also added EPS export (#1828), because of the changed interfaces for rendering.
=> Add documentation on how to interact with Gaphor programmatically

docs/scripting.md, gaphor/codegen/coder.py, gaphor/extensions/sphinx.py, gaphor/plugins/diagramexport/gaphorconvert.py, gaphor/storage/parser.py, gaphor/storage/storage.py, gaphor/storage/tests/test_loading.py, gaphor/storage/tests/test_parser.py, gaphor/storage/tests/test_storage_message_item_upgrade.py, gaphor/tests/test_application.py, gaphor/ui/errorhandler.py, gaphor/ui/filemanager.py, gaphor/ui/tests/test_filemanager.py, test-models/merge-conflict.gaphor, tests/test_action_issue.py, tests/test_load_model.py, tests/test_package_removal.py
The storage module has been stable for quite a while. However, the errors it produces are not very helpful to the user.
Issue Number: #388 
As a first stage towards #1845, let's make the storage module produce helpful error messages.
=> Storage module maintenance

.github/workflows/full-build.yml
This PR updates the Windows build to use Python 3.11. :rocket: 
=> Update Windows build to use Python 3.11

.github/actions/macos_dependencies/action.yml, .github/workflows/full-build.yml
Improve the macOS build:
* use environment variables for the python version
* Install only GTK 3 or 4 packages, not both
=> macOS build update

gaphor/i18n.py, gaphor/ui/diagrampage.py, gaphor/ui/mainwindow.py, gaphor/ui/styling.py
When running tests with Python 3.11, deprecation warnings appear
Code is updated for Python 3.9+.
=> Python 3.11 updates

gaphor/ui/mainwindow.ui
It's unclear what the icons in the header bar mean, until you click on them.
Issue Number: #1882 
Added tooltips.
=> Add tooltips to the application header icons

_packaging/gaphor.spec, docs/style_sheets.md, gaphor/ui/elementeditor.py, gaphor/ui/language-specs/gaphorcss.lang
The element editor shows official CSS properties different from our custom properties
Styling of all our properties and special property values is highlighted consistently.
=> Style sheet language

gaphor/UML/interactions/message.py
It takes a bit of effort to keep your sequence diagram messages horizontal.
Issue Number: #1863
Messages are horizontal. If you add extra line segments, the horizontal constraint is removed.
Should I add an option to disable this constraint on 1-segment lines?
=> Make sequence diagram messages horizontal by default

poetry.lock, pyproject.toml
This PR replaces a pre-release version of PyInstaller with the final version.
=> Update PyInstaller to version 5.7.0

gaphor/ui/selftest.py
On windows, Gaphor crashes when a model is loaded. Our 2.13.0 release is stable, though
Expand the self test to also load a model.
=> Load template as part of self-test

tests/test_load_model.py
Fixes: #1915
Nothing. All remains as is.
=> Remove tests that do not add to Gaphor's quality

.github/actions/setup_and_test/action.yml
AppImage build fails due to missing pip. See https://github.com/gaphor/gaphor/actions/runs/3685774039/jobs/6237157706.
Issue Number: #1918 
We know we have Python, so let's call pip as a Python module.
=> Use pip as Python module

poetry.lock, pyproject.toml
=> New handle style

org.gaphor.Gaphor.json, poetry.lock, pyproject.toml
Upgrade pycairo to 1.23.0 and fix the local flatpak build so it works with an upgraded pycairo.
=> Upgrade pycairo

.github/workflows/full-build.yml, .github/workflows/hypothesis-test.yml
We have better control over caches. We can restore and save separately.
See https://github.com/actions/cache/issues/92.
=> Use new actions/cache/(save|restore)

.github/workflows/full-build.yml
If part of a release build breaks, it could be that the artifacts have been uploaded to Pypi.org already.
Only publish to PyPI after all jobs succeed.
=> Publish to PyPI after all other jobs have passed

gaphor/storage/mergeconflict.py, gaphor/storage/tests/test_mergeconflict.py, gaphor/ui/filemanager.py, gaphor/ui/mainwindow.py, gaphor/ui/statuswindow.py, gaphor/ui/tests/test_filemanager.py, test-models/merge-conflict.gaphor
When a model has been edited on two branches, there's a big change of merge conflicts. It's not possible to resolve those merge conflicts with a text editor (our file format is xml).
One way would maybe be to figure our a merge-friendly file format, but since the model is littered with object references, this seems like a hard job.
Issue Number: #388 
Gaphor itself should aid in resolving merge conflicts on a semantic level. This should provide the user with the information needed to update a model with incoming changes.
=> Resolve (git) merge conflict: choose which branch to load

.github/workflows/full-build.yml
This PR updates GTK to 4.8.3 along with the other dependencies for Windows.
=> Update to gvsbuild 2023.1.0

.all-contributorsrc
=> Change name displayed on all-contributors

.github/actions/setup_and_test/action.yml, .github/workflows/codeql-analysis.yml
Updates poetry in CI/CD to version 1.3.2
=> Update poetry to version 1.3.2

gaphor/ui/greeter.py, gaphor/ui/mainwindow.py
It's hard to distinguish between releases and dev builds in CI
The header bar has the develop mode stripes in dev builds:
You'll have to change the version to `2.15.0.dev123` or something to see the change. We will normally not see it in our workspace.
=> Apply development mode for dev releases

docs/_static/css/custom.css, docs/_static/js/utterances.js, docs/conf.py
People can't comment on pages or point out mistakes, except for posting an issue on this repo.
Add a comment section to the end of the pages, so people can respond.
=> Add sphinx-comments

gaphor/ui/tests/test_treecomponent.py, gaphor/ui/tests/test_treemodel.py, gaphor/ui/treecomponent.py, gaphor/ui/treemodel.py, gaphor/ui/treesearch.py
Issue Number: #2044
Branches are abstracted in a new class `Branch`. This class decides if an element is shown directly under the parent node or in a separate "Relationship" node.
This way the tree build-up is localized and can be extended when needed. The `TreeModel` class takes care of the complete tree model.
=> Refactor and improve model browser

gaphor.doap
https://gitlab.gnome.org/World/apps-for-gnome/-/blob/main/METADATA.md#doap
=> meta: Add .doap-file

.github/workflows/full-build.yml
Updates GtkSourceView, Libadwaita, and Cairo in Windows.
=> Update gvsbuild to version 2023.2.0

docs/design_principles.md
The "Keep model in sync" design principle is somewhat contradicting.
A more clear explaination of the principle.
=> Update "Keep model in sync" design principle

.github/actions/linux_appimage/action.yml, poetry.lock
Closes #2017.
Issue Number: #2017
https://pyinstaller.org/en/v5.8.0/CHANGES.html
=> Update PyInstaller to version 5.8.0

.github/workflows/full-build.yml, _packaging/appimage/Dockerfile, pyproject.toml
=> Update AppImage docker image to 2023.3.0

gaphor/C4Model/propertypages.py, gaphor/SysML/propertypages.py, gaphor/UML/uicomponents.py, gaphor/diagram/general/uicomponents.py, gaphor/services/moduleloader.py, pyproject.toml
`gaphor.modules` modules have an `init()` function that doesn't do a thing
Just load the modules.
=> Just load modules for gaphor.modules entry points

gaphor/ui/diagrampage.py, gaphor/ui/elementeditor.py
When in dark mode, the CSS editor still has a white background.
The style editor color transitions with dark/light mode.
=> Css editor dark mode

.github/workflows/full-build.yml, org.gaphor.Gaphor.json
=> Upgrade development build to GNOME 44

gaphor/ui/mainwindow.py
LibAdwaita is complaining sometimes a dialog is opened without a parent window reference.
The main window is always available, so it can be used as a parent for any kind of popup.
=> Make main window always available

gaphor/UML/classes/tests/test_association.py, gaphor/diagram/presentation.py, gaphor/diagram/tests/test_presentation.py, poetry.lock, test-models/simple-items.gaphor
Fix issue exposed by https://github.com/gaphor/gaphor/actions/runs/4539848078/jobs/8000116693.
=> Fix orthogonal lines

gaphor/ui/modelbrowser.py
DnD in model browser only works for selected element(s).
Issue Number: #2182
Any element can be dragged.
=> Fix drag from model browser

.github/actions/macos_dmg/action.yml
Update the notarize, staple, and cert actions to new versions and new fork that isn't archived.
We also need 
Issue Number: #2197
=> Update notarize, staple, and cert actions

.github/workflows/full-build.yml
Updates libadwaita, glib, gobject-introspection, and other dependencies in Windows.
=> Update gvsbuild to 2023.4.0

.github/workflows/full-build.yml, org.gaphor.Gaphor.json
Issue Number: #2205
The Flatpak build is using a prepared GNOME 44 container. This reduces the load on flathub.
* Added tests in the (devel) flatpak manifest.
* Used [flatpak-github-actions](https://github.com/flatpak/flatpak-github-actions) to build the whole lot.
=> Update flatpak build

README.md
We have received a couple of requests for things that I don't think should be the focus of Gaphor in https://github.com/gaphor/gaphor/issues/2214 and https://github.com/gaphor/gaphor/issues/1363.
Sometimes it helps clarify the focus of things when we are also explicit about the things that aren't the focus of the project.
I know at one point, there was a lot of interest in MDA and creating executable models that could generate source code. I think the power of modeling is for the descriptive and analytical analysis that is possible. If you want an actual implementation, then just write the code. Do others agree?
=> Add non-goals to README

.github/workflows/full-build.yml
=> Update gvsbuild to 2023.5.0

gaphor/ui/elementeditor.ui
=> Update elementeditor.ui: typo

gaphor/services/undomanager.py, gaphor/transaction.py, tests/test_undo.py
If code in an event handler raises an error, this can cause an rollback loop.
Check if we're already performing a rollback from the undo manager. If so, do not try to roll back again.
=> Fix undo loops

README.md
=> Update Flathub logo to README

gaphor/storage/storage.py, gaphor/storage/tests/test_storage.py
Do not crash if a property or reference cannot be found.
NB. This was already the case for single references.
If an element type is not found, an exception is raised.
=> Be more lenient when loading models

docs/linux.md, docs/macos.md
Only windows docs have a section on debugging.
Issue Number: #2357
Updated docs for macOS and Linux.
Same we have for Windows already.
=> Add debug sections to macOS and Linux docs

gaphor/UML/interactions/lifeline.py, gaphor/diagram/connectors.py, gaphor/diagram/shapes.py, gaphor/main.py, gaphor/plugins/diagramexport/exportcli.py, gaphor/storage/parser.py, gaphor/ui/styling.css
Sourcery refactorings and other cleanup.
=> Various Sourcery refactoring

gaphor/ui/elementeditor.ui, gaphor/ui/help/__init__.py, gaphor/ui/help/shortcuts.ui, gaphor/ui/layout.py, gaphor/ui/mainwindow.py, gaphor/ui/mainwindow.ui, po/ca.po, po/cs.po, po/de.po, po/es.po, po/fi.po, po/fr.po, po/gaphor.pot, po/gl.po, po/hr.po, po/hu.po, po/it.po, po/ja.po, po/ko.po, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sl.po, po/sv.po, po/ta.po, po/tr.po, po/zh_Hans.po
Gaphor can be maximized, but not put in full screen mode.
Full screen mode.
Also updated the Shortcuts window and added a shortcut to show the Shortcuts window.
Updated translations too, since the terminology is not _that_ much different.
=> Add a fullscreen mode to Gaphor

.github/workflows/scorecard.yml, SECURITY.md
Add a security policy to the project and add scorecard checks.
=> Create a Security Policy and Run Scorecard Checks

gaphor/UML/interactions/interactionsconnect.py, gaphor/UML/interactions/tests/test_messageconnect.py
Issue Number: #2411
Models load with messages connected to both a lifeline's lifetime and an execution specification.
=> Fix connect interaction fragments

.github/workflows/full-build.yml, CHANGELOG.md, pyproject.toml
This PR prepares for the next release. I also regenerated the dispatch tokens in an attempt to fix #2407.
Issue Number: #2407
=> Prepare release for 2.19.3, fix dispatch tokens

CHANGELOG.md, gaphor/UML/actions/activity.py, gaphor/UML/actions/activitypropertypage.py, gaphor/UML/actions/tests/test_activitypropertypage.py, gaphor/UML/classes/classespropertypages.py, gaphor/diagram/presentation.py, gaphor/diagram/propertypages.py
Parameters with long names get out of the box
Issue Number: #2429 
Parameter text remains inside the box.
=> Scale parameters to contain all text

gaphor/SysML/sysml.py, gaphor/SysML/tests/test_sysml.py, models/SysML.override, pyproject.toml, tests/test_models_up_to_date.py
`Requirement.derived,satisfiedBy,etc.` are not implemented
Issue Number: #2405
In order to make it simpler to navigate requirements, the derived attributes have been implemented.
=> Add SysML Requirements trace derived unions

.github/workflows/full-build.yml
Updates gvsbuild to version 2023.7.0
=> Update gvsbuild to version 2023.7.0

gaphor/storage/storage.py, gaphor/storage/tests/test_storage_upgrades.py
The current upgrade function did only cover Property, no sub-types.
Fixes #2466.
ProxyPort is upgraded, similar to Property.
=> Fix loading of ProxyPorts with informationFlow attached

CHANGELOG.md, pyproject.toml
This PR prepares for the 2.19.3 release.
=> Prepare for 2.19.3 release

gaphor/diagram/painter.py
Issue Number: fixes #2496
Since painting is async, there is a possibility that the item has been removed from the diagram before it's actually drawn.
=> Ensure painter is only drawing on valid diagrams

gaphor/UML/classes/associationpropertypages.py
=> Fix error when inverting association

gaphor/diagram/propertypages.py, gaphor/diagram/tests/test_propertypages.py, gaphor/storage/parser.py, gaphor/storage/storage.py, gaphor/storage/tests/test_storage_upgrades.py
Notes are applied on diagram items, so they do are not visible in other diagrams
Issue Number: #2522
Notes are applied to model elements.
During loading, notes are transferred to the model elements.
=> Fix notes: should be applied to model elements

gaphor/diagram/shapes.py, gaphor/ui/filedialog.py
Pins are rendered weirdly.
Issue Number: fixes #2428 
Border rendering van handle positions where top/left is not (0, 0).
=> Fix weird pin rendering

.github/workflows/full-build.yml
I noticed that PR's coming from contributors are not built here.
Therefore errors can slip though, since we do not have the lint/build in place to check things.
Build PR's from contributors.
=> Build incoming pull requests

gaphor/SysML/blocks/block.py
Operations are not shown.
Fixes #2567.
Operations are shown.
=> Fix displaying operations in blocks

.github/workflows/full-build.yml
Upgrades Gvsbuild, this will fix the Windows build failures that others were getting when running CI on their fork, and it upgrades all the used dependencies to the latest.
=> Upgrade Gvsbuild to 2023.7.1

gaphor/ui/diagrampage.py
Issue Number: #2598 
Diagram background is properly set on a per-diagram basis.
Additionally the style context is properly removed when the diagram is closed.
=> Fix diagram background shouldn't be shared between open models

gaphor/C4Model/modelinglanguage.py, gaphor/C4Model/toolbox.py, gaphor/RAAML/modelinglanguage.py, gaphor/RAAML/toolbox.py, gaphor/SysML/modelinglanguage.py, gaphor/SysML/toolbox.py, gaphor/UML/modelinglanguage.py, gaphor/UML/toolbox.py, gaphor/abc.py, gaphor/core/modeling/modelinglanguage.py, gaphor/diagram/diagramtoolbox.py, gaphor/services/modelinglanguage.py, gaphor/ui/modelbrowser.py
Allows creating new elements directly in the model browser.
Issue Number: https://github.com/gaphor/gaphor/issues/2552
=> New element creation through model browser

.github/workflows/full-build.yml
Upgrades Windows to use GTK 4.12.0
=> Update Gvsbuild to version 2023.8.0

gaphor/ui/diagrams.py
Cannot move elements with arrows (alt and arrow)
Issue Number: #2565 
Elements can be moved using arrows (alt, alt-shift-arrow)
=> Move diagram elements with the arrow keys

CHANGELOG.md, gaphor/SysML/blocks/block.py
Issue Number: https://github.com/gaphor/gaphor/issues/2613
=> Fix block not showing parts

gaphor/SysML/propertypages.py
Attributes and operations are displayed for requirements
Issue Number: #2588
Removed display of attributes and operations for requirements
=> Removed unnecessary operations and attributes for requirements

gaphor/ui/__init__.py, gaphor/ui/macosshim.py, gaphor/ui/tests/test_macosshim.py
Issue Number: #2636
macOS keybindings work again. Also added a test to avoid this regression again.
=> Enable macOS keybindings again

gaphor/ui/greeter.py
Issue Number: #2623
This makes sure the Greeter is on top (on macOS).
=> Present the Greeter, instead of only making it visible

gaphor/UML/tests/test_uml2_overrides.py, gaphor/UML/umloverrides.py
Issue Number: #2650
Fixed Component.required property.
=> Add tests and fix Component.required

docs/style_sheets.md, gaphor/core/modeling/stylesheet.py, gaphor/ui/modelbrowser.py
The system style sheet may serve as inspiration.
https://gaphor--2658.org.readthedocs.build/en/2658/style_sheets.html#system-style-sheet
=> Add system style sheet to the documentation

.github/workflows/full-build.yml
GTK 4.12.1 for Windows.
Windows had GTK 4.12.0
Windows get GTK 4.12.1
=> Update Gvsbuild to 2023.9.0

docs/plugins.md
Issue Number: #2546
Better docs?
=> Improve docs regarding plugins a little

docs/macos.md
Homebrew path has been updated. Now the docs are in line.
=> Update docs with new homebrew path

gaphor/diagram/presentation.py
Issue Number: Fixes #2739.
This makes it easier to select a line with a trackpad.
Does this work better?
=> Increase line tolerance to 4

gaphor/transaction.py
The `@transactional` annotation was using a global set and a "class".
Use a nice, enclosed object, instead of a global variable and class methods.
=> Clean up transactional event handling

.github/workflows/full-build.yml
Updates Windows to GTK 4.12.3.
Windows uses GTK 4.12.1
Windows uses GTK 4.12.3
=> Update Gvsbuild to version 2023.10.1

.gitignore, docs/_static/js/utterances.js, gaphor/SysML/blocks/proxyport.py, gaphor/SysML/blocks/tests/test_proxy_port.py, gaphor/UML/actions/pin.py, gaphor/core/modeling/properties.py, gaphor/core/styling/tests/test_css.py, gaphor/diagram/tests/test_presentation.py
I gave [Sonar Cloud](https://sonarcloud.io/project/overview?id=gaphor) a try.
It detected a few issues that I fixed, apart from that a lot of false positives.
=> Boyscouting

poetry.lock, pyproject.toml
Closes #2006.
Old Sphinx since we were waiting on MyST dependencies
New Sphinx :)
=> Update Sphinx to version 6.0

.github/workflows/full-build.yml, tests/test_architecture.py
- Architecture test rules have been fine tuned. `gaphor.diagram` is still a bit problematic since it has a (cyclic) dependency on `gaphor.ui` and `gaphor.UML`, but the dependencies have been explicitly specified now.
- Build artifacts also for PR's created by Dependabot. We should be able to assess updates on libraries like PyInstaller.
=> Arch rules & build update

gaphor/ui/__init__.py
Files cannot be opened by dragging them on the application icon.
=> Fix DnD file opening on macOS

.github/workflows/hypothesis-test.yml
We updated our full-build to use Fedora, but I forgot to update hypothesis as well. This PR updates the hypothesis workflow to use Fedora as well.
Hypothesis tests are failing
Issue Number: #2861
Hypothesis tests are failing
=> Fix libadwaita 1.4.0 missing for hypothesis tests

gaphor/SysML/diagramtype.py, gaphor/SysML/tests/test_drop.py
=> Add support for dropping SysML diagrams on diagrams

CHANGELOG.md, pyproject.toml
Updates change log and bumps version.
=> Prepare for 2.22.1 release

gaphor/ui/selftest.py, gaphor/ui/tests/test_selftest.py
* Test all schemas in one go. 
* Be more verbose with logging if the self-test unit test fails.
* For tests to properly fail (and not time out), an exception has to be raised.
=> Simplify GSettings schema self test

gaphor/ui/icons/Makefile, gaphor/ui/icons/hicolor/scalable/actions/gaphor-merge-node-symbolic.svg, gaphor/ui/icons/stencil.svg
Issue Number: #2874
Merge icon is also present.
I found that the merge node, in a combined merge/decision node, shows on top level.
=> Add merge-node icon

README.md
Logo is missing on readme
All logos have been moved to /data/logos.
=> Fix logo on readme

README.md
It's slightly more than 32 nowadays.
=> Fix all contributors

gaphor/settings.py
App crashes in case there's no default Gio GSettings source.
Issue Number: Reported on Matrix
Be extra defensive about the availability of GSettings sources.
=> Be very defensive about settings schema sources

gaphor/ui/mainwindow.py, gaphor/ui/tests/test_mainwindow.py
Currently a window is always opened in "windowing" mode.
Restore maximized and fullscreen mode when a model is reopened.
Tested on macOS.
=> Restore windows in maximized and fullscreened state

.github/workflows/full-build.yml
Updates Windows to GTK 4.12.4.
=> Update Gvsbuild to 2023.12.0

gaphor/diagram/export.py, gaphor/diagram/tests/test_instanteditors.py, gaphor/diagram/tools/__init__.py, gaphor/diagram/tools/dropzone.py, gaphor/diagram/tools/itemtool.py, gaphor/diagram/tools/magnet.py, gaphor/diagram/tools/placement.py, gaphor/diagram/tools/shortcut.py, gaphor/diagram/tools/tests/conftest.py, gaphor/diagram/tools/tests/test_dropzone.py, gaphor/diagram/tools/tests/test_tool_set.py, gaphor/diagram/tools/textedit.py, poetry.lock, tests/test_comment_line_placement.py
No changes, just support Gaphas 4.0: https://github.com/gaphor/gaphas/pull/741.
Before merging:
=> Update to Gaphas 4.0

po/ca.po, po/cs.po, po/de.po, po/es.po, po/fi.po, po/fr.po, po/gaphor.pot, po/gl.po, po/hr.po, po/hu.po, po/it.po, po/ja.po, po/ko.po, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sl.po, po/sv.po, po/ta.po, po/tr.po, po/zh_Hans.po
`.po` files have not been updated for a while.
Everything up to date.
=> Update .pot and .po files

CHANGELOG.md, gaphor/ui/help/about.ui, pyproject.toml
This PR bumps the version and prepares for the next release.
=> Prepare for 2.23.0 release

po/ca.po, po/cs.po, po/de.po, po/es.po, po/fi.po, po/fr.po, po/gaphor.pot, po/gl.po, po/hr.po, po/hu.po, po/it.po, po/ja.po, po/ko.po, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sl.po, po/sv.po, po/ta.po, po/tr.po, po/zh_Hans.po, poetry.lock
Following the release of 2.23.0, this PR updates our dependencies and translations.
=> Bump dependencies and translations

gaphor/core/modeling/diagram.py, gaphor/core/modeling/tests/test_style_attributes.py, gaphor/core/styling/__init__.py, gaphor/core/styling/pseudo.py, gaphor/core/styling/tests/test_compiler.py, gaphor/diagram/shapes.py
`[subject]` should check for the existance of the subject property, not its value.
Issue Number: #2994
The `[subject]` expression now checks for the presence of the subject *attribute*, whether it's set or not.
Fix CSS attribute.
=> Fix attribute check

CHANGELOG.md, pyproject.toml
Bumps the version and updates the changelog.
=> Prepare for version 2.23.1 release

gaphor/UML/actions/activitypropertypage.py, gaphor/UML/classes/classespropertypages.py, gaphor/UML/classes/enumerationpropertypages.py, gaphor/ui/modelbrowser.py
If a parameter/attribute/operation/enumeration name is empty, the placeholder text is shown.
Issue Number: [Reported on Matrix](https://matrix.to/#/!maFZnGxzqXqppVZrTd:gitter.im/$RfXDKSTgqZJ32e2ElosRttOvJAERo1xWo299XDKS1a0?via=gitter.im&via=matrix.org&via=gnome.org)
Show an empty cell.
=> Deal with parameters without a name

gaphor/plugins/console/consolewindow.py, gaphor/plugins/errorreports/errorreports.py, gaphor/plugins/errorreports/errorreports.ui, gaphor/ui/greeter.ui, gaphor/ui/mainwindow.ui, gaphor/ui/styling.css
The interface is a bit more flat. This makes it look a bit less out of place on macOS at least ;).
Also made the Error Reports window use CSD.
=> Update Adwaita style

.github/workflows/full-build.yml
GTK 4.12.5 and friends on Windows.
=> Update Gvsbuild to version 2024.1.0

gaphor/UML/classes/association.py, gaphor/UML/classes/associationpropertypages.py, gaphor/UML/classes/tests/test_association.py, gaphor/UML/informationflow.py, gaphor/UML/interactions/lifeline.py, gaphor/diagram.css, gaphor/diagram/painter.py, gaphor/diagram/shapes.py, gaphor/ui/elementeditor.ui, gaphor/ui/mainwindow.ui
Just a few small left-over fixes.
=> Odds and ends

CHANGELOG.md
=> Update release notes for 2.24.0

docs/scripting.md
=> Fix encoding in scripting example

gaphor/SysML/requirements/requirement.py, gaphor/diagram.css
Requirement text is not wrapped. This is not desired, as this text description can become quite long.
Issue Number: Fixes #3094
Text is wrapped, as expected. Also extra nodes have been added for req. id and text.
=> Wrap requirement text

poetry.lock, pyproject.toml
Issue Number: Fixes https://github.com/gaphor/gaphas/issues/773
Ensure we use at least Gaphas 4.0.
Also updated setuptools, identify, and hypothesis.
=> Require Gaphas >=4

docs/locale/docs.pot, docs/locale/nl/LC_MESSAGES/docs.po, pyproject.toml
Fix merge conflict with Weblate.
=> Unlock weblate

gaphor/application.py
Now the greeter window will stay open after all session windows are closed.
Fixes #3076.
=> Do not quit if there are windows open after sessions are closed

gaphor/RAAML/raaml.py, models/RAAML.gaphor
This is a step towards creating table support by integrating changes to the RAAML profile to support HAZOP analysis. The next step will be to use these profile types to add to a simple table.
=> Add HAZOP table elements to RAAML profile

docs/linux.md, docs/locale/docs.pot, docs/macos.md
=> docs: Fix typo “is vscode” to “in vscode”

_packaging/windows/build-win-installer.py, examples/list_classes.py, gaphor/codegen/override.py, gaphor/codegen/tests/test_coder.py, gaphor/main.py, gaphor/services/properties.py, gaphor/tests/run_script.py, gaphor/ui/appfilemanager.py, gaphor/ui/installschemas/__init__.py, gaphor/ui/tests/test_mainwindow.py, gaphor/ui/uipreview.py, po/check-babel.py, pyproject.toml, tests/test_elements_have_owner.py
Dan checks a PR I wrote and sees a dangling `print` statement.
[Ruff checks](https://docs.astral.sh/ruff/rules/#flake8-print-t20) for `print` statements.
=> Check for print statements

gaphor/plugins/align/align.py, gaphor/ui/filemanager.py, gaphor/ui/tests/test_filemanager.py, tests/test_package_removal.py
Nothing new. Just a bit of maintenance.
=> Refactor align service and cleanup unused arguments

gaphor/ui/greeter.py, gaphor/ui/greeter.ui
Issue Number: Fixes #3179
Should only show if there are recently opened files. Also fixed the text.
=> Fix greeter label for recent files

gaphor/UML/profiles/stereotypepropertypages.py, gaphor/diagram/tools/dnd.py, gaphor/diagram/tools/placement.py
This is some fallout from #3148:
* Stereotype editor is shown for elements that have no subject
* Update the editor when a new element is placed on the diagram
=> Some fixes for the editors change

gaphor/ui/greeter.ui, gaphor/ui/styling.css
Issue Number: Fixes #3178
The `.title` CSS class has many uses in the Adwaita style sheet and should not be redefined.
=> Fix greeter row style

gaphor/ui/modelbrowser.py
Fixes #2627.
Show the right menu.
=> Show right popover menu after profile change

gaphor/UML/interactions/__init__.py, gaphor/UML/interactions/drop.py, gaphor/UML/interactions/tests/test_drop.py, gaphor/diagram/drop.py
Issue Number: #2563
When you drop a Connectable Element (Interface, Property, Parameter) on a Lifeline, the type is set.
=> Drop a ConnectableElement on a Lifeline

gaphor/ui/diagrampage.py
Items without any connected items are not properly displayed.
All items in a diagram are updated once a view is created.
Follow-up fix for #3205.
=> Fix initial display of items without relations

gaphor/ui/tests/test_selftest.py
It fails often, and a retry fixes it normally.
=> Retry self-test test case on macOS

docs/models/core_element.rst, gaphor/core/modeling/diagram.py, gaphor/diagram/export.py, gaphor/plugins/align/align.py, gaphor/plugins/autolayout/pydot.py, gaphor/ui/diagrampage.py
Some fall-out from #3205.
* Update docs, since users now need to know about the `update()` method.
* Use `Diagram.ownedPresentation` instead of `Diagram.get_all_items()`.
* Update diagram on stylesheet change.
=> More docs and fixes for update 

gaphor/core/modeling/diagram.py
Issue Number: related to #3205 
A small optimization to only emit `DiagramUpdateRequested` once for each update cycle.
=> Only emit update-requested event on first request

.github/workflows/full-build.yml
Updates Windows to GTK 4.14.1 and other related libraries.
=> Update Gvsbuild to version 2024.4.1

docs/contribute.md, docs/index.rst
Based on feedback from @FranciscoTGouveia, I added a bit of prose on how to contribute.
The text on https://gaphor.org/contribute/ needs an update once this is merged.
=> Add some documentation on contributing

docs/changelog.rst
Fixes #3234 by removing the change log.
Issue Number: #3234
=> Remove change log from translations

CHANGELOG.md, gaphor/ui/help/about.ui, pyproject.toml
Bump version, update change log, and add some new contributors to the about Window.
=> Prep for version 2.25.0 release

gaphor/core/styling/compiler.py, gaphor/core/styling/tests/test_compiler.py
Issue Number: #3263
The method returns `None` now, but strings were expected at some places.
=> Fix: deal with absense of attributes

gaphor/ui/mainwindow.ui
Zoom button disappeared in the latest version. This PR adds them back
Issue Number: Fixes #3255
=> Add the zoom buttons back

CHANGELOG.md, gaphor/ui/help/about.ui, pyproject.toml
Prepare for version 2.25.1 release.
=> Prepare for 2.25.1 release

tests/test_auto_layouting.py
test is disabled due to large amount of time required
Issue Number: #2104 
test completes in few seconds. Realized by setting the hypothesis testing to limit itself to generating examples (and not compare, reduce etc), see https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.Phase. Also limit the number and extend of tests.   
Feel free to adjust the setting parameters; I just picked something that achieved completion in few seconds and which I believed made sense.
=> Re-enable auto-layout tests

.github/workflows/full-build.yml
Update GTK version to 4.14.4, released May 2nd.
=> GTK 4.14.4 is available, drop workaround

tests/test_plugins.py
I ran into this while coding in the garden. Let's skip the one test that requires access to PyPI if no internet access is available.
=> Skip plugin test if internet is not available

docs/scripting.md
Added example of updating existing elements using transactions in a script.
=> Docs: add info about scripting updates to existing elements

docs/scripting.md
Added example of simple element validation to scripting.md
=> Script docs validation example

gaphor/UML/actions/activitypropertypage.py, gaphor/UML/classes/classespropertypages.py, gaphor/UML/classes/enumerationpropertypages.py, gaphor/UML/profiles/stereotypepropertypages.py, gaphor/UML/propertypages.py, gaphor/ui/modelbrowser.py, gaphor/ui/treemodel.py
When you create a diagram and add an element. the diagram shows in editable mode in the model browser.
Issue Number: fixes #3326
Editable mode is restored.
I also simplified the code a bit regarding editing.
I want to figure out if er actually need an `editing` property in the model class. Maybe something for a future PR ;).
=> Fix model entry shows editable

docs/scripting.md, gaphor/entrypoint.py
Updated docs so that cells execute. Simplified validation rules so they apply to my_model  
- [ x] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [ x] I have read, and I understand the GNOME [Code of Conduct](https://conduct.gnome.org/)
- [ x] Documentation content changes
Issue Number: 3312
Scripting docs build with all example code in code-cells 
- [ x] No
=> fixed execution issues in scripting docs

gaphor/diagram.css, gaphor/diagram/general/diagramitem.py, gaphor/diagram/painter.py, gaphor/event.py, gaphor/storage/recovery.py, tests/test_architecture.py
You can set stereotypes on diagrams.
Show stereotypes on diagrams.
=> Diagram stereotypes

gaphor/diagram/group.py, gaphor/ui/tests/test_modelbrowser.py
Fixes #3229.
Check fir all parents before allow an owner to change.
=> Improve check to avoid cycles in ownership

CHANGELOG.md, gaphor/ui/help/about.ui, pyproject.toml
Update changelog and bump version.
=> Prepare for version 2.26.0 release

gaphor/UML/actions/flowconnect.py, gaphor/UML/classes/dependency.py, gaphor/UML/classes/dependencypropertypages.py, gaphor/UML/recipes.py, gaphor/core/modeling/__init__.py, gaphor/core/modeling/element.py, gaphor/core/modeling/event.py, gaphor/services/tests/test_undomanager.py, gaphor/services/undomanager.py, gaphor/storage/recovery.py, gaphor/storage/tests/test_recovery_recorder.py
* undo does not work when changing dependency type
* dependency type changes are not recorded
Changes of element type are recorded for undo and recovery.
=> Fix undo and recovery of Dependency type

gaphor/UML/classes/association.py, gaphor/UML/classes/associationpropertypages.py
Dropping an association causes an exception.
Issue Number: Fixes #3359
No more exceptions.
=> Fix exception when dropping an association on a diagram

.github/workflows/full-build.yml
Updates GLib and other dependencies for Windows.
=> Monthly Gvsbuild update

.github/actions/macos_dmg/action.yml, .github/workflows/full-build.yml, gaphor/ui/selftest.py
We only build for the Intel platform, and ARM needs to be transpiled.
Issue Number: Fixes #3309
Deliver 2 builds: one for Intel and one for Arm.
* The website should also be updated.
* Brew cask recipe should fetch version based on architecture.
For hints on matrix builds: https://github.com/orgs/community/discussions/26639
=> Support macOS ARM (Apple Silicon)

.all-contributorsrc
=> Update nickname .all-contributorsrc

docs/design_principles.md, docs/gaphor-services.md, docs/plugins.md, docs/windows.md
Nothing major, just some things that caught my eye.
=> Some documentation updates

.github/workflows/full-build.yml, .pre-commit-config.yaml, _packaging/windows/build-win-installer.py, gaphor/RAAML/fta/majorityvotegate.py, gaphor/UML/actions/action.py, gaphor/UML/actions/activitynodes.py, gaphor/UML/actions/partition.py, gaphor/UML/classes/tests/test_associationconnect.py, gaphor/UML/profiles/tests/test_stereotypepropertypages.py, gaphor/core/styling/tests/test_compiler.py, gaphor/core/styling/tests/test_declarations.py, gaphor/diagram/tests/test_copypaste_full.py, gaphor/diagram/tests/test_copypaste_grouping.py, gaphor/diagram/tests/test_shapes.py, gaphor/plugins/console/console.py, gaphor/services/tests/test_undo_diagram.py, gaphor/storage/tests/fixtures.py, gaphor/ui/diagrampage.py, gaphor/ui/installschemas/__init__.py, gaphor/ui/tests/test_actiongroup.py, gaphor/ui/tests/test_lifecycle.py, po/build-babel.py, pyproject.toml, tests/test_plugins.py
We have `PYTHONWARNDEFAULTENCODING` defined in our build script.
Instead let's add linting rules that enforce best practices.
See https://docs.astral.sh/ruff/rules/#warning-w_1
=> More linting rules

gaphor/ui/diagrampage.py, gaphor/ui/modelbrowser.py
This provides the right conditions to trigger a context menu, even on macOS (for GTK 4.16).
=> Use Gdk.Event.triggers_context_menu()

docs/style_sheets.md, gaphor/core/styling/__init__.py, gaphor/core/styling/declarations.py, gaphor/diagram.css, gaphor/diagram/shapes.py, gaphor/templates/c4model-example.gaphor, gaphor/ui/greeter.py, gaphor/ui/language-specs/gaphorcss.lang
We have no example model for C4.
Issue Number: https://github.com/gaphor/gaphor/discussions/3412
Implement the canonical C4 Banking System example.
* Added a `max-width` property for text.
=> Add C4 banking example

.github/workflows/full-build.yml
Monthly GTK update for Windows.
=> Update Gvsbuild to 2024.8.0

.github/constraints.txt, .github/workflows/full-build.yml, _packaging/hook-pydot.py, docs/windows.md
- Fix an index out of range error when packaging Graphviz on Windows with PyInstaller
- Overwrite Python using brew prior to installing packages to fix brew linking errors
- Update the docs to use WinGet for package management since I think that is now the more modern option.
=> Fix Windows and macOS Build

.github/constraints.txt, .github/workflows/gvsbuild-updater.yml
Adds a weekly check for new Gvsbuild versions and creates a PR if a new version is found.
Manual version changes after a release
Automatic version bumps
=> Automatically update Gvsbuild version

gaphor/services/undomanager.py, gaphor/ui/elementeditor.ui, gaphor/ui/mainwindow.py, gaphor/ui/mainwindow.ui, gaphor/ui/styling.css
Issue Number: Fixes #3460.
* file name in title bar is elipsized, so it does not push away the property editor.
* Fix model show up as modified on load.
=> File name width

gaphor/ui/__init__.py, gaphor/ui/macosshim.py, gaphor/ui/styling-macos.css, gaphor/ui/styling-windows.css, gaphor/ui/styling.py
Corners do not look nice:
Remove shadow and rounded corners completely, since macOS will deal with this.
Corners look nice:
=> Update platform styling for macOS

.github/workflows/codeql-analysis.yml, .github/workflows/gvsbuild-updater.yml
One more fix for the Gvsbuild automation. I think we are quickly getting in to https://xkcd.com/1205/. 😄 
=> Fix root env variable not defined for Gvsbuild automation

gaphor/core/modeling/event.py, gaphor/event.py, gaphor/ui/filemanager.py, gaphor/ui/modelchanged.py, gaphor/ui/tests/fixtures.py, gaphor/ui/tests/test_filemanager.py, gaphor/ui/tests/test_mainwindow.py, gaphor/ui/tests/test_modelchanged.py
Issue Number: Fixes #3330
* Moved all code that deals with file checks to one service.
* Check the file hash digest before announcing the file actually changed.
=> Improve file changed notification

gaphor/UML/classes/associationpropertypages.py
Initializing the property editor for Association causes updates to the model.
Issue Number: Fixes #3469
Ensure that creation of property page does not cause updates.
=> Fix recursive updates for association property editor

docs/macos.md
I had some issues installing PyGObject. It was not able to find `ffi.h` 
Updated macos installation instructions.
=> Update macOS docs for installing libffi

CHANGELOG.md, pyproject.toml
=> Bump version and update changelog

README.md
=> Add OpenSSF status badge

.github/actions/macos_dmg/action.yml, .github/workflows/full-build.yml, gaphor/ui/help/about.ui
- Update contributors since last release
- Upgrade macOS runners to fix build errors I was getting with macos-12
=> Update about dialog with new contributors

gaphor/ui/modelchanged.py
Issue Number: Fixes #3536
The file digest is now updated when the model is saved.
Now the popup no longer appears if the model was saved.
=> macOS: Fix file changed notification

gaphor/ui/tests/test_modelbrowser.py
I fixed issue #3527 as suggested in https://github.com/gaphor/gaphor/issues/3527#issuecomment-2411071552
Issue Number: #3527
=> fix issue #3527

docs/event_system.md, docs/framework.md, docs/models/core.rst, docs/models/core_services.rst, docs/scripting.md, docs/service_oriented.md, gaphor/UML/classes/tests/test_copypaste.py, gaphor/UML/profiles/tests/test_copypaste.py, gaphor/core/eventmanager.py, gaphor/core/modeling/coremodel.py, gaphor/core/modeling/element.py, gaphor/core/modeling/elementfactory.py, gaphor/core/modeling/presentation.py, gaphor/diagram/connectors.py, gaphor/diagram/copypaste.py, gaphor/storage/tests/test_storage_upgrades.py, gaphor/ui/modelmerge/organize.py, models/Core.gaphor
This PR builds on #3541.
`Presentation` inherited from `Element`, which provided it with features it would never need, such as a name, ownership.
`Presentation` is now derived directly from `Base`. This makes it clear that this kind of element is different from the modeling language base type `Element`.
* Documentation improvements
=> Presentation class inherits directly from Base

.github/workflows/codeql-analysis.yml, .github/workflows/dependency-review.yml, .github/workflows/full-build.yml, .github/workflows/gvsbuild-updater.yml, .github/workflows/hypothesis-test.yml, .github/workflows/labeler.yml, .github/workflows/pre-commit-updater.yml, .github/workflows/release-drafter.yml, .github/workflows/scorecard.yml, .pre-commit-config.yaml, gaphor/UML/classes/containmentconnect.py, gaphor/action.py, gaphor/codegen/coder.py, gaphor/settings.py, gaphor/ui/mainwindow.py, gaphor/ui/modelmerge/organize.py
This PR:
1. Updates the pre-commit hooks manually, since ruff was failing during the update
2. Finishes blocking egress for all workflows
3. Updates to using Python 3.13 on the remaining workflows
=> Update pre-commit hooks

.github/workflows/full-build.yml
=> Fix macOS build and add some emojis

docs/coffee_machine.md, docs/first_model.md, docs/getting_started.md, docs/merge_conflicts.md, docs/plugins.md, docs/stereotypes.md, docs/style_sheets.md
Alt texts are simple and provide no real information.
Images have a proper alt-text. This improves accessibility of our docs.
=> Update alt texts on images in our documentation

tests/conftest.py, tests/test_model_consistency.py
Dependency relations changed from `[0..1]` to `[0..*]`. That's what broke the hypothesis tests.
Issue Number: Fixes #3563
It also turned out profiles no longer worked, so I fixed that as well.
=> Fix hypothesis tests

tests/test_model_consistency.py
Use only UML diagrams in the model consistency test.
=> Only use UML diagrams in model consistency test

.github/actions/macos_dmg/action.yml, .github/workflows/full-build.yml, _packaging/dmgbuild-settings.py, poetry.lock, pyproject.toml
Let's see if this tool performs better.
Issue Number: #3605
=> Build macOS DMG with dmgbuild

.github/workflows/full-build.yml, gaphor/asyncio.py, gaphor/ui/errordialog.py, gaphor/ui/filemanager.py, gaphor/ui/statuswindow.py, gaphor/ui/styling.css
Improved UI when dialogs are shown with grey background (sheets):
=> Adwaita dialogs

docs/modeling_language.md, gaphor/SysML/diagramtype.py, gaphor/UML/actions/drop.py, gaphor/UML/copypaste.py, gaphor/UML/diagramitems.py, gaphor/UML/drop.py, gaphor/UML/general/__init__.py, gaphor/UML/general/diagramitem.py, gaphor/UML/interactions/drop.py, gaphor/UML/uml.py, gaphor/core/modeling/base.py, gaphor/core/modeling/presentation.py, gaphor/diagram/copypaste.py, gaphor/diagram/drop.py, gaphor/diagram/general/__init__.py, gaphor/diagram/general/diagramitems.py, gaphor/diagram/general/tests/test_modelinglanguage.py, gaphor/diagram/tests/test_copypaste_full.py, gaphor/ui/diagrampage.py, gaphor/ui/modelmerge/organize.py, gaphor/ui/tests/test_diagrampage.py, models/UML.gaphor, tests/test_architecture.py
Follow up of #3571.
Reduce the blast radius of the UML model in the code base.
This is important so, we can support other modeling languages alongside UML.
Issue Number: #3540, #3577
=> Reduce dependency on UML model in the code base

gaphor/SysML/tests/test_diagramtype.py, gaphor/UML/actions/partition.py, gaphor/UML/classes/dependencypropertypages.py, gaphor/UML/classes/tests/test_copypaste.py, gaphor/UML/uml.py, gaphor/UML/umlfmt.py, gaphor/UML/umloverrides.py, gaphor/codegen/coder.py, models/UML.gaphor, models/UML.override
Builds on #3606
Fix UML Model a bit more: NamedElement.
=> Move name and qualifiedName properties back to NamedElement

gaphor/UML/classes/classconnect.py, gaphor/UML/classes/tests/test_dependencyconnect.py, gaphor/UML/group.py, gaphor/storage/storage.py, gaphor/storage/tests/test_recovery_recorder.py, gaphor/storage/tests/test_storage_upgrades.py, gaphor/ui/styling.css
Issue Number: Fixes #3467
Dependencies are owned by a package.
=> Dependency should reside in a package

docs/gaphor-services.md, docs/scripting.md
=> Remove "schema not installed" warning from docs

gaphor/ui/filemanager.py, tests/test_auto_layouting.py, tests/test_comment_line_placement.py, tests/test_model_consistency.py, tests/test_undo.py
Issue Number: #3577
All new models are created from templates.
Now file manager no longer has a dependency on the UML model.
=> Remove default model creation from file manager

docs/plugins.md
Added section for community developed plugins and link to repo for gaphor_tools plugin
- [x ] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [x ] I have read, and I understand the GNOME [Code of Conduct](https://conduct.gnome.org/)
- [ x] Documentation content changes
- [x ] No
=> Update plugins.md - link to gaphor_tools plugin

docs/first_model.md
- [ x] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [x ] I have read, and I understand the GNOME [Code of Conduct](https://conduct.gnome.org/)
- [x ] Documentation content changes
- [ x] No
=> Update first_model.md - added link to sysml_distilled repo

gaphor/ui/diagrampage.py, gaphor/ui/diagrams.py, gaphor/ui/selftest.py, gaphor/ui/tests/test_modelbrowser.py
Fallout from model separation efforts.
The Diagram.name attribbute is shadows by NamedElement.name. So let's check the property name instead.
=> Fix diagram name updates

gaphor/UML/treemodel.py
Issue Number: Fixes #3651
Since `name` moved to `NamedElement` again, we should adjust the check accordingly.
Fallout from model changes.
=> Fix critial warning in tree model

.github/workflows/full-build.yml, REUSE.toml, gaphor/C4Model/propertypages.py, gaphor/UML/classes/dependencypropertypages.py, gaphor/UML/classes/propertypages.ui, gaphor/UML/general/comment.py, gaphor/UML/general/commentpropertypage.py, gaphor/UML/profiles/propertypages.ui, gaphor/diagram.css, gaphor/diagram/propertypages.py, gaphor/diagram/propertypages.ui
Stereotype is not shown on Comment items.
Fixes #3655
Stereotypes are shown on comments:
* Make a separate property editor for the type label
* Align dependency-editor "Source" and "Target" labels
=> Show stereotypes on comments

docs/locale/fr/LC_MESSAGES/docs.po, docs/locale/hr/LC_MESSAGES/docs.po
=> Fix weblate

gaphor/ui/diagrams.py
Issue Number: fixes #3653
We should tell the system the event is handled.
Hotkey does non longer show up in instant editor when a character is typed.
=> Fix toolbox hotkey showing up in editor

.github/constraints.txt
Updates Poetry and other dependencies.
=> Bump workflow constraint versions

gaphor/UML/group.py, gaphor/UML/tests/test_group.py, gaphor/diagram/propertypages.ui
Issue Number: fixes #3683
Image works again, and does not show in the tree view.
=> Do not expect an owner for UML.Image

gaphor/SysML/__init__.py, gaphor/SysML/blocks/connectors.py, gaphor/SysML/deletable.py, gaphor/SysML/diagramframe.py, gaphor/SysML/diagramitems.py, gaphor/SysML/diagramtype.py, gaphor/SysML/painter.py, gaphor/SysML/tests/test_diagramitems.py, gaphor/UML/actions/activity.py, gaphor/diagram.css
Issue Number:  #2213 (partially)
Replaces PR #2867.
New SysML diagrams have a frame.
Old style diagrams stay as is.
@marek-piirikivi I rebased and updated your PR on top of the latest code. I think this is how you expect it to work. If you have time, can you please check 😄 ?
@danyeaw What do you think?
=> Use frames in SysML diagrams

gaphor/UML/actions/activity.py, gaphor/UML/actions/activitypropertypage.py, gaphor/UML/actions/objectnode.py, gaphor/UML/actions/tests/test_activitypropertypage.py, gaphor/UML/classes/tests/test_associationconnect.py, gaphor/diagram/propertypages.py, gaphor/diagram/styleeditor.py, gaphor/diagram/styleeditor.ui, gaphor/storage/tests/test_recovery_eventlog.py, gaphor/ui/mainwindow.py, gaphor/ui/mainwindow.ui, tests/test_properties.py
* Remove redundant Type editor for Parameter nodes
* Add Show Type option for ObjectNode
* Replace Gtk.ColorChooser by Gtk.ColorDialog
* some tests
=> Boyscouting: a couple of small fixes

.github/actions/install/action.yml, .github/constraints.txt, .pre-commit-config.yaml, gaphor/SysML/tests/test_drop.py, gaphor/UML/actions/objectnode.py, gaphor/UML/propertypages.py, gaphor/UML/recipes.py, gaphor/UML/tests/test_uml2.py, gaphor/codegen/coder.py, gaphor/core/modeling/base.py, gaphor/core/modeling/elementdispatcher.py, gaphor/core/modeling/properties.py, gaphor/core/styling/selectors.py, gaphor/diagram/general/metadata.py, gaphor/diagram/propertypages.py, gaphor/event.py, gaphor/plugins/diagramexport/export.py, gaphor/services/undomanager.py, gaphor/tests/test_application.py, gaphor/tests/test_transaction.py, tests/test_model_consistency.py, tests/test_properties.py
Some more cleanups this weekend. :smile: This PR bumps Ruff, which created some formatting changes and also flagged opportunties to use dataclasses. Also updated Poetry to version 2.0.1.
=> Poetry and Ruff Update

CHANGELOG.md, gaphor/ui/help/about.ui
- Marks changelog as released
- Updates contributors in about dialog - shoutout to @FranciscoTGouveia, @nomisge, @jhenriquelc, @TamilNeram, and @stansz84 who are new contributors :tada:
=> Prepare version 3.0.0 release

gaphor/UML/actions/action.py, gaphor/UML/actions/activity.py, gaphor/UML/actions/drop.py, gaphor/UML/actions/tests/test_drop.py
Issue Number: Fixes #3790
Creating an action on an Activity and drag it on a swimlane works.
=> Fix DnD of action from Activity to Partition (swimlane)

gaphor/UML/actions/tests/test_actionseditors.py, gaphor/UML/classes/tests/test_classeseditors.py, gaphor/UML/general/tests/test_generaleditors.py, gaphor/conftest.py, gaphor/diagram/tests/test_instanteditors.py, gaphor/diagram/tools/tests/test_dropzone.py, gaphor/ui/modelmerge/editor.py, gaphor/ui/tests/test_diagrampage.py, gaphor/ui/tests/test_handletool.py, gaphor/ui/tests/test_mainwindow.py, poetry.lock, pyproject.toml, tests/test_comment_line_placement.py, tests/test_placement_tools.py
> Builds on #3797
We did not update to Gaphas 5 yet.
In Gaphas 5, `GtkView.update()` returns a task, that can be awaited. The custom decorators have been removed.
=> Upgrade to Gaphas 5

gaphor/ui/clipboard.py
Build is broken
Fixed build.
It now maintains it's own background task.
=> Fix clipboard

.github/scripts/appdata-release.py, .github/workflows/full-build.yml, RELEASE_CHECKLIST.md, data/org.gaphor.Gaphor.appdata.xml, data/org.gaphor.Gaphor.desktop, data/org.gaphor.Gaphor.xml, data/update-appdata.py, pyproject.toml
Project metadata is in the flathub repo, instead of neatly in our own repo.
Issue Number: fixes #3812 
* Desktop, mime and appdata files are in this repo.
* Update scripts have been updated
* Checks are done to verify if versions are in sync between project, metadata and tag.
=> Add project metadata to this repo

gaphor/event.py, gaphor/transaction.py, gaphor/ui/diagrampage.py, gaphor/ui/diagrampage.ui, gaphor/ui/mainwindow.py
Issue Number: #3832
Disable the alignment menu if < 2 items are selected.
Cleaned up some event and action related code.
=> Enable alignment menu only if enough items are selected

gaphor/ui/help/about.ui, po/build-babel.py
Since they are now mature, enable additional translations.
Tamil, Ukrainian, and Hindi translations aren't available
They are now available
=> Enable Tamil, Ukrainian, and Hindi translations

gaphor/UML/umlfmt.py, gaphor/storage/parser.py, gaphor/storage/storage.py, gaphor/storage/tests/test_storage_upgrades.py, gaphor/storage/xmlwriter.py, gaphor/ui/statuswindow.py
Deal with odd cases, e.g. when value of a value is empty.
Issue Number: Fixes #3829
* Added regression tests for ValueSpecification update.
* Added and fixed corner cases (superseeds #3830)
* Type all storage functions. This will reduce the room for error in the future.
* Cleanup: no longer need to deal with "homeless literals"
=> Fix empty values in older (pre-3.0) models

gaphor/diagram/propertypages.py, gaphor/diagram/styleeditor.py, gaphor/ui/elementeditor.ui, gaphor/ui/mainwindow.ui, gaphor/ui/modelmerge/editor.py, gaphor/ui/styling.css
Improve the element editor.
Issue Number: #3831
View switchers are in the element editor.
The style editor can also be added to the element editor/sidebar now.
Also tested with merge conflict.
=> Use view switcher in element editor

gaphor/storage/storage.py, gaphor/storage/tests/test_storage_upgrades.py
Fixes an issue where lower value is an empty string.
All pre-3.0 models should work fine now.
=> Add fallback in case of empty lower or upper values

gaphor/plugins/diagramexport/export.py
Diagram name is used for exporting file
Issue Number: fixes #3876
Entered file name is used.
=> Fix file name for exported files

gaphor/UML/uml.py, models/UML.gaphor
Linked Behavior (e.g. Activity) is removed when CallBehaviorAction is removed.
Issue Number: Fixes #3862
Linked behavior is not removed.
=> Relation between CallBehaviorAction and Behavior should not be composite

.github/workflows/full-build.yml
Syntax error which caused the lint step to fail.
=> Fix syntax error with version check

docs/style_sheets.md, gaphor/ui/elementeditor.py, gaphor/ui/tests/test_elementeditor.py
You can't know `.item` class is assigned to all diagram items.
=> Show CSS classes in style editor

gaphor/SysML/diagramframe.py
=> Revert unintended updat eon diagram frame

gaphor/UML/actions/actionstoolbox.py, gaphor/UML/recipes.py, gaphor/diagram/group.py
Issue Number: fixes #3926
Deal with non-UML based types (e.i. they have no `owner` attribute).
=> Make search owner by type a bit more lenient

.github/workflows/full-build.yml, README.md
It breaks the build, and code climate doesn't show it anymore.
Code Climate upload doesn't work.
No more upload. We'll have to find an alternative.
=> Remove Code Climate coverage upload

.github/workflows/full-build.yml, gaphor/C4Model/c4model.py, gaphor/RAAML/raaml.py, gaphor/SysML/sysml.py, gaphor/UML/actions/activitypropertypage.py, gaphor/UML/actions/tests/test_actionspropertypages.py, gaphor/UML/classes/association.py, gaphor/UML/classes/associationpropertypages.py, gaphor/UML/recipes.py, gaphor/UML/states/tests/test_pseudostates.py, gaphor/UML/uml.py, gaphor/UML/umllex.py, gaphor/codegen/coder.py, gaphor/codegen/tests/test_coder.py, gaphor/core/modeling/coremodel.py, gaphor/core/modeling/properties.py, gaphor/core/modeling/tests/test_properties.py, gaphor/storage/load.py, gaphor/storage/tests/test_storage.py, gaphor/storage/tests/test_storage_upgrades.py, models/Core.gaphor, models/SysML.gaphor, models/UML.gaphor, poetry.lock, pyproject.toml
Our implementation of enumerations in the data model predates the `enum` module.
Use enumerations like a boss. Based on the enum module.
I think this will make implementing #3975 somewhat easier.
Dropped Python 3.11 support.
Bump Gaphor version to 3.2.0.
=> Use real enumerations in the data models

.readthedocs.yaml
Translations tend to fail often.
Translations should build.
=> No longer generate PDF docs

.github/actions/install/action.yml, .github/workflows/full-build.yml, _packaging/gaphor.spec, gaphor/application.py, gaphor/ui/selftest.py, scripts/build_babel.py, scripts/check_babel.py
macOS builds are constantly failing.
Stable macOS builds, hopefully.
* Updated macOS intel image to `macos-15-intel`. Not sure what that does on minimal OS version for our build
* Build on macOS with Homebrew's Python version
* Simplified self-test
* Install Poetry with pipx
* Fix locale file generation
* Allow support for integrated GPU (See https://gitlab.gnome.org/GNOME/gtk/-/issues/7676)
=> Fix macOS builds

.github/workflows/full-build.yml
=> Use new official flatpak container image

.pre-commit-config.yaml, gaphor/UML/umloverrides.py
=> Update mypy to 1.18.2
