gaphor/gaphor

- gaphor/ui/mainwindow.py
If you don't have any elements selected in the Namespace, and you hit F2, the MainWindow was throwing an AttributeError.
> Fix AttributeError when hitting F2 with no elements selected

- gaphor/plugins/diagramlayout/__init__.py
- gaphor/plugins/xmiexport/__init__.py
- gaphor/plugins/xmiexport/exportmodel.py
- gaphor/services/diagramexportmanager.py
- gaphor/ui/event.py
- gaphor/ui/filedialog.py
- gaphor/ui/interfaces.py
- gaphor/ui/mainwindow.py
- gaphor/ui/tests/test_diagramtools.py
- gaphor/ui/tests/test_handletool.py
- gaphor/ui/tests/test_mainwindow.py
- gaphor/ui/tests/test_namespace.py
The diagram exporter and diagram layout tools were using the get_current_diagram method from the MainWindow class, which was refactored into a new Diagrams class in previously merged changes. This PR cleans up some of that refactoring by fixing the diagram exporter and layout tools.
This PR also updates the tests to be compatible with the new Diagrams class and closes #74.
Issue Number: #74
> Fix Get Current Diagram and View Needs to Call Diagrams Class

- gaphor/ui/diagramtools.py
It should still submit text when clicked outside the editor window.
Text can only be edited via the Editor window
Issue Number: #94 
Double click on a diagram item will open a editor box.
> Fix in-diagram editor to something workable

- gaphor/application.py
For one, this greys out the Quit option in the MacOS menu
On MacOS, the Quit option in the apple menu was visible, clickable, but didn't do a thing
The menu items that are not implemented are greyed out.
> Start Gaphor as a Gtk.Application

- gaphor/UML/collection.py
- gaphor/UML/element.py
- gaphor/UML/elementfactory.py
- gaphor/UML/properties.py
- gaphor/diagram/actions/flow.py
- gaphor/diagram/actions/tests/test_flow.py
- gaphor/diagram/classes/tests/test_association.py
- gaphor/diagram/diagramitem.py
- gaphor/diagram/tests/test_diagramitem.py
- gaphor/services/componentregistry.py
- gaphor/services/tests/test_elementdispatcher.py
- gaphor/services/tests/test_undomanager.py
- gaphor/ui/diagramtoolbox.py
- gaphor/ui/tests/test_namespace.py
Reduce external dependencies for the UML module.
The `gaphor.UML` module is dependent on global state, namely the adapter registry of a global "site-manager" inside the zope.component module.
This is bad. First of all since global state in general is a bad idea, but it also means that our own `component_registry` has to do some monkey-patching to make sure the application works as expected.
The eventing mechanism for derived properties is baked in to the properties classes. The event handling itself is externalized, and delegated to the ElementFactory, who knows about components and stuff.
Unless your plugin is using `component.handle`, that is.
For now, elements should keep their reference to the element factory. It's needed …
> Self contained uml package

- gaphor/ui/diagramtools.py
Currently when Gaphor is launched with Wayland it crashes. The issue is when using GDK CursorType SIZING, so I have updated it to use the CROSSHAIR one. I am currently not sure how to make use of this Group Placement tool, so I'm not positive if this is a suitable cursor to use in this situation.
TypeError: constructor returned NULL
Issue Number: #147 
No TypeError
> Fix Wayland Cursor TypeError: constructor returned NULL

- gaphor/ui/toolbox.py
This is done explicitly. It does the trick, although it may not be the most clean way.
Fixes 158.
Selection tool is no longer draggable.
> Do not set up DND for toolbox-pointer

- gaphor/UML/elementfactory.py
- gaphor/UML/modelfactory.py
- gaphor/UML/tests/test_modelfactory.py
- gaphor/UML/tests/test_uml2.py
- gaphor/diagram/actions/actionsgrouping.py
- gaphor/diagram/actions/flowconnect.py
- gaphor/diagram/classes/classconnect.py
- gaphor/diagram/classes/classespropertypages.py
- gaphor/diagram/components/connectorconnect.py
- gaphor/diagram/connectors.py
- gaphor/diagram/grouping.py
- gaphor/diagram/interactions/interactionspropertypages.py
- gaphor/diagram/interactions/messageconnect.py
- gaphor/diagram/interactions/tests/test_messageconnect.py
- gaphor/diagram/profiles/extensionconnect.py
- gaphor/diagram/profiles/metaclasspropertypage.py
- gaphor/diagram/profiles/stereotypepage.py
- gaphor/diagram/profiles/tests/test_classifier_stereotypes.py
- gaphor/diagram/profiles/tests/test_metaclasspropertypage.py
- gaphor/diagram/profiles/tests/test_stereotypepage.py
- gaphor/diagram/propertypages.py
- gaphor/diagram/states/vertexconnect.py
- gaphor/services/sanitizerservice.py
- gaphor/services/tests/test_sanitizerservice.py
- gaphor/services/undomanager.py
Everything, including model elements are dependent on the _injected_ `ElementFactory`. Basically the application is dependent on a few singleton objects.
UML Elements, however, already have their own reference to the model (element-factory). This model reference should be used for diagram items (which inherit from `UML.Presentation`).
No more injecting of `element_factory`'s in any model related item.
`ElementDispatcher` is still a dependency that needs fixing.
Fixed errors in `UndoManager`: it was trying to set values for derived associations. It should only record and play back the original association state change.
> Element factory to model

- utils/model/build_uml.py
Fixes a TypeError: not all arguments converted during string formatting error when building with Windows. The code should have maintained the `"build"` string like so:
```
def finalize_options(self):
self.set_undefined_options("build", ("force", "force"))
```
When building gaphor for Windows, I was getting the following error:
```
running install
running bdist_egg
running egg_info
creating gaphor.egg-info
writing gaphor.egg-info/PKG-INFO
writing dependency_links to gaphor.egg-info/dependency_links.txt
writing entry points to gaphor.egg-info/entry_points.txt
writing requirements to gaphor.egg-info/requires.txt
writing top-level names to …
```
> Fix TypeError with Distutils when building with Windows

- gaphor/ui/toolbox.py
All toolbox sections were expanded on start.
The toolbox state is persisted. So next time Gaphor is started, the toolbox sections are restored.
> Retain toolbox expanded/collapsed groups

- gaphor/services/copyservice.py
This fixes two errors caused during creating a new element on a diagram where it tries to look up an action on the win action group that doesn't yet exist, and when copying an item caused by the same issue. This fix adds a guard to check if the win action group is None before looking
up the action.
I am not sure if there is a more elegant fix than adding a guard to check for the None type.
Create a block and then click on it:
```
Traceback (most recent call last):
File "/home/dan/Projects/gaphor/gaphor/ui/diagrampage.py", line 308, in _on_view_selection_changed
DiagramSelectionChange(view, view.focused_item, view.selected_items)
File …
```
> Fix AttributeError when win action group is None

- gaphor/diagram/interactions/interactionspropertypages.py
- gaphor/diagram/interactions/message.py
- gaphor/diagram/interactions/messageconnect.py
- gaphor/diagram/interactions/tests/test_message.py
- gaphor/diagram/interactions/tests/test_messageconnect.py
- gaphor/storage/parser.py
- gaphor/storage/storage.py
- gaphor/storage/tests/test_storage_message_item_upgrade.py
- gaphor/storage/tests/test_storage_upgrades.py
- test-diagrams/multiple-messages.gaphor
MessageItem was a weird one. Where each item (or part of it) references a model element (via `Presentation.subject` and the model element references the presentation item (via `Element.subject`), this was no the case for messages.
With the new drawing model it became clear that it's quite hard to draw a decent message with text. The solution is to make the MessageItem a *lot* simpler.
It was possible to have multiple messages connected to a single MessageItem.
As a result, actions that concern the Message, had to be executed on a MessageItem class.
Issue Number: #195
The message has become simpler. Only a single message can be presented by one MessageItem.
A migration is made that creates multiple message items. One for each (additional) message …
> Cleanup message item

- gaphor/diagram/classes/classconnect.py
- gaphor/diagram/classes/classespropertypages.py
- gaphor/diagram/classes/dependency.py
- gaphor/diagram/classes/implementation.py
- gaphor/diagram/classes/interface.py
- gaphor/diagram/classes/interfaceconnect.py
- gaphor/diagram/classes/tests/test_interfaceconnect.py
- gaphor/diagram/components/connector.py
- gaphor/diagram/components/connectorconnect.py
- gaphor/diagram/components/tests/test_connect.py
- gaphor/diagram/components/tests/test_connector.py
- gaphor/diagram/connectors.py
Simplify the way interfaces and (mainly) components interact.
This fixes the regression after the new item drawing model was implemented.
Fixes #193 
TODO:
> Interface folding

- MANIFEST.in
The pyproject.toml file replaces the MANIFEST.in. I just tested this and it already includes the LICENSE, and all the icons, images, and css files without explicitly including them in the `include` section of the pyproject.toml
> Remove package manifest file

- gaphor/ui/diagrampage.py
- gaphor/ui/preferences.py
Tool is not reset. This makes things complex for newcomers when the pointer tool has scrolled out of the toolbox view.
Reset tool after creation.
I think we should release 1.1.1 to fix the issue.
> Reset tool after creation by default

- azure-pipelines.yml
I would assume 18.04 is the most used LTS version by now.
update: that did not work...
> Upgrade linux image to 18.04: latest LTS

- gaphor/diagram/profiles/stereotypepage.py
- gaphor/diagram/propertypages.py
- gaphor/ui/namespace.py
Search was only possible on already expanded nodes in the tree view.
When searching, nodes that have matching children will expand, allowing for better searching.
It would probably need some sort of highlighting, to distinguish those nodes even better.
No elements are filtered out of the view.
searching has been completely disabled for tree/list views used in the Element editor.
> Allow nested searches on namespace view

- gaphor/misc/generic/event.py
- gaphor/ui/diagrampage.py
- gaphor/ui/namespace.py
* No keyboard shortcut for editing an element name in the tree view
* Keyboard shortcur (F2)
* Add a list of diagrams to the popup of an element, now you can open any diagram an element features in. This makes it easier to navigate the model.
> Show in diagram

- gaphor/diagram/text.py
- gaphor/ui/__init__.py
- gaphor/ui/actiongroup.py
When running Gaphor:
```
/home/dan/Projects/gaphor/gaphor/ui/__init__.py:9: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Gdk, Gio, Gtk
/home/dan/Projects/gaphor/gaphor/ui/__init__.py:9: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Gdk, Gio, Gtk
/home/dan/Projects/gaphor/gaphor/diagram/text.py:11: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets …
```
> Fix GTK Warnings - Versions not Specified before Import

- .github/workflows/build.yml
Manually ran pre-commit in CI.
pre-commit is run through the pre-commit action.
> Use pre-commit Action to Run pre-commit

- gaphor/ui/mainwindow.py
Fixes `DeprecationWarning: Gtk.Button.set_focus_on_click is deprecated`
`button.set_focus_on_click(False)`
> Fix GTK Deprecation Warning

- gaphor/misc/gidlethread.py
- gaphor/misc/tests/test_gidlethread.py
- gaphor/storage/storage.py
This PR fixes an AttributeError caused by the clock method in the time module being deprecated, and removed in Python 3.8.
When opening `gaphor/UML/uml2.gaphor` I get the following error:
```
Traceback (most recent call last):
File "/home/dan/Projects/gaphor/gaphor/ui/actiongroup.py", line 147, in _action_activate
method()
File "/home/dan/Projects/gaphor/gaphor/ui/filemanager.py", line 298, in action_open
self.load(filename)
File "/home/dan/Projects/gaphor/gaphor/ui/filemanager.py", line 87, in load
worker.wait()
File "/home/dan/Projects/gaphor/gaphor/misc/gidlethread.py", line 76, in wait
clock = time.clock
AttributeError: module 'time' has no attribute 'clock'
``` …
> Fix AttributeError When Opening Models with Python 3.8

- gaphor/misc/tests/test_gidlethread.py
Fixes issue introduced in #251. macOS is being flaky about passing the best. This fix increases the timeout to try to fix the issue.
> Fix test flakiness by changing timeout to a longer value

- gaphor/UML/properties.py
When closing (flushing) a model (e.g. `gaphor/UML/uml2.gaphor`) a lot of errors show up:
gaphor.UML.properties ERROR Failed to unlink _stub_7fb1e478f990 from <gaphor.UML.uml2.Class object at 0x7fb1e479cdd0>
Traceback (most recent call last):
File "/home/arjan/Development/gaphor/gaphor/UML/properties.py", line 549, in unlink
values = getattr(obj, self._name)
AttributeError: 'Class' object has no attribute '_stub_7fb1e478f990'
No more errors. This behavior is expected.
The code has been written in a way that expresses the intent more clearly.
> Fix attribute errors when unloading a model

- win-installer/msys2-install.sh
This PR fixes the build which is failing in Windows.
The Windows build was still using the venv script, and using virtualenvs in MSYS2 isn't working with Poetry > 1.0.0.
No virtualenv is created and builds pass.
> Avoid creation of a virtualenv in CI with Windows

- gaphor/diagram/propertypages.py
- po/ca.po
- po/es.po
- po/fr.po
- po/gaphor.pot
- po/nl.po
- po/pt_BR.po
- po/ru.po
- po/sv.po
Naming of the options around rectilinear lines is unclear.
Issue Number: #186 
use more clear terminology.
> Rectilinear lines

- gaphor/diagram/general/connectors.py
- gaphor/diagram/general/tests/conftest.py
- gaphor/diagram/general/tests/test_comment.py
- gaphor/diagram/interactions/tests/conftest.py
- gaphor/diagram/tests/conftest.py
- gaphor/diagram/tests/fixtures.py
- gaphor/services/sanitizerservice.py
- gaphor/services/tests/conftest.py
- gaphor/services/tests/test_sanitizerservice.py
See #72 
A background service (sanitizer) ensures elements have their comments attached.
> Comment line fixes

- gaphor/UML/collection.py
- gaphor/UML/properties.py
- gaphor/UML/tests/test_properties.py
- gaphor/misc/errorhandler.py
- gaphor/misc/gidlethread.py
- gaphor/ui/filemanager.py
Issue Number: #290 
An error is presented when a loading error is experienced.
Also, removing a non-existant element no longer logs an error. It's desired state,  so we're good.
> Fix loading file with errors

- gaphor/diagram/profiles/tests/conftest.py
- gaphor/diagram/profiles/tests/test_extensionconnect.py
- gaphor/diagram/profiles/tests/test_metaclasspropertypage.py
- gaphor/diagram/profiles/tests/test_stereotypepage.py
- gaphor/misc/tests/test_gidlethread.py
This PR continues conversion towards closure of #129.
All profile tests are using unittest
Issue Number: #129 
Some profile tests are using PyTest
> Convert Some Profile Tests to Pytest

- README.md
- docs/windows.md
- win-installer/msys2-install.sh
MSYS2 made Python 3 the default, so package names no longer need to specify python3.
> Fix MSYS2 Package Names

- gaphor/diagram/diagramtoolbox_actions_uml.py
- gaphor/diagram/profiles/__init__.py
- gaphor/diagram/profiles/packageimport.py
- gaphor/diagram/profiles/packageimportconnect.py
- gaphor/diagram/profiles/tests/test_packageimportconnect.py
- gaphor/ui/icons/gaphor-import-symbolic.svg
This PR adds Package Import support to the toolbar and constrains connections between packages only. A following PR will use this to import other Python data models.
> Add Package Import to Toolbar

- gaphor/UML/components/component.py
- gaphor/UML/components/node.py
- gaphor/UML/interactions/tests/test_executionspecification.py
- gaphor/diagram/diagramtools.py
- gaphor/diagram/shapes.py
For Node item, text is always in the center, which is not handy when adding nested items.
Issue Number: #287
Put text at the top if there is a nested item.
> Change text alignment for node and component

- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/profiles/stereotypepropertypages.py
- gaphor/UML/profiles/tests/test_stereotypepage.py
- gaphor/diagram/propertypages.glade
> Stereotypes for association ends

- gaphor/UML/components/component.py
- gaphor/UML/components/node.py
- gaphor/UML/components/tests/test_grouping.py
- gaphor/UML/uml.py
- gaphor/core/modeling/diagram.py
- gaphor/diagram/copypaste.py
- gaphor/diagram/tests/test_copypaste_grouping.py
- models/UML.gaphor
Items, part of a super item, such as Components in a Node, are not copied properly.
Issue Number: #286 
* When a nested item is copied, it's pasted in the same parent item
* When child and parent item are copied together, a new parent item is created and the child will be part of that
Note that items are still pasted relative to the item position (position to the parent). Gaphor still needs some work so pasted items are always pasted inside the canvas' view port.
> Copy paste with parent items

- .gitignore
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/tests/test_diagram.py
- gaphor/core/modeling/tests/test_elementfactory.py
- gaphor/diagram/tests/test_presentation.py
It used to be possible for diagram items to end up in the model. This leads to issues when loading models.
Issue Number: #286, #326
Extra checks are done for the type sanity for both `Element Factory` (which contains the model) and `Diagram` (where diagram items are added).
This should ensure the model stays clean.
`ElementFatctory.bind()` has been removed since it was not used (nor tested).
> Add extra model integrity checks

- gaphor/SysML/requirements/requirement.py
- gaphor/diagram/shapes.py
- gaphor/diagram/text.py
Small PR that wraps the requirement name text and centers it.
Work left to do:
> Enable Text Wrapping for Requirement Name

- gaphor/SysML/blocks/block.py
- gaphor/SysML/propertypages.glade
- gaphor/SysML/propertypages.py
- gaphor/SysML/requirements/requirement.py
- gaphor/UML/classes/klass.py
- gaphor/UML/modelfactory.py
- gaphor/UML/tests/test_modelfactory.py
- gaphor/UML/tests/test_umlfmt.py
- gaphor/UML/umlfmt.py
No parts and references compartment in Block diagram
Issue Number: #138 
Parts and references are visible:
NB. It looks like SysML elements are not visible in the tree view at all (!)
> Parts and references

- gaphor/ui/elementeditor.glade
- gaphor/ui/elementeditor.py
- gaphor/ui/layout.css
- gaphor/ui/layout.py
- gaphor/ui/tests/test_elementeditor.py
Issue Number: #339 
* Element editor is shown by default
* Extra text is shown with some usage tips
* The editor section is now a scrolled window
* Remove unused space on right side of window when element editor is collapsed
* Fixed box spacing for boxes created via the layout class
> Show element editor by default

- gaphor/UML/tests/test_umllex.py
- gaphor/UML/umlfmt.py
- gaphor/UML/umllex.py
- gaphor/ui/namespace.py
- gaphor/ui/tests/test_namespace.py
- models/UML.gaphor
Issue Number: #334 
All namespaced information is shown.
> Namespace show all

- examples/all-elements.gaphor
- gaphor/SysML/propertypages.glade
- gaphor/SysML/propertypages.py
- gaphor/UML/actions/actionspropertypages.py
- gaphor/UML/actions/partitionpage.py
- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/components/componentspropertypage.py
- gaphor/UML/profiles/stereotypepropertypages.py
- gaphor/core/modeling/presentation.py
- gaphor/core/styling.py
- gaphor/diagram/propertypages.glade
- gaphor/diagram/style.py
- gaphor/ui/diagrampage.py
- gaphor/ui/elementeditor.glade
- gaphor/ui/elementeditor.py
- gaphor/ui/tests/test_elementeditor.py
Follow-up on #346 
Style sheet can only be edited from a separate editor and placed in a special place to be picked up by Gaphor. Enabling stylesheet requires tinkering in the Console editor.
An editor is available in the Element editor
I'm thinking about moving the other Preferences here too.
> Edit style sheet

- gaphor/SysML/blocks/property.py
- gaphor/diagram/shapes.py
This is part of closing #138 in order to show Reference Properties with dashed borders instead of solid.
All properties are shown as a rectangle with a solid line.
Issue Number: #138 
Reference Properties are shown as a rectangle with a dashed line.
> Show Reference Properties as Dashed

- gaphor/UML/classes/association.py
- gaphor/diagram/shapes.py
- gaphor/diagram/tests/test_shapes.py
- gaphor/diagram/tests/test_text.py
- gaphor/diagram/text.py
This PR improves the speed of text rendering by about a _factor 10_. Now Pango layouts are not created all the time, but they are reused. This saves a huge amount of time.
> Faster text layout

- .flake8
- gaphor/SysML/blocks/block.py
- gaphor/SysML/blocks/connectors.py
- gaphor/SysML/blocks/proxyport.py
- gaphor/SysML/modelinglanguage.py
- gaphor/SysML/requirements/connectors.py
- gaphor/SysML/requirements/requirement.py
- gaphor/SysML/tests/fixtures.py
- gaphor/UML/classes/association.py
- gaphor/UML/classes/tests/test_interfaceconnect.py
- gaphor/UML/components/artifact.py
- gaphor/UML/iconname.py
- gaphor/UML/interactions/tests/test_executionspecification.py
- gaphor/UML/umloverrides.py
- gaphor/codegen/tests/test_profile_coder.py
- gaphor/core/eventmanager.py
- gaphor/core/modeling/elementdispatcher.py
- gaphor/core/modeling/listmixins.py
- gaphor/core/modeling/presentation.py
- gaphor/core/styling/tests/test_css.py
- gaphor/diagram/diagramtoolbox.py
- gaphor/diagram/general/simpleitem.py
- gaphor/diagram/presentation.py
- gaphor/diagram/propertypages.py
- gaphor/diagram/shapes.py
- gaphor/diagram/tests/test_presentation.py
- gaphor/diagram/tests/test_style.py
- gaphor/ui/elementeditor.py
- gaphor/ui/namespace.py
- tests/test_undo.py
This PR removes unused imports and enables the unused import check with flake8.
> Remove Unused Imports

- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/tests/conftest.py
- gaphor/core/modeling/tests/test_style_attributes.py
Issue Number: #284
Define rules based on attributes.
> Support CSS attributes

- docs/style_sheets.md
This PR helps polish some of the style sheet doc formatting, spelling, and language.
> Polish Style Sheet Documentation

- .gitignore
- images/vagrant-arch/Vagrantfile
Since we got a bug report with Arch Linux, I thought it might be worthwhile for us to start collecting some image configs so that we can quickly spin up a VM of a non-Ubuntu distro. This PR adds a Vagrantfile for Arch, to make use of it:
```bash
cd images/vagrant-arch
vagrant up
```
Once it installs and configures everything, run:
`vagrant reload`
> Add Vagrant File for Arch Linux

- gaphor/SysML/blocks/grouping.py
- gaphor/SysML/blocks/property.py
Property item only has its name rendered
Issue Number: #138 
- Render contents of Property item with type and multiplicity, if applicable.
- Grouping for properties that are created as part of an association, can only group with their owner.
> Render property item with type and multiplicity

- win-installer/gaphor.spec
- win-installer/hooks/hook-cssselect2.py
- win-installer/hooks/hook-tinycss2.py
PyInstaller was unable to find the tinycss2/VERSION file.
Adds two PyInstaller hooks to collect the data files. These hooks can be removed once I get them in to a released version of https://github.com/pyinstaller/pyinstaller-hooks-contrib.
Gaphor fails to launch after installed in Windows.
Gaphor launches again :tada:
> Fix Windows Packaging Fails for Missing Files

- gaphor/diagram/shapes.py
- gaphor/diagram/text.py
- gaphor/ui/namespace.py
Text in tree-view is misbehaving if you enter something between angular brackets, e.g. `Class<Type>`
Issue Number: #376 
You can enter those characters. Style (italic/bold) is set on cell level.
Also fix rendering in diagram when you remove the name (e.g. for Classes)
> Fix tree cell rendering

- gaphor/UML/actions/partition.py
Issue Number: #374
Name and stereotype do update (may require #377 to work properly, since empty text strings do no cause an update).
> Trigger updates on name and stereotype change

- gaphor/services/copyservice.py
Copy /paste behavior is not intuitive when. Also it conflicts with copy/paste in the editor pane.
E.g.
* Create a class item on the diagram
* Copy it
* go to the name field in the editor. Select all (ctrl-A), cut (ctrl-X) and paste (ctrl-V).
* An item is pasted in the diagram. No change in text in the editor pane.
Issue Number: #274
Gaphor interacts with the system clipboard. Clearing it's diagram item copy buffer when something else is copied.
For now and empty string is put on the system clipboard. This should change to an image of the copied items at some point.
> Clear clipboard when diagram items are copied

- gaphor/SysML/sysml.py
- gaphor/UML/uml.py
- gaphor/UML/umloverrides.py
- gaphor/codegen/profile_coder.py
- gaphor/codegen/tests/test_uml_coder.py
- gaphor/codegen/writer.py
- gaphor/core/modeling/coremodel.py
- gaphor/core/modeling/properties.py
- gaphor/core/modeling/tests/test_properties.py
- gaphor/services/tests/test_undomanager.py
- models/Core.override
- models/UML.override
There is some complexity in the data model that I like to get rid of.
Slightly cleaner code.
> Implement some simplifications in the data model

- gaphor/SysML/toolbox.py
- gaphor/UML/toolbox.py
Using the UML Composite and Share Association tools was only creating a normal association. To resolve this, I copied the SysML implementation, and refactored some of the functions in to the UML toolbox module to prevent duplication.
UML composite and shared association tools create a normal association.
Issue Number: closes #396 
This issue is resolved, the composite and share associations are created properly.
> Fix UML composite and shared association

- .github/workflows/build.yml
- .gitignore
- win-installer/build-installer.sh
Add Windows build signing using a certificate. I used the Microsoft SignTool directly based on the [DevOps for Windows Desktop Apps Using GitHub Actions](https://github.com/microsoft/github-actions-for-desktop-apps) guide. The [code-sign-action GitHub Action](https://github.com/dlemstra/code-sign-action) doesn't allow for passwords on the certificate. There was a few forks of it, but I kept on getting errors.  
Issue Number: #395
> Sign using certificate during CI build

- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/event.py
- gaphor/core/modeling/presentation.py
- gaphor/services/undomanager.py
- tests/test_undo.py
diagram items end up in the ElementFactory, because they emited
ElementCreated and ElementDeleted events.
Undo does no longer break the model. Instead `DiagramItemCreated` events are no longer inherited from `ElementCreated` events. This ensures both code paths do not intervene. 
I added `DiagramItemDeleted` events, to match with the `DiagramItemCreated` events.
> Fix #408 where undo on diagram items breaks the model

- gaphor/plugins/console/tests/test_console.py
- pyproject.toml
Console tests are not run.
I thought I fixed it.
> Run console tests as well

- gaphor/UML/actions/actionseditors.py
- gaphor/UML/classes/classeseditors.py
- gaphor/diagram/general/generaleditors.py
- gaphor/diagram/inlineeditors.py
I found it problematic that I had to explicitly "enter" a name in the popover editor. Even more so since the text in the sidebar editor for fields like "name" is instantly applied.
Text edited in a popover editor is instantly applied. One can hit "ESC" to revert the text to before the change.
> Live editing for inline editors (popovers)

- gaphor/UML/classes/association.py
- gaphor/UML/classes/classconnect.py
- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/tests/test_association.py
- gaphor/UML/classes/tests/test_associationconnect.py
- gaphor/UML/classes/tests/test_classconnect.py
- tests/test_multiple_associations.py
Create a class, connect both ends of an association to it. Copy + paste the association and remove the original.
See `tests/test_multiple_associations.py` for a failing scenario.
I hope it will work as expected: association ends remain in tact as well as the navigability.
This is also applicable for Connectors!
Scenario's I can think of:
* Class and association are pasted in a new diagram
* Class and association are pasted in a new diagram and original association is deleted
* Class and association are pasted in a new diagram and new association is deleted
* Association is pasted in a new diagram and reconnected to the class (same subject as original)
* Association is pasted and directly deleted
* Class and association are pasted in a new …
> Fix issue where copy/paste + delete of original association causes association ends to be removed

- win-installer/gaphor.spec
- win-installer/hooks/hook-gi.repository.HarfBuzz.py
- win-installer/hooks/hook-tinycss2.py
- win-installer/hooks/pre_safe_import_module/hook-gi.repository.HarfBuzz.py
This PR fixes three issues with PyInstaller:
1. GTK started linking to HarfBuzz with Gtk and Pango. I added a hook to work around this until a new version of PyInstaller is released, the original issue is at https://github.com/pyinstaller/pyinstaller/issues/5129
2. Although the tinycss2 hook is now integrated with the pyinstaller-hooks-contrib package, we aren't yet using PyInstaller 4.0 because of a separate issue. I added back in this hook for us. Tinycss2 is also working on a new release which will get rid of the need for a hook at all.
3. Windows MSYS2 uses an older version of setuptools which has an issue around use of py2.warn.
Windows packages won't launch
They …
> Fix PyInstaller Packaging Issues

- gaphor/application.py
- gaphor/event.py
- gaphor/ui/__init__.py
- gaphor/ui/appfilemanager.py
- gaphor/ui/filemanager.py
- gaphor/ui/macosshim.py
- gaphor/ui/tests/test_lifecycle.py
- pyproject.toml
There was a lot of hopping around the code when dealing with file loading and session creation. This was only possible through the `GtkApplication`. This is inconvenient and not handy, since `GtkApplication` is not out core application: `gaphor.application.Application` is.
This PR cleans up the code. Makes sure all file loading takes place through the `app_file_manager` and ensures session lifecycle can be completely handled in our code.
On application level there's also an event manager now, so session creation and application shutdown events can be propagated to the GtkApplication as well. Handlers in GtkApplication ensure that the main window is shown when a new session is created and make sure the Gtk main loop is ended …
> Cleanup session lifecycle

- .github/workflows/build.yml
The default timeout of a build stage 360 minutes, and I caught one of builds trying to generate a macOS package for 4 hours. This PR limits the lint stage to 10 minutes, and the other stages to 30 minutes.
> Shorten timeout during build stages

- gaphor/UML/interactions/executionspecification.py
- gaphor/UML/interactions/interactionsconnect.py
- gaphor/UML/interactions/interactionsgrouping.py
- gaphor/UML/interactions/tests/test_message.py
- gaphor/UML/interactions/tests/test_messageconnect.py
- gaphor/UML/tests/test_interactions.py
- gaphor/UML/toolbox.py
- gaphor/diagram/diagramtools.py
- gaphor/ui/icons/Makefile
- gaphor/ui/icons/hicolor/scalable/actions/gaphor-behavior-execution-specification-symbolic.svg
- gaphor/ui/icons/stensil.svg
Lifelines and Messages are not _owned_, hence they end up in the root of the tree view
Issue Number: #386 
Lifelines, Messages, and Execution Specifications are shown in an Interaction. If no Interaction exists in the package the diagram resides in, a new one will be created.
When a lifeline/message/execspec is dragged out of an interaction, it remains part of that interaction hierarchically. This avoid dangling elements. It is placed in a new interaction if it's dragged in to one.
No migration has been written for older models.
> Ownership for interactions

- gaphor/ui/__init__.py
Python 3.9 is right around the corner, with release candidates out now. One of the changes is that importlib.resources now has a `files` method that returns a path and you can feed it directories. Some of the methods that did exist like `importlib.resources.path` were only supposed to be used for resources, which don't include directories. The new method is nice, because it doesn't force using a context manager to get a path to a file or directory.
This PR fixes a IsADirectoryError with Python 3.9 since it no longer allows calling directories with `importlib.resources.path`.
> Fix is directory error with importlib resources in Python 3.9

- gaphor/UML/sanitizerservice.py
- gaphor/UML/tests/test_sanitizerservice.py
- Bugfix
When a diagram is moved, "from" lines remain, although they may be invalid.
Issue Number: #373
Diagram is updated when moved. Relative references are updated, as are "from" messages in classes and packages.
> Update diagram when moved

- gaphor/services/copyservice.py
- gaphor/services/tests/test_copyservice.py
When you copy some items in a diagram, you can only paste them in the same model.
Issue Number: #463 
You can copy, and then paste the items in a different diagram. The diagram items are backed by their model elements.
The current implementation (a global variable) is not really nice. But it proves the application can handle this copy/paste behavior. The actual behavior should work via an `gaphor.appservice`. However, there's no way to inject an app service in a session. And I'm not sure if we want to.
> Use a global copy buffer

- .github/workflows/build.yml
- win-installer/msys2-install.sh
This PR uses the rankmirrors util to look for the fastest MSYS2 repo to prevent issues with long timeouts when the main msys2 repo is down.
We also should also avoid mixing msys2 (POSIX) with mingw64 packages like git and make. For example virtualenv doesn't work when using msys2 git, we should instead be linking to git-for-windows instead which is based off of mingw64. I don't think the CI needs git installed using pacman, but I changed to the mingw64 version of make.
> Fix MSYS2 timeout due to mirror down

- gaphor/services/copyservice.py
Copy/paste breaks on Ubuntu 20.10/Wayland.
Copy buffer is only cleared if a view has no focus.
It looks like I get multiple clipboard `OwnerChange` events in Wayland. This broke the logic with semaphores.
Oddly enough it worked fine in VSCode (installed as Snap).
> Fix copy paste

- .github/workflows/build.yml
- gaphor/diagram/diagramtools/__init__.py
- gaphor/diagram/diagramtools/shortcut.py
- gaphor/ui/diagrampage.py
- gaphor/ui/namespace.py
- poetry.lock
In GTK 4 there are no mouse/keyboard events on the widgets directly. Instead we have to define [EventControllers](https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/EventController.html). Event controllers offer more options (e.g. for multi-touch gestures).
I changed the old events to the new EventController style. Just to see how it works. 
I updated https://github.com/gaphor/gaphas/issues/72 with some findings and ideas.
NB. _EventControllers_ were added in GTK+ 3.14. `EventControllerKey` was only added in GTK+ 3.24.
If this PR is accepted, the minimal GTK+ version is **3.24**. It's available in Ubuntu 20.04, not in _latest_ (18.04). Therefore I upgraded the build image.
NB2. This PR also fixes focus handling of the …
> Slowly move towards event controllers

- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/presentation.py
- gaphor/core/modeling/tests/test_presentation.py
- gaphor/diagram/diagramtools/placement.py
- gaphor/storage/storage.py
- gaphor/storage/tests/test_group.py
We needed to await an "update" to get the right `matrix_i2c` values.
The matrix is updated instantly based on the parent's matrix and it's own matrix.
Dropped `Diagram.get_matrix_i2c()`.
> Presentation instantly updates `matrix_i2c`

- gaphor/UML/classes/tests/conftest.py
- gaphor/core/modeling/properties.py
- gaphor/diagram/general/tests/conftest.py
- gaphor/diagram/general/tests/test_comment.py
- gaphor/diagram/tests/fixtures.py
- gaphor/services/tests/conftest.py
- gaphor/services/tests/test_copyservice.py
- gaphor/services/tests/test_undomanager.py
- gaphor/services/undomanager.py
- gaphor/ui/mainwindow.py
- tests/test_issue_gaphas.py
- tests/test_multiple_associations.py
- tests/test_package_removal.py
- tests/test_undo.py
- tests/test_unioncache_in_derived_response.py
Currently it's possible to make changes to the model at any given point. We want proper Undo/redo behaviour, but can not guarantee that every change happens in a transaction.
An exception is raised when a change is made to the model without being properly encapsulated in a transaction.
If the undo manager finds a (reversible) action to be performed outside of a transaction, it will instantly revert the action and it will raise an exception.
It was good to see that I could not trigger the exception from using the GUI.
There were some tests that used the old `TestCase` class, and therefore implicitly activated the undo-manager service. Those tests have been rewritten to pytest tests.
All changed need to happen within a transaction.
> Everything transactional

- gaphor/core/modeling/elementdispatcher.py
- gaphor/core/modeling/presentation.py
- tests/test_undo.py
Element dispatcher is logging warning messages when handlers are disconnected.
On Element dispatcher, handlers can be registered multiple times, but once a handler is registered, subsequent registrations have no effect. When unregistering, however, a warning message is displayed when a handle can not be found.
Issue Number: #585
The warning level message is demoted to debug.
> Fix element dispatcher warnings

- gaphor/UML/tests/test_umlfmt.py
- gaphor/UML/tests/test_umllex.py
- gaphor/UML/umllex.py
Spaces are not allowed in attribute and operation names and types.
Issue Number: #601
Spaces can be used in attributes and operations. Expressions like this can be parsed:
```
+ attr with spaces: some type
operation with spaces(some param : some type) : some return type
```
> Allow spaces in attribute and operation name and type

- gaphor/UML/actions/action.py
- gaphor/UML/actions/activitynodes.py
- gaphor/UML/actions/partition.py
- gaphor/UML/classes/association.py
- gaphor/UML/classes/dependency.py
- gaphor/UML/classes/generalization.py
- gaphor/UML/classes/implementation.py
- gaphor/UML/classes/package.py
- gaphor/UML/interactions/lifeline.py
- gaphor/UML/profiles/extension.py
- gaphor/UML/states/finalstate.py
- gaphor/UML/states/pseudostates.py
- gaphor/UML/usecases/actor.py
- gaphor/UML/usecases/usecase.py
- gaphor/diagram/diagramtools/grayout.py
- gaphor/diagram/general/comment.py
- gaphor/diagram/presentation.py
- gaphor/diagram/shapes.py
It's not really clear when a 
Issue Number: #390 
Item is highlighted when a handle can be connected.
Items that need a highlight color:
This wraps up #390, I guess :).
> Highlight item when a connection can be established

- gaphor/diagram/diagramtools/grayout.py
- gaphor/diagram/diagramtools/placement.py
The line end is connected to an element when placed on a diagram. The line head is not.
Also connect line head after a line is connected.
To reproduce:
1. create 2 classes
2. Draw an Association from the center of class 1 to the center of class 2
3. The association should connect on both sides.
> Connect start of line when placed inside an element

- gaphor/UML/classes/association.py
- gaphor/UML/interactions/message.py
Association is not properly drawn when one end is composite and it consists of at least 2 segments.
Issue Number: #621 
Association is properly drawn. Interaction message how also highlights.
> Fix composite association

- gaphor/core/modeling/diagram.py
- gaphor/diagram/painter.py
- gaphor/diagram/propertypages.glade
Rendering of diagrams is relatively slow. It turns out the `push_group()` and `paint_with_alpha()` methods of Cairo take quite some resources.
```
23215400 function calls (22809223 primitive calls) in 31.074 seconds
Ordered by: internal time
List reduced from 3143 to 50 due to restriction <50>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1   11.381   11.381   31.075   31.075 Gio.py:40(run)
3123    3.144    0.001    3.144    0.001 {method 'paint_with_alpha' of 'cairo.Context' objects}
3123    2.648    0.001    2.648    0.001 {method 'push_group' of 'cairo.Context' objects}
1    1.335    1.335    1.342    1.342 Gtk.py:577(run)
8297    1.120    0.000    1.723 …
```
> Speed up rendering by determining gray-out colors upfront

- gaphor/__init__.py
- gaphor/diagram/__init__.py
- gaphor/diagram/text.py
- gaphor/ui/__init__.py
- gaphor/ui/actiongroup.py
This suppresses all GI warnings related to undefined versions.
GTK and friends are required in a lot of places. Basically the application and it's scripts (such as `gaphorconvert`) can not run without GTK being available.
Set GTK, GDK and PangoCairo version once, on top level.
```
$ grep -r "from gi.repository" *
gaphor/ui/questiondialog.py:from gi.repository import Gtk
gaphor/ui/gidlethread.py:from gi.repository import GLib
gaphor/ui/actiongroup.py:from gi.repository import Gio, GLib, Gtk  # noqa: isort:skip
gaphor/ui/recentfiles.py:from gi.repository import Gio, GLib, Gtk
gaphor/ui/namespaceview.py:from gi.repository import Gdk, Gtk, Pango
gaphor/ui/__init__.py:from …
```
> Define Gtk version once, at the top of the package

- gaphor/SysML/blocks/proxyport.py
- gaphor/UML/actions/activitynodes.py
- gaphor/UML/actions/partition.py
- gaphor/UML/classes/association.py
- gaphor/UML/classes/dependency.py
- gaphor/UML/classes/interface.py
- gaphor/UML/classes/interfacerealization.py
- gaphor/UML/classes/tests/test_interfaceconnect.py
- gaphor/UML/components/tests/test_connect.py
- gaphor/UML/interactions/executionspecification.py
- gaphor/UML/interactions/message.py
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/stylesheet.py
- gaphor/core/styling/declarations.py
- gaphor/diagram/presentation.py
- gaphor/diagram/shapes.py
Presentation elements have a (relatively) complex update model, with a `pre_update()` and a `post_update()` method. 
Remove `post_update()`, and rename `pre_update()` to `update()`.
As an extra, the style of Dependency and Interface Realization item is set via CSS.
> Simplify presentation update method

- gaphor/ui/toolbox.py
This PR left justifies the toolbox header labels.
Toolbox header labels are centered
Issue Number: #498 
Toolbox header labels are left aligned
> Left align the toolbox header labels

- .github/workflows/build.yml
This PR checks if secrets are available before running a step where a secret is needed. This is to stop dependabot builds from failing due to changes made to made in GitHub Actions to make them read-only:
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
Dependabot builds are failing
Hopefully they now pass :)
> Fix build fails when GitHub Actions secrets are not available

- gaphor/UML/classes/classespropertypages.py
It's unclear what "A" and "S" means in the attributes and operations editor.
Issue Number: #799
A tooltip is showing what the letters stand for
> Add tooltips for "A"/"S" in editor

- gaphor/diagram/inlineeditors.py
- gaphor/ui/namespace.py
- gaphor/ui/namespacemodel.py
- gaphor/ui/namespaceview.py
- gaphor/ui/tests/test_namespace.py
- gaphor/ui/tests/test_namespacemodel.py
Drag-n-drop only works for GTK+ 3.
Issue Number: #618 
Clean up DnD code for GTK+ 3 and enable it in GTK 4
DnD works better for GTK+ 3:
* elements are selected after drop
* nodes are expanded
* scrolling kinda works
* Fix expand/collapse keys in tree view for GTK 3.
TreeView in GTK 4 still contain issues, see #756.
> Improve drag and drop for TreeView

- gaphor/UML/classes/classespropertypages.py
An error is raised when a composite association is added to a diagram and connected to two classes.
Issue Number: #814
No exception, association is properly set.
> Property page should only set navigability if both ends are connected

- .github/workflows/build.yml
This PR hopefully reduces errors on branches due to timeouts of the notarizing service. Also builds will be a little faster.
Rationale: we do not distribute versions from branches, so there's no need to sign them. Maybe it's even better not to sign them, cause these branches (or PR's) can be created by anyone.
> Sign only builds on the master branch

- gaphor/diagram/diagramtools/shortcut.py
- gaphor/diagram/tests/conftest.py
- gaphor/ui/diagrampage.py
- gaphor/ui/diagrams.py
- gaphor/ui/elementeditor.glade
- gaphor/ui/elementeditor.ui
- gaphor/ui/event.py
- gaphor/ui/mainwindow.glade
- gaphor/ui/mainwindow.py
- gaphor/ui/mainwindow.ui
- gaphor/ui/namespace.py
- gaphor/ui/tests/conftest.py
- gaphor/ui/tests/test_handletool.py
- gaphor/ui/tests/test_namespacemodel.py
- gaphor/ui/tests/test_toolbox.py
- gaphor/ui/toolbox.py
Action groups in Gaphor are "magically" set on the main window. The comment already says it's hacky.
... and it doesn't port nicely to GTK 4.
Clean up the action code:
* handle toolbox related code in the toolbox component
* When a tool is selected, it can be applied on all diagrams (before, each diagram had its own action group)
* move DiagramPage actions to Diagrams level. This makes the action handling simpler
* make relation between diagrams and toolbox expicit
* remove hacky code
To do:
> Link toolbox and diagrams

- gaphor/services/undomanager.py
- tests/test_undo.py
If you delete a diagram with an item in it
this causes the item to also be deleted.
Undoing this change raises an exception.
Delete and undo of a diagram should just work.
> Fix delete and undo of a diagram

- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/event.py
- gaphor/core/modeling/presentation.py
- gaphor/core/modeling/tests/test_presentation.py
- gaphor/services/undomanager.py
Gaphor makes a distinction between model elements and diagram items. This distinction is no longer valid and may even harm the integrity of a model.
Issue Number: N.A.
Simplify the use of events for creation of model elements and diagram items. They should behave the same.
`DiagramItemCreated` and `DiagramItemDeleted` have been replaced by `ElementCreated` and `ElementDeleted`.
This change allows us to store diagram items (Presentation) in the ElementFactory, alongside the rest of the model.
> Organize element events

- gaphor/C4Model/modelinglanguage.py
- gaphor/C4Model/tests/test_modelinglanguage.py
- gaphor/RAAML/modelinglanguage.py
- gaphor/SysML/modelinglanguage.py
- gaphor/UML/classes/tests/test_associationconnect.py
- gaphor/UML/classes/tests/test_copypaste.py
- gaphor/UML/modelinglanguage.py
- gaphor/UML/profiles/tests/test_copypaste.py
- gaphor/abc.py
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/element.py
- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/presentation.py
- gaphor/core/modeling/tests/test_diagram.py
- gaphor/diagram/copypaste.py
- gaphor/diagram/presentation.py
- gaphor/services/modelinglanguage.py
- gaphor/services/tests/test_undo_presentation.py
- gaphor/storage/storage.py
- gaphor/storage/tests/test_storage.py
- gaphor/storage/verify.py
- gaphor/ui/tests/test_diagrampage.py
- pyproject.toml
- test-models/all-elements-v2.5.gaphor
- test-models/interaction.gaphor
- test-models/simple-items.gaphor
- tests/test_undo.py
Currently diagram items (Presentation) are managed by diagrams, outside the view of ElementFactory.
All elements, model and presentation are managed by the Element Factory.
This simplifies the loading/saving, the undo management and the way we need to think about out models.
E.g. open `test-models/all-elements.gaphor`, save it and open it again. you'll see some lines and items are wrong. See #855.
> Diagram items in element factory

- .github/workflows/build.yml
- .pre-commit-config.yaml
- gaphor/UML/uml.py
- gaphor/UML/umloverrides.py
- gaphor/abc.py
- gaphor/application.py
- gaphor/codegen/uml_coder.py
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/element.py
- gaphor/core/modeling/elementdispatcher.py
- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/properties.py
- gaphor/core/modeling/tests/test_properties.py
- gaphor/core/styling/__init__.py
- gaphor/core/styling/parser.py
- gaphor/diagram/connectors.py
- gaphor/diagram/copypaste.py
- gaphor/diagram/grouping.py
- gaphor/diagram/inlineeditors.py
- gaphor/diagram/painter.py
- gaphor/diagram/shapes.py
- gaphor/storage/parser.py
- gaphor/ui/diagrampage.py
- gaphor/ui/namespace.py
- packaging/windows/msys2-install.sh
This PR enables pyupgrade to modernize some code, and adds a pre-commit hook to keep things current. Most of the changes currently are simplifications to typing for [PEP 604](https://www.python.org/dev/peps/pep-0604/).
Because there was a typing error while running pytest in Windows with these changes, also upgraded Windows to use Python 3.9. PR #873 will update the docs to match.
No pyupgrade.
pyupgrade enabled :robot:
> Enable pyupgrade and use Python 3.9 in Windows

- docs/windows.md
This PR adds docs for the creation of a development environment in Windows using gvsbuild and the official version of Python for Windows instead of MSYS2.
MSYS2 is only supported
gvsbuild and MSYS2 are options.
> Add Docs for Building GTK for Windows with gvsbuild

- gaphor/core/modeling/properties.py
- gaphor/core/modeling/tests/test_properties.py
- gaphor/services/tests/test_undomanager.py
This should avoid errors such as #894.
It is possible to construct a model in such a way that, for a `ClassItem` and `InterfactItem`, where `obj.parent is obj`.
Issue Number: #894
An exception is raised if `obj.parent` is set to `obj`. This rule is universal for associations, so it can be checked for at model level.
This is possibly no a solution to the root cause for #894, but at least it will not create an error in model.
> Add extra rules to avoid cyclic references

- docs/windows.md
- packaging/windows/msys2-install.sh
Reverts back to using the MSYS2 python package since Python 3.9 is now default.
> Python 3.9 is now default in MSYS2

- gaphor/core/modeling/element.py
This PR fixes a TypeError I was getting in 11 of the tests with Python 3.9.7 locally, although I haven't seen the errors on CI.
```
diagram = <gaphor.core.modeling.diagram.Diagram element 565e76b2-0e80-11ec-a48f-18cf5efc6bb9>
def test_unset_parent_updates_matrix_i2c(diagram):
>       parent = diagram.create(Example)
gaphor/core/modeling/tests/test_presentation.py:111: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
gaphor/core/modeling/diagram.py:256: in create
return self.create_as(type, str(uuid.uuid1()), parent, subject)
gaphor/core/modeling/diagram.py:260: in create_as
item = self.model.create_as(type, id, diagram=self) …
```
> Fix TypeError for Protocols cannot be instantiated

- gaphor/services/helpservice/__init__.py
The about dialog was not closing when the close button was pressed.
When the close button is pressed on the about dialog, it is not closing.
Issue Number: issue-994
When pressing the close button, the dialog is getting closed.
> Fixed closing of about dialog

- gaphor/ui/mainwindow.glade
We have some buttons in the header.
The GTK4 (new libawaita) look will make those buttons flat. I wondered what it would look like for Gaphor.
The items in the header are flat. This does indeed make the header less cluttered:
https://blogs.gnome.org/alexm/2021/09/10/cleaning-up-header-bars/
Not sure if we should actually merge this though? Will it look okay and is it intuitive on Windows and macOS?
> Use flat buttons in the header bar

- gaphor/UML/actions/flow.py
- gaphor/UML/actions/tests/test_flow.py
- gaphor/UML/states/tests/test_transition.py
- gaphor/UML/states/transition.py
The guard field for object and state transitions, is pretty much a free text field.
Issue Number: #978
The guard is actuallt displayed between square brackets.
Fixes #978.
> Display guard conditions in square brackets

- docs/modeling_language.md
- gaphor/UML/actions/actionseditors.py
- gaphor/UML/classes/classeseditors.py
- gaphor/diagram/diagramtools/__init__.py
- gaphor/diagram/diagramtools/textedit.py
- gaphor/diagram/general/generaleditors.py
- gaphor/diagram/general/generalpropertypages.py
- gaphor/diagram/inlineeditors.py
- gaphor/diagram/tests/test_inlineeditors.py
When editing, for each character changed a new undo transaction is created. This makes undo/redo behave in an unexpected way.
Only set name once, after editng
> Improve inline editor undo/redo behavior

- packaging/make-script.py
This PR fixes parameter incorrect errors when trying to load PyGObject with a double semicolon in the path. PyGObject doesn't check that the path is valid prior to adding the dll directory to it. We may be able to push a fix upstream to resolve this as well.
WinError with parameter is incorrect error for ""
Issue Number: #1001
No error.
> Fix parameter is incorrect error with ";;" in path

- docs/requirements.txt
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/element.py
- gaphor/core/modeling/properties.py
- gaphor/core/styling/__init__.py
- gaphor/core/styling/properties.py
- gaphor/diagram/connectors.py
- gaphor/ui/__init__.py
- mypy.ini
- packaging/windows/build-win-installer.py
- pyproject.toml
Python has all typing features we need. No need anymore for typing_extensions.
> Up typing compliance to 3.9, and remove typing_extensions

- docs/requirements.txt
- gaphor/application.py
- gaphor/entrypoint.py
- gaphor/tests/test_entrypoint.py
- poetry.lock
- pyproject.toml
`importlib_metadata` was used to apply Python 3.8+ features in Python 3.6/7.
We only support Python 3.9 currently.
Nothing changed, we use the standard library now directly.
By caching entry points we speed up unit tests by roughly 10%.
> Remove importlib_metadata

- NEWS
- packaging/appimage/Makefile
- packaging/appimage/org.gaphor.Gaphor.appdata.xml
- poetry.lock
- pyproject.toml
The flatpak build is failing because it can't resolve the dependencies. In 93fd1f5, I relocked the dependencies, but I should have run it with `--no-update`. Until we can get #1018 merged, we'll have to be careful about bumping the dependencies.
flatpak-builder was not able to successfully build the flatpak, and I was getting errors about setuptools and wheel, and if I manually added them to the manifest I was getting OSErrors about trying to uninstall version 3.42.0 of PyGObject.
These errors are similar to the ones here: https://github.com/flatpak/flatpak-builder-tools/issues/90
Flatpak build is failing for version 2.6.3
Hopefully the build will pass!
> Fix flatpak build by reverting dependencies

- docs/windows.md
GtkSourceView was missing from the Windows build instructions. This PR adds it in.
> Add gtksourceview to Windows docs

- gaphor/ui/namespace.py
Automatically created Activity, StateMachine, Interaction, Region can not be removed.
Issue Number: #1008
The tree view allows removed of those elements via the context menu.
> Allow auto-generated elements to be removed

- gaphor/UML/interactions/executionspecification.py
- gaphor/UML/interactions/interactionsconnect.py
- gaphor/UML/interactions/lifeline.py
Message ends are tied to a specific position on the life line. When the lifeline is grown, the messages ends also move.
Issue Number: #1007
Messages stay on their place, as long as they are on the lifeline. This allows to freely grow and shrink the lifeline and execution specifications. Also it allows for message to be moved up and down the lifeline.
> Allow messages to move freely on Lifeline and ExecutionSpec

- .github/workflows/full-build.yml
- .github/workflows/test.yml
Until the seg fault issues get resolved, this PR uses updates the builds to use Python 3.9.9. 
Gaphor doesn't launch in Windows after installing
Issue Number: #1122 
Gaphor launches successfully
> Fix Windows build by Updating to Python 3.9.9

- gaphor/UML/classes/tests/test_classconnect.py
- gaphor/UML/classes/tests/test_generalizationconnect.py
- gaphor/UML/classes/tests/test_interfacerealizationconnect.py
- gaphor/UML/uml.py
- models/UML.gaphor
When a generalization between two classes is created on two diagrams, two generalizations are created in the model
Issue Number: #1147 
Fix old behavior where an existing generalization is used from the model. This requires both associations (`UML.Generalization.specific` and `UML.Generalization.general`) to be bi-directional associations, so we can discover an existing . The `UML.Generalization.general` association was uni-directional and a model update has been made to make it bi-directional. This may also help traversing the model in code generation.
I also added a similar test for `InterfaceRealization`.
> Reuse generalization

- gaphor/UML/interactions/interactionsconnect.py
- gaphor/UML/interactions/tests/test_ordering.py
This commit fixes an isue that can occur when loading a model. Lifelines are ordered based on their position on the diagram. The re-ordering is triggered when items are connected. However, relations on model level are already connected at that point. The ordering is dependent on the connections in the diagram as well as the connections on model level.
This change makes the code more resilient during loading.
Fixes #1152
This issue can only be fixed in code, so it requires a new release.
> Fix lifeline ordering when not all items are linked in a diagram

- .github/workflows/full-build.yml
- .github/workflows/test.yml
- poetry.lock
- pyproject.toml
This PR resolves CI seg faults in Linux and updates Gaphor's Python version to 3.10.0.
After debugging seg faults using the [Python with debug workflow](https://github.com/danyeaw/setup-python-debug), it seems like the standard library docttest module is the culprit. I am not sure exactly why though. To fix this, I replaced doctest with [xdoctest](https://github.com/Erotemic/xdoctest).
I also submitted a Python bug report: https://bugs.python.org/issue45913
Python 3.9.9 is used
Python 3.10.0 is used
> Update Python to 3.10.0

- gaphor/UML/tests/test_umllex.py
- gaphor/UML/umllex.py
For an attribute or parameters, it's not possible to have an undefined multiplicity: `attr[]`, `myfunc(arg: string[]): result[]`. The brackets `[]` are not parsed.
However, `[]` is a common construct in programming languages to define an unbounded array. We can simply help the user here by interpreting `[]` as `[*]`.
Issue Number: #1185
Attributes and parameters with undefined multiplicity are treated as if it has a `*` multiplicity. `attr[]` will parse and render as `attr[*]`.
> Empty square bracket notation

- gaphor/SysML/blocks/block.py
- gaphor/SysML/propertypages.glade
- gaphor/SysML/propertypages.py
- gaphor/SysML/propertypages.ui
- gaphor/SysML/tests/test_propertypages.py
- gaphor/UML/classes/tests/test_datatype_connect.py
- gaphor/UML/modelfactory.py
- gaphor/UML/umloverrides.py
Value types can not be shown in Block as a compartment.
Issue Number: #701
* A fix is done so DataType's connect with (composite) associations similar to Classes and Interfaces
* The "Parts and References" property page has been renamed to "Compartments" and "values" have been added as an option.
> Add "values" compartment to Block item

- gaphor/services/modelinglanguage.py
- gaphor/ui/mainwindow.py
- gaphor/ui/tests/test_toolbox.py
- gaphor/ui/toolbox.py
Toolbox settings - which sections are expanded/collapsed - is defined once. The settings were used for all modeling languages.
Issue Number: #973 
Toolbox settings are stored per modeling language.
Also did a bit of cleanup in the `ModelingLanguageService`.
This is a first step towards diagram type support.
> Store toolbox settings per modeling language

- gaphor/UML/sanitizerservice.py
- gaphor/event.py
- gaphor/ui/diagrampage.py
- gaphor/ui/elementeditor.glade
- gaphor/ui/elementeditor.py
- gaphor/ui/elementeditor.ui
- gaphor/ui/event.py
- gaphor/ui/namespace.py
- gaphor/ui/namespacemodel.py
- gaphor/ui/notification.py
- gaphor/ui/tests/test_notifier.py
When you remove a diagram with diagram items, model elements that are no longer presented in any diagram will be removed. A dialog is shown (somewhere on screen) with a message.
Fixes #971.
Instead of a dialog, an in-app notification is shown. An option has been added to the Preferences pane to toggle automatic deletion of no longer presented model elements.
When a diagram is deleted with items, a notification is shown. The notification is also shown if an item is removed on a diagram.
This solution leverages the solutions already present in Gaphor: in-app notifications and our simple preferences pane.
If items are deleted by accident, they can simply be undone.
Note that the message does not tell *which* items have been removed. This is partly …
> Notification when model elements are automatically removed

- gaphor/UML/actions/partition.py
- gaphor/UML/actions/partitionpage.py
- gaphor/UML/actions/propertypages.glade
- gaphor/UML/actions/tests/test_partitionpage.py
- gaphor/diagram/text.py
Swimlanes can only have a name.
Issue Number: #426 
Swimlanes can be assigned a type, via a drop-down in the property editor. Swimlane types are restructed to UML Classifiers (Classes, Interfaces, SysML Blocks, etc..
I'll leave out the option to DnD a block on a swimlane for now.
> Allow allocation of structural types to swimlane partitions

- .github/workflows/full-build.yml
- .github/workflows/test.yml
- docs/windows.md
This PR updates to the latest gvsbuild which includes updates to harfbuzz, librsvg, and openssl. It also switches to using the official wingtk repo instead of a separate fork, since I am have the commit bit now and both repositories are identical now.
> Update to latest gvsbuild, switch to wingtk repo

- gaphor/SysML/blocks/connectors.py
- gaphor/SysML/sysml.py
- gaphor/UML/uml.py
- gaphor/codegen/coder.py
- gaphor/ui/icons/Makefile
- gaphor/ui/icons/hicolor/scalable/actions/gaphor-item-flow-symbolic.svg
- gaphor/ui/icons/stensil.svg
- models/SysML.gaphor
- models/UML.gaphor
Connector and itemProperty end up in the root of the model.
Issue Number: #841
* The SysML model has been adjusted to make itemProperty an owned property of ItemFlow
* Connector has been changed to be owned by the owner of the property it's connecting to
* ProxyPort is now properly owned by a classifier
To make the lookup for "owner" work from the SysML model, I had to make a tweak to the coder to recurse multiple models if needed.
> Fix model element ownership

- .github/workflows/appimage-docker.yml
- .github/workflows/build-docker.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/full-build.yml
- _packaging/appimage/Dockerfile
- _packaging/appimage/jhbuildrc
- _packaging/gaphor.spec
- pyproject.toml
This PR uses Docker and [jhbuild](https://gitlab.gnome.org/GNOME/jhbuild) to build GTK and then package Gaphor in an AppImage on Ubuntu-18.04 bionic. I propose that we try to support the [oldest LTS version](https://ubuntu.com/about/release-cycle) that is still getting hardware and security updates, not ones in extended security maintenance.
The Gaphor AppImage runs on distros with GLIBC >= 2.31 like Ubuntu-20.04.
Issue Number: #1023 
The Gaphor AppImage runs on distros with GLIBC >= 2.29
> Fix AppImage GLIBC Error on Older Distro Versions

- _packaging/gaphor.spec
The gaphor template files weren't included in the packaged apps using PyInstaller. This PR adds the files as extra data to be packaged.
Launch gaphor from a new template using Windows, macOS, or AppImage:
```
Traceback (most recent call last):
File "gaphor/ui/greeter.py", line 146, in _on_template_activated
File "gaphor/babel.py", line 43, in translate_model
File "xml/etree/ElementTree.py", line 1229, in parse
File "xml/etree/ElementTree.py", line 569, in parse
FileNotFoundError: [Errno 2] No such file or directory: '/home/dan/Projects/gaphor/_packaging/dist/gaphor/gaphor/templates/c4model.gaphor'
Traceback (most recent call last):
File "gaphor/ui/greeter.py", line 146, in …
```
> Fix FileNotFoundError when running packaged app

- gaphor/UML/actions/activitynodes.py
- gaphor/UML/actions/tests/test_flow.py
- gaphor/UML/actions/tests/test_flowconnect.py
- gaphor/UML/actions/tests/test_forknode.py
- gaphor/UML/actions/tests/test_grouping.py
- gaphor/UML/actions/tests/test_objectnode.py
Issue Number: #1246
This is a regression: at some point during the Gaphas 3.0 migration, positions were no longer "normalized" (`handle[0]` was reset to `(0, 0)` and the item `matrix` was updated accordingly).
This fixes the regression, without breaking backwards compatibility. 
A nicer approach may be to implement it like [ExecutionSpecification](https://github.com/gaphor/gaphor/blob/master/gaphor/UML/interactions/executionspecification.py#L116).
NB. `ForkNodeItem` does not save the lines connected to itself.
> Fork node loading

- gaphor/SysML/blocks/connectors.py
- gaphor/UML/interactions/interactionsconnect.py
- gaphor/UML/interactions/interactionsgrouping.py
- gaphor/core/modeling/presentation.py
- gaphor/core/modeling/tests/test_presentation.py
- gaphor/diagram/diagramtoolbox.py
- gaphor/diagram/tests/test_copypaste_grouping.py
- gaphor/diagram/tools/dropzone.py
- gaphor/diagram/tools/placement.py
- gaphor/services/tests/test_undo_presentation.py
When undo-ing a nested item, it's positioned wrongly.
Issue Number: #1264
The nested item appears exactly where it was when it was removed.
To change the parent of an item and keep it visually at the same place, a new method `change_parent()` was introduced.
> Fix positions of nested items during undo

- gaphor/UML/actions/tests/test_partition.py
- gaphor/UML/classes/tests/test_copypaste.py
- gaphor/UML/components/componentsgrouping.py
- gaphor/UML/components/tests/test_copypaste.py
- gaphor/UML/interactions/tests/test_copypaste.py
- gaphor/UML/profiles/tests/test_copypaste.py
- gaphor/UML/states/tests/test_copypaste.py
- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/tests/test_elementfactory.py
- gaphor/diagram/copypaste.py
- gaphor/diagram/tests/fixtures.py
- gaphor/diagram/tests/test_copypaste_full.py
- gaphor/diagram/tests/test_copypaste_grouping.py
- gaphor/diagram/tests/test_copypaste_link.py
- gaphor/services/copyservice.py
- gaphor/services/helpservice/shortcuts.ui
- gaphor/services/tests/test_copyservice.py
- tests/test_multiple_associations.py
Only a shallow (link) type of paste is supported for the diagram items
Issue Number: #791
A new key binding <key>Ctrl</key>+<key>Shift</key>+<key>p</key> can be used to copy the presentation along with the underlying model elements.
I introduced a `paste_link()` and `paste_full()` function to distinguish between the two types of pasting.
Model elements were already copied, because they were needed for cut/paste functionality.
* A lot of changes have to do with changing the test functions `copy_and_paste` and `copy_clear_and_paste` to `*_link`, to distinguish them from the deep-copy functionality.
* Newly created elements now always get a new id.
* I refactored the copy code a little to get rid of some duplication &mdash; introduced a `blacklist` …
> Full Copy/Paste of model elements

- _packaging/gaphor.spec
- gaphor/ui/macosshim.py
* Gaphor files do not have the proper file icon on macos
* On macOS, files do not load from the command line.
Issue Number: #1280
Gaphor starts and opens a model when one is double clicked from Finder
> Load files directly from macOS Finder

- gaphor/UML/interactions/interactionsconnect.py
- gaphor/UML/interactions/lifeline.py
- gaphor/UML/interactions/tests/test_message.py
Issue Number: #1285
Connecting to the lifetime (line) takes preference over connecting
to the lifeline body. But only if the lifeline is visible, of course.
> Fix Sequence diagram loading when message is close to lifeline body

- gaphor/ui/diagrams.py
Gaphor uses a legacy, fullcolor close icon for notebook tabs.
Gaphor uses a symbolic close icon for notebook tabs.
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/136
> Use symbolic close icon for notebook tabs

- .github/workflows/full-build.yml
- .github/workflows/test.yml
- gaphor/babel.py
- gaphor/i18n.py
- po/check-babel.py
- po/de.po
- po/fi.po
- po/fr.po
- po/hr.po
- po/hu.po
- po/nl.po
- po/pt_BR.po
Errors can slip in the PO files that cause our app to fail.
We do not check for errors in translations actively.
Issue Number: #1297
Check if all placeholders are properly used in the translations.
We should only use the `{key}` syntax for placeholders.
Output is like:
```
nl.po:2362: Invalid placeholders for '{name} package': 'Nieuw package'
hr.po:1281: Invalid placeholders for 'Gaphor Interactive Python Console
{version}
Type "help" for more information.
': 'Gaphorova interaktivna Python konzola
{verzija)
Za daljnje informacije upiši “help" (pomoć).
'
fr.po:2241: Invalid placeholders for 'Unable to open model “{filename}”.': 'Impossible d'ouvrir le modèle « {nom du fichier} ».'
```
> Check for placeholder errors in translations

- gaphor/ui/appfilemanager.py
- gaphor/ui/greeter.glade
- gaphor/ui/greeter.py
- gaphor/ui/greeter.ui
- gaphor/ui/mainwindow.py
Reduces the number of buttons and changes the title of the windows based on which GtkStack is open.
Issue Number: #1300
> Simplify the Greeter Dialogs

- gaphor/UML/umlfmt.py
- gaphor/ui/appfilemanager.py
- gaphor/ui/greeter.py
- po/ca.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/gaphor.pot
- po/gl.po
- po/hr.po
- po/hu.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nl.po
- po/pt_BR.po
- po/ru.po
- po/sv.po
- po/zh_Hans.po
This PR adds additional translation strings:
- The updated greeter added the app name to the Greeter and File Manager window titles. This PR removes them, as discussed in #1308. Other GNOME apps don't include the app name in the Window title.
- Adds translation for UML relationship formats like `include: ClassName`
Window titles say, for example: `Gaphor - Create a New Model`
Issue Number: 1308
Window titles say, for example: `Create a New Model`
> Add Additional Strings for Translation

- gaphor/diagram/tools/tests/test_txtool.py
- gaphor/diagram/tools/txtool.py
It's no possble to split a line in two segments.
Issue Number: #1312
Start a transaction on `drag-begin`, So handle creation happens within a transaction.
Reverts d55585903ef6ac9ab7ad119f4b167f22f564b0c9 (except for one line).
Fixes #1312.
> Fix splitting of lines

- gaphor/ui/__init__.py
- poetry.lock
- pyproject.toml
Dark mode is not picked up for macOS and Windows.
Issue Number: #1335
Set a dark-mode preference flag on macOS and Windows. Do not do this for any Linux/FreeBSD platform, since it works just fine on GNOME/KDE.
Note that the mode is set on startup, it does not change after that.
Tests:
> Automatically select dark mode for macOS and Windows

- docs/connect.gaphor
- gaphor/SysML/requirements/connectors.py
- gaphor/UML/actions/flowconnect.py
- gaphor/UML/actions/tests/test_flowconnect.py
- gaphor/UML/classes/classconnect.py
- gaphor/UML/classes/tests/test_associationconnect.py
- gaphor/UML/classes/tests/test_containmentconnect.py
- gaphor/UML/classes/tests/test_dependencyconnect.py
- gaphor/UML/classes/tests/test_generalizationconnect.py
- gaphor/UML/classes/tests/test_interfacerealizationconnect.py
- gaphor/UML/classes/tests/test_realizationconnect.py
- gaphor/UML/profiles/packageimportconnect.py
- gaphor/UML/states/tests/test_transition_connect.py
- gaphor/UML/states/vertexconnect.py
- gaphor/UML/usecases/tests/test_extend.py
- gaphor/UML/usecases/tests/test_include.py
- gaphor/UML/usecases/usecaseconnect.py
- gaphor/diagram/connectors.py
- gaphor/diagram/copypaste.py
- gaphor/diagram/tools/connector.py
Currently, reconnecting a line to another element can make the model and diagrams inconsistent.
Issue Number: #1347 
Instead of modifying existing relations, create a new relation and copy the properties from the old relation. This way filled in values, like name and guard conditions will stay, although the underlaying model element has been replaced completely.
This change currently works for simple relations, like Dependency and Generalization. The more complex ones (Association, Extension, Connector) do not use this functionality, but should use a similar scheme.
* When recreating, notifications are issued that unused model elements have been removed.
* A copy of the existing model elements (if any) is made when a `Connector` is created. …
> Improve reconnect for relationships

- gaphor/UML/classes/association.py
- gaphor/UML/classes/classconnect.py
- gaphor/UML/classes/classestoolbox.py
- gaphor/UML/classes/tests/test_associationconnect.py
- gaphor/UML/profiles/tests/test_extensionconnect.py
- gaphor/diagram/connectors.py
- tests/test_composite_association.py
* Association is the only relation type that holds a model element when disconnected.
* It's not able to find existing associations from the model when a relation is drawn in a diagram.
Issue Number: #1009?
This PR unifies the behavior of Association with other relation types. Associations can be looked up, it can use the  copy functionality introduced in #1351.
Requires #1351 to be merged.
> Update connection behavior for Association

- .github/workflows/hypothesis-test.yml
- .gitignore
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/element.py
- gaphor/core/modeling/elementfactory.py
- gaphor/services/copyservice.py
- gaphor/services/undomanager.py
- gaphor/storage/upgrade_canvasitem.py
- gaphor/transaction.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_hypothesis.py
- tests/test_model_consistency.py
We've seen issues reported by users that we could not properly reproduce.
A [Hypothesis Stateful Test](https://hypothesis.readthedocs.io/en/latest/stateful.html) (model-based test) has been added that performs actions a user would do: create/remove items, copy/paste, undo/redo.
So far this test manages to fail in a couple of cases.
, 
To run an in-depth test, run `pytest --hypothesis-profile=ci tests/test_model_consistency.py`. It should raise an error where connections in the diagram do not match connections in the model.
This change also contains some Sourcery updates, not directly related to the functional change.
The implementation can be extended even more. However, this is a good start, and already uncovered an error. …
> Simulate user behavior with Hypothesis

- .github/workflows/appimage-docker.yml
- .github/workflows/full-build.yml
- _packaging/appimage/Dockerfile
- pyproject.toml
This PR sets the environmental variable `XDG_DATA_DIRS` so that Gtk can find the user-specific data files related to GNOME when compiled from source. Also, librsvg was failing to build and this updates the dependencies to fix that issue with the docker image.
AppImage version of Gaphor crashes on save.
Issue Number: #1355 
No crashes
> Fix AppImage Crashes on Save Command

- gaphor/SysML/blocks/proxyport.py
ProxyPort behavior is off when the port is moved around.
Issue Number: #1277 
The problem was that the port positions were not updated when the port moved. Hence they always stayed at their initial location.
This PR fixes that.
> Proxyport: update ports when proxyport is moved

- gaphor/ui/namespace.py
You have to explicitly edit a newly created diagram in order to change its name.
Issue Number: #1276
When a new diagram is created, it is made editable instantly.
> Edit newly created diagram name

- docs/modeling_language.md
- gaphor/SysML/drop.py
- gaphor/SysML/modelinglanguage.py
- gaphor/SysML/tests/test_drop.py
- gaphor/UML/__init__.py
- gaphor/UML/drop.py
- gaphor/UML/recipes.py
- gaphor/UML/tests/test_drop.py
- gaphor/core/__init__.py
- gaphor/core/modeling/collection.py
- gaphor/core/modeling/elementdispatcher.py
- gaphor/core/modeling/properties.py
- gaphor/core/modeling/tests/test_collection.py
- gaphor/diagram/connectors.py
- gaphor/diagram/drop.py
- gaphor/diagram/tools/dnd.py
- gaphor/services/undomanager.py
- gaphor/ui/diagrampage.py
- gaphor/ui/drop.py
- tests/test_model_consistency.py
Only classes, packages can be dragged from tree view to diagram.
Issue Number: #648 
Model elements can be dragged from tree view to diagram.
Covered "simple" elements and relationships, complex relationships (Association, Extension, Connector, Message) and Proxy port.
I think that's all.
> Allow to drag and drop all elements from tree view to diagram

- gaphor/C4Model/propertypages.ui
- gaphor/SysML/propertypages.ui
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/classes/propertypages.ui
- gaphor/UML/deployments/propertypages.ui
- gaphor/UML/interactions/propertypages.ui
- gaphor/UML/profiles/propertypages.ui
- gaphor/UML/states/propertypages.ui
- gaphor/diagram/propertypages.ui
- gaphor/ui/styling-gtk4.css
- gaphor/ui/uipreview.py
- pyproject.toml
GTK4 property page layout was off. Switches were not right aligned.
Issue Number: #618 
Updated the UI to look similar to GTK3. Changed margin properties and such for classes.
I added a little app (`gaphor/ui/uipreview.py`) to check on the preview layouts.
> Fix GTK4 property page layouts

- gaphor/RAAML/stpa/stpatoolbox.py
- gaphor/SysML/blocks/blockstoolbox.py
- gaphor/UML/profiles/metaclasspropertypage.py
- gaphor/UML/profiles/propertypages.glade
- gaphor/UML/profiles/propertypages.ui
- gaphor/core/eventmanager.py
- gaphor/services/undomanager.py
- tests/test_model_consistency.py
- tests/test_undo.py
The Model Based Test (`tests/test_model_consistency.py`) has been extended to include all model elements currenly in use, from all modeling languages.
This uncovered a few (small) issues:
* Shared and Composite Association should not have a subject by default
* STPA relation RelevantTo should not have a subject by default
* Reflexive Message could not be undone. This had to do with how events were emitted.
Previously, events were emited directly. This ment that when one event was "in flight", a new (nested) event could be handled. This can cause for some issues in event ordering, as was the case with Undo Manager.
In the new implementation, events are queued, instead of handled. This means that one event is handled by *all* event handlers before …
> Include all diagram items in test model

- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/tests/test_elementfactory.py
- gaphor/services/undomanager.py
- tests/test_undo.py
A carefully constructed model can break Gaphro's undo behavior.
Issue Number: #1457 
* `ElementFactory.create(_as)` is idempotent: when it receives a create request for an id and type it already knows, it returns that element instead of creating a new one.
* When undoing a `Presentation` element, a `Diagram` is created if it does not exist yet. Presentations depend on a diagram in order to be created.
ElementFactory's create method is idempotent now.
> Fix diagram dependency cycle

- .github/workflows/codeql-analysis.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Update permissions for CodeQL GitHub Action

- gaphor/SysML/blocks/proxyport.py
- gaphor/UML/actions/__init__.py
- gaphor/UML/actions/actionstoolbox.py
- gaphor/UML/actions/flowconnect.py
- gaphor/UML/actions/pin.py
- gaphor/UML/actions/pinconnect.py
- gaphor/UML/actions/tests/test_flowconnect.py
- gaphor/UML/actions/tests/test_pin.py
- gaphor/UML/actions/tests/test_pinconnect.py
- gaphor/UML/uml.py
- gaphor/diagram/presentation.py
- gaphor/ui/icons/Makefile
- gaphor/ui/icons/hicolor/scalable/actions/gaphor-input-pin-symbolic.svg
- gaphor/ui/icons/hicolor/scalable/actions/gaphor-output-pin-symbolic.svg
- gaphor/ui/icons/stensil.svg
- models/UML.gaphor
Pins are not supported.
Support for input and output pins.
> Pin support for activity diagram

- gaphor/SysML/drop.py
- gaphor/UML/actions/activity.py
- gaphor/UML/actions/activityconnect.py
- gaphor/UML/actions/tests/test_pin.py
- gaphor/UML/drop.py
- gaphor/diagram/presentation.py
- gaphor/diagram/tests/fixtures.py
When loading a model with pins, and object flows connected to those pins, the object flow may be connected in wrongly -> not in a state as when you saved it.
Fix loading of Attached Presentations. The boundaries of an attached presentation are calculated by constraints. By resolving those constraints it ensures the line is connected exactly as when you saved it.
> Fix pin connections when loading a model

- .github/workflows/full-build.yml
- .github/workflows/release-drafter.yml
- .github/workflows/test.yml
This PR adds skip-duplicate-action which will prevent rerunning CI jobs that have already been run. It also adds permissions for release-drafter.
> Add Skip Duplicate Action and Release-Drafter Permissions

- gaphor/ui/diagrams.py
- gaphor/ui/event.py
- gaphor/ui/namespace.py
Currently diagram items can only be added from the tree view by means of drag-and-drop. It would be good to be able to perform this without DnD.
Issue Number: #1520 
Elements can be added by double click and by an entry in the popup menu.
> Add element to diagram by double click

- gaphor/diagram/tools/__init__.py
- gaphor/ui/diagrampage.py
When scrolling with a touch screen, the scrolling happens too fast.
Issue Number: #1425
Scrolling works as expected with touchscreens.
Gaphor no longer uses the `scroll_tool` from Gaphas. Instead it relies on the scroll behavior of the `ScrolledWindow`, underneath the diagram. This way scroll behavior is similar to, for example, the toolbox.
This is a `packaging` branch, so I can test the results on a Windows machine with touchscreen.
> Fix scroll speed for touch screens

- gaphor/UML/uml.py
- gaphor/core/modeling/properties.py
- gaphor/core/modeling/tests/test_properties.py
- gaphor/diagram/tests/test_copypaste_full.py
- gaphor/services/tests/test_undomanager.py
- tests/conftest.py
A curious construction of packages containing diagrams can not be fully/deep copied.
Issue Number: #1535 
When pasting (or loading) a relationships is established. However, if the opposite side is already set, and has a multiplicity of `[0..1]`, the existing relation should not be overwritten.
> Fix issue with fully pasting a diagram

- docs/modeling_language.md
- gaphor/UML/actions/actionseditors.py
- gaphor/UML/classes/classeseditors.py
- gaphor/diagram/general/generaleditors.py
- gaphor/diagram/inlineeditors.py
- gaphor/diagram/instanteditors.py
- gaphor/diagram/tests/test_instanteditors.py
- gaphor/diagram/tools/__init__.py
- gaphor/diagram/tools/placement.py
- gaphor/diagram/tools/textedit.py
- gaphor/ui/styling-gtk4.css
Instant editors do not work with GTK4.
Issue Number: #1555
Editors work.
The class `InlineEditor` has been renamed to `InstantEditor`.
> Fix instant editors for GTK4

- gaphor/services/copyservice.py
- gaphor/services/tests/test_copyservice.py
- tests/test_model_consistency.py
- tests/test_multiple_associations.py
No proper copy/paste in our GTK4 version
Issue Number: #274, #618 
Copy paste works with Gdk.Clipboard.
This will allow us to extend it with copy/paste of images, for example, so you can easily share stuff with other apps. Also we can paste things like text in the application now.
> Add Copy/Paste for GTK4

- gaphor/core/modeling/element.py
- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/tests/test_elementfactory.py
I ran into a nice edge case. In gaphor 2.10 we changed the behavior of the EventManager. If an event B is triggered while event A is being handled, B is held back and handled once all handlers for A have been executed.
This fixed some issues in our Undo manager.
However, it seems like it can also introduce some unexpected behavior.
We have a Sanitizer service. This service is responsible for deleting a model element if there are no presentations of that element left. The effect (removed from model and Element.model set to None) takes effect immediately. However the event is added to the queue where a bunch of events still need to be handled. Some of the event handlers expect Element.model to be set.
One way to solve it is to ensure the effect …
> Fix unlinking elements from the model 

- gaphor/UML/classes/association.py
- gaphor/UML/deployments/connector.py
* text and association end arrows can overlap
* association direction arrow can overlap with text
Issue Number: #1451
* text at association ends has a little more padding
* direction arrows are always drawn at the opposite side of the text
> Improve text placement for Associations

- .github/workflows/codeql-analysis.yml
We are getting two warnings and an error on our CodeQL builds:
1. `git checkout HEAD^2` is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
2. Please specify an on.push hook so that Code Scanning can compare pull requests against the state of the base branch.
3. Error: The process '/home/runner/work/_actions/github/codeql-action/v2/python-setup/auto_install_packages.py' failed with exit code 1. Please make sure any necessary dependencies are installed before calling the codeql-action/analyze step, and add a 'setup-python-dependencies: false' argument to this step to disable our automatic dependency installation and avoid this warning.
What kind of change does …
> Fix codeql warnings and error

- docs/style-sheet-examples.gaphor
- docs/style_sheets.md
This PR will add a todo example of use for css in the docs.
The changes result in this new section:
Thanks to @danyeaw kind assist for showing me how to implement the example.
> Todo example of use for css

- gaphor/plugins/xmiexport/exportmodel.py
- gaphor/services/properties.py
- gaphor/storage/parser.py
- gaphor/ui/filemanager.py
- gaphor/ui/tests/test_filemanager.py
- test-models/wrong-encoding.gaphor
Models with non-ascii characters created on Windows, can't be loaded on Linux.
Issue Number: #1585 
Files are explicitly saved with UTF-8 encoding.
I expected UTF-8 to be the default encoding, also for files, since `sys.getdefaultencoding()` returns `utf-8`.
> Ensure all models are saved with UTF-8 encoding

- gaphor/UML/states/finalstate.py
- gaphor/UML/states/pseudostates.py
- gaphor/UML/states/state.py
- gaphor/UML/states/tests/test_transition_connect.py
- gaphor/UML/states/vertexconnect.py
- gaphor/core/modeling/tests/test_literal_eval.py
Transitions can't start and end on the same State.
Issue Number: #1577 
Transitions can be self-referencing.
> Transition can self-reference State 

- .github/workflows/full-build.yml
- _packaging/windows/win_installer.nsi
This PR moves the installation location on Windows to C:\Program Files from C:\Program Files (x86).
If upgrading versions, it will automatically uninstall previous versions, even if they are in C:\Program Files (x86), or any other location. However, it will by default specify the previous location and the user would need to remove the (x86) if they want it installed somewhere else, which I think is OK. For new installs, it always defaults to C:\Program Files.
Gaphor is installed to C:\Program Files (x86)
Issue Number: #1580
Gaphor is installed to C:\Program Files
> Move Windows Installation to C:\Program Files

- .github/workflows/full-build.yml
- _packaging/gaphor.spec
- _packaging/make-script.py
- poetry.lock
- pyproject.toml
tomllib is being introduced in Python 3.11 by adding tomli to the standard library. This PR changes to using tomllib by default if it is available.
> Replace tomli with tomllib for Python 3.11+

- gaphor/ui/__init__.py
Using `GtkSettings:gtk-application-prefer-dark-theme` with libadwaita is unsupported. This PR updates to use `AdwStyleManager:color-scheme` instead when running in GTK4.
Color scheme warning seen in some macOS builds
No warning
> Fix color scheme warning with libadwaita

- gaphor/UML/profiles/extensionconnect.py
- gaphor/UML/recipes.py
- gaphor/UML/sanitizerservice.py
- gaphor/UML/tests/test_recipes.py
- gaphor/UML/tests/test_sanitizerservice.py
- gaphor/UML/uml.py
- models/UML.gaphor
Stereotypes are not removed from classes when the (extension) relation has been broken.
Issue Number: #1635 
Stereotypes do are again removed when extensions are removed.
This regression was casued by the new event manager. Now events are queued. So when the event is handled, a lot of propertyies can have changed already. The new algorithm checks for which elements the stereotype application is still valid and removed it from the invalid ones.
> Fix stereotype unapplication

- gaphor/ui/treecomponent.py
- gaphor/ui/treemodel.py
When you select the "Rename" entry from the popover menu in the tree view, the text is not editable on Wayland.
On X11 it works fine, though :/.
"Rename" is available fro a shortcut (`F2`). I could not find a way to make the popover work in combination with the edit feature.
Therefore I propose to remove the "Rename" option from the popover.
> Fix "rename" from popover

- _packaging/gaphor.spec
- _packaging/hooks/hook-gi.repository.freetype2.py
- _packaging/hooks/pre_safe_import_module/hook-gi.repository.freetype2.py
- poetry.lock
Update PyInstaller to version 5.3 and removes local hooks that are now included upstream. 
> Update PyInstaller to version 5.3

- gaphor/UML/profiles/tests/test_stereotypepropertypages.py
- gaphor/UML/recipes.py
- gaphor/UML/sanitizerservice.py
- gaphor/UML/tests/test_recipes.py
- gaphor/UML/tests/test_sanitizerservice.py
- gaphor/UML/tests/test_uml2.py
- gaphor/ui/treecomponent.py
Stereotypes inherited from other stereotypes can not be assigned. They are not shown in the property page.
Issue Number: #672
> Support stereotypes inherited from other stereotypes

- .devcontainer/devcontainer.json
Fedora uses SELinux. Also I needed to explicitly expose the ports.
Those are a few tweaks I needed to do to get the devcontainer running on my local machine.
> Update devcontainer to work on Fedora

- gaphor/application.py
- gaphor/event.py
- gaphor/plugins/diagramexport/__init__.py
- gaphor/plugins/xmiexport/__init__.py
- gaphor/services/properties.py
- gaphor/tests/test_application.py
- gaphor/ui/filedialog.py
- gaphor/ui/filemanager.py
- gaphor/ui/mainwindow.py
- gaphor/ui/tests/test_filedialog.py
- gaphor/ui/tests/test_filemanager.py
When exporting a diagram, the folder always reverted to the current working directory
Issue Number: #1675
Fix #1675 behavior.
In addition, use `pathlib.Path` for paths internally, instead of `str`.
Some events now contain a `Path` instead of a `str` object.
> Retain save folder - use Path

- gaphor/plugins/console/console.py
- gaphor/ui/statuswindow.py
- gaphor/ui/toolbox.py
When you create a new item on a diagram, a warning is printed to stdout:
```
(gaphor:2109098): Gtk-CRITICAL **: 21:57:18.331: gtk_event_controller_get_propagation_phase: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed
```
This warning is fixed: a new set of controllers is set from an idle handler.
> Fix event-controller warning on GTK4

- docs/modeling_language.md
- gaphor/UML/actions/actionseditors.py
- gaphor/UML/classes/classeseditors.py
- gaphor/diagram/general/generaleditors.py
- gaphor/diagram/instanteditors.py
- gaphor/diagram/tools/placement.py
- gaphor/diagram/tools/textedit.py
When an instant editor closes, focus is not automatically returned to the diagram. This causes users to do an extra click, before (for example) shortcuts can be used again
Instant editors work in GTK4 the same as GTK3.
> Fix Instant editor focus on GTK4

- gaphor/UML/__init__.py
- gaphor/UML/profiles/stereotypepropertypages.py
- gaphor/UML/profiles/tests/test_stereotypepropertypages.py
- gaphor/UML/recipes.py
- gaphor/UML/tests/test_sanitizerservice.py
When you inherit a stereotype from another stereotype, the attributes of the super stereotype do not show up in the property editor for the sub type.
Issue Number: #672
Attributes from a super type also contribute to a sub type
> Inherited stereotype part 2: attributes from super type

- gaphor/UML/interactions/interactionsconnect.py
- gaphor/UML/interactions/lifeline.py
- gaphor/UML/interactions/message.py
- gaphor/UML/interactions/tests/test_messageconnect.py
Issue Number: #1599 
* Messages can be connected everywhere on a lifeline object
* The timeline can now always be extracted (used to be blocked when a message was connected to the body)
* Saving and loading has been fixed to support connecting to body as well as timeline
* Only if a message is connected between two lifeline elements without timeline (timeline is collapsed), a communication diagram style message will be shown.
Timeline length is saved differently.
> Allow sequence diagram messages on lifeline body

- gaphor/UML/tests/test_umllex.py
- gaphor/UML/umllex.py
For attributes and operations (parameters).
Currently syntax like `attr: Generic<Type>` is not supported.
Issue Number: #1720
The `<Type>` bit is parsed as part of the type value. No special meaning is provided. This is the same as it currently works for union types.
> Support Generic<Type> syntax

- gaphor/ui/toolbox.py
- gaphor/ui/treecomponent.py
On GTK4/macos DnD does not work. It makes the IU block. Therefore it may be better to disable DnD on macOS, at least until it's properly working.
> macos: Disable DnD for GTK4

- gaphor/diagram/tools/__init__.py
- gaphor/diagram/tools/shortcut.py
- gaphor/diagram/tools/tests/test_shortcut.py
A diagram can be automatically deleted when you delete an item that's also an owner of the diagram. Although this is correct, according to Gaphor's inner workings, it's quite surprising for a user to see his diagram gone spontaneously.
Issue Number: #1747
The diagram is moved to toplevel before the owner element is removed. This avoids surprising removal.
I initially tried to fix it in the `SanitizerService`. However, then we should determine what to do while the item is halfway unlinking. Then it's not possible to determine if an element is an owner element reliably.
> Prevent deleting an element in a diagram also deleting the diagram itself

- .github/dependabot.yml
Change the dependabot PRs so they have the skip-changelog label
Dependabot PRs have the default labels like dependancy
Dependabot PRs have the skip-changelog label
> Add skip-changelog label to dependabot PRs

- gaphor/ui/namespace.py
Gdk.Rectangle doesn't accept arguments, which resulted in the coordinates and width/height not being set.
These properties are now set. As a result of this change, 'set_offset' is no longer required.
> namespace.py: Actually set properties for rectangle

- .github/actions/windows_executables/action.yml
I have updated the project secrets with the new PFX file and updated password for the Windows certificate. The new cert is good until 2025-10-04, so we need to order a new one beginning of September.
The certificate signing was previously failing semi-silently, where it gave an error but didn't cause the build to fail. This PR fixes this by forcing an Exit 1 if the signing fails.
Windows binaries are unsigned
Issue Number: #1756 
Windows binaries are now signed
> Fail CI build if Windows certificate signing fails

- docs/linux.md
- docs/macos.md
- gaphor/diagram/tools/shortcut.py
1. When deleting, it checks if there are no modifiers or the META modifier is pressed. However, keys like _caps lock_ and _scroll lock_ are also modifiers -> deletion will not work.
2. The modifier masdk `MOD2_MASK` is no longer available in GTK4.
Issue Number: #1788 
The Delete element shortcut works without checking modifier keys.
> Fix key modifiers for delete element shortcut

- .github/workflows/full-build.yml
Our build was failing due to a zlib download error. This PR updates to the new version which uses a zlib link that won't if a new version is released.
Build is failing
Build is passing
> Update gvsbuild to 2022.4.1 to fix zlib error

- poetry.lock
- pyproject.toml
Linters are installed. When running pre-commit, pre-commit installs the linters again, separately.
Linters have been removed as development dependencies. Only pre-commit is installed.
> Remove lint tooling handled by pre-commit from pyproject.toml

- mypy.ini
- pyproject.toml
`tests` folders have a `__init__.py` file.
According to [Pytest's good practices](https://docs.pytest.org/en/latest/explanation/goodpractices.html), that is not required.
Pytest now uses `importlib`.
> Pytest now uses importlib

- gaphor/ui/appfilemanager.py
- gaphor/ui/errorhandler.py
- gaphor/ui/filemanager.py
This PR uses one of the new features in libadwaita 1.2 to update the Message Dialogs.
Gaphor uses Gtk.MessageDialogs for asking the user a question:
Gaphor uses the new Adw.MessageDialogs:
This requires GNOME 43 and libadwaita 1.2
> Update Message Dialogs to libadwaita

- gaphor/ui/treecomponent.py
You need to use the popup on the tree view if you want to remove an element.
Issue Number: #1834
Elements can be  deleted from the tree view directly by hitting Delete.
Only works for GTK 4.
> Support Delete to delete entries from tree view

- gaphor/ui/greeter.py
- gaphor/ui/tests/test_greeter.py
The "Recent Models..." option is always enabled in the menu, even if no recent files are available. It opens the new model dialog which is confusing.
Issue Number: #1829 
The menu entry is disabled if no recent files are present.
You can test this by removing all recently opened Gaphor files from the "Recent" page in the file explorer (Nautilus).
> Disable Recent files if no recent files are present

- gaphor/UML/classes/interfaceconnect.py
When connecting a dependency to a folded interface, the visual for the interface does not show the socket.
The visual is updated to show the socket.
Before connecting:
After connecting:
> Update folded interface shape when connecting dependency

- gaphor/UML/usecases/actor.py
- gaphor/UML/usecases/tests/test_actor.py
If you attach a relation (association, dependency) to the bottom of an Actor, the relation crosses the actor name.
Issue Number: #1231, #1854
An extra port has been added below the name of the actor. You can attach your associations and dependencies there.
> Added extra port below text for actor

- gaphor/ui/layout.py
The separator for the toolbox can be dragged down completely. It looks like  the toolbox is gone
Issue Number: #1872
Ensure a minimal visible area on both sides of a Gtk.Paned.
This feature is compatible with GTK3, although in GTK3 there was already a minimal visible area.
> Ensure both sides of a Gtk.Paned are always visible

- gaphor/ui/help/__init__.py
This fixes a bug introduced by #1871. When opening the about and keyboard shortcuts dialog, a FileNotFoundError was thrown.
About and Keyboard Shortcut dialogs won't load
Dialogs are working properly
> Fix file not found for about and keyboard shortcut dialogs

- .github/labeler.yml
Automatically label pre-commit.ci and all-contributor with skip-changelog so that they don't show up in our release drafts.
Also fixes the Python labeler, since it wasn't working except for Python files in the root of the project.
No labels are applied and they have to be manually added for these two bots
skip-changelog label is automatically added
> Auto add skip-changelog label for pre-commit.ci and all-contributors

- gaphor/ui/elementeditor.py
- gaphor/ui/greeter.ui
- gaphor/ui/help/shortcuts.ui
- gaphor/ui/mainwindow.ui
Keyboard shortcuts as defined in the [GNOME HIG](https://developer.gnome.org/hig/reference/keyboard.html):
* `F10` Open menu
* `F9` Toggle side pane
> Standard keyboard shortcuts

- .github/workflows/full-build.yml
- docs/windows.md
This PR limits the number of cores to 2 during the Windows build and updates the Windows build command in the docs for GTK4.
This should help get rid of out of memory errors while linking GTK4.
> Improve Windows build reliability by limiting cores to 2

- gaphor/ui/actiongroup.py
- gaphor/ui/help/__init__.py
- gaphor/ui/macosshim.py
- [] Bug fix
On GTK4 no magic mapping is done for us on macOS, where `Command` serves as primary modifier.
Issue Number: #1839
We remap the `Primary` modifier on macOS to the `Meta` key (`Command`).
> Fix macOS shortcuts on GTK 4

- gaphor/extensions/sphinx.py
Files are placed in the wrong location, depending on the working directory the Sphinx builder is started from.
Issue Number: #1902
Fixed.
Thanks @2old4it!
> Support non-standard Sphinx directory structures

- gaphor/plugins/autolayout/pydot.py
Sequence diagrams can be auto-layouted, which guarantees a messed up diagram 
Issue Number: #1899
Explicitly exclude sequence diagrams from auto-layouting.
> Do not auto-layout sequence diagrams

- gaphor/ui/macosshim.py
Cursor shortcuts (`Cmd+Left`, etc.) do not work.
Issue Number: #1839
Cursor shortcuts work as expected.
I reworked the code a little, so shortcuts are only loaded for macOS.
I think this is the last change related to macOS keyboard shortcuts in GTK4.
> macOS: cursor shortcuts

- .github/actions/setup_and_test/action.yml
- .github/actions/windows_executables/action.yml
- .github/workflows/full-build.yml
- docs/windows.md
- gaphor/RAAML/fta/majorityvotegate.py
- poetry.lock
- pyproject.toml
- tests/test_gaphorconvert.py
This PR fixes Windows build issues by:
- Upgrading gvsbuild to version 2022.6.0
- Update the Windows docs to use the official Python installer and install wheels from gvsbuild
- Fix an issue with `test_gaphorconvert` where it was using relative file paths, updated to use importlib
> Update gvsbuild to upgrade cairo in Windows

- gaphor/core/modeling/stylesheet.py
- gaphor/core/modeling/tests/test_diagram_style.py
- gaphor/diagram/text.py
- gaphor/ui/__init__.py
- gaphor/ui/diagrams.py
- models/SysML.gaphor
- models/UML.gaphor
We use the default font `sans`, which looks a bit off.
Issue Number: #1921 
* The system default UI font is set when the UI is used.
* Fallback to the well known "Sans" font.
* Removed default style from our models
It looks like the changes in element dimensions are minimal. The fonts have slightly different sizing.
> Use system fonts by default for diagrams

- gaphor/codegen/tests/test_coder.py
- gaphor/core/modeling/collection.py
- gaphor/core/modeling/listmixins.py
We could use string based queries, but never used those.
Just use a list comprehension:
```python
a = instancespec.ownedAttribute["it.name == 'specification'"][0]
a = next(it for it in instancespec.ownedAttribute if it.name == 'specification')
```
> Remove querymixin from modeling lists

- gaphor/UML/classes/classconnect.py
- gaphor/core/eventmanager.py
- gaphor/core/modeling/tests/test_presentation.py
- gaphor/core/tests/test_eventmanager.py
- gaphor/services/undomanager.py
- gaphor/storage/storage.py
There is still a possibility that a model is saved in a state that can't be loaded.
Issue Number: #1928
* Add an extra check for presentation elements that lack a diagram reference. We can easily get rid of those *iff* they are not referenced.
* Add an extra check for association connections: do not assume `Association.memberEnd` is always populated.
* Add a priority lane for event handlers. This is mainly to allow Undo Manager to receive all events
My hypothesis on why things still can break is because not all events are properly registered at the undo manager. In that case we can no do a full undo, and the model may remain in an inconsistent state. The effect (e.g. a property is set) is applied directly, then we notify by means of an event. …
> Fix loading error

- gaphor/ui/namespace.py
Fixes #1952 which is an assertion error while creating a package that is nested under a non-package item.
The New Package option was always visible on the right click menu.
Issue Number: #1952
The New Package option is disabled unless you are right-clicking on a package.
> Hide New Package menu unless package selected

- gaphor/ui/filemanager.py
Locally, Gaphor throws some warnings when it's exiting. On flatpak it just dumps core.
Issue Number: #1962
Somehow it works better if the final dialog is not transient to the window.
Given I do not see warnings anymore locally, I expect this change to fix flatpak.
> Fix coredumps on Flatpak

- .github/workflows/codeql-analysis.yml
- .github/workflows/full-build.yml
- .github/workflows/hypothesis-test.yml
This PR resolves a cannot create symlink error with actions/cache version 3.2.1 by changing the Windows cache key to include the runner os. They reverted the change in version 3.2.2, but it still seems like it a best practice to include the runner os in the key.
Symlink error in CI when upgrading actions/cache versions
No errors
> Windows CI: fix cannot create symlink error

- gaphor/ui/filedialog.py
Windows build falls back to `GtkFileChooserDialog` instead of using its native file chooser.
See https://docs.gtk.org/gtk4/class.FileChooserNative.html#win32-details
Use of `GtkFileChooserNative` on Windows.
> Use native file chooser on Windows

- .github/actions/setup_and_test/action.yml
- .pre-commit-config.yaml
- _packaging/windows/build-win-installer.py
- gaphor/UML/actions/tests/test_objectnode.py
- gaphor/codegen/coder.py
- gaphor/codegen/override.py
- gaphor/diagram/tests/test_export.py
- gaphor/extensions/sphinx.py
- gaphor/extensions/tests/test_sphinx.py
- gaphor/plugins/console/consolewindow.py
- gaphor/plugins/diagramexport/gaphorconvert.py
- gaphor/plugins/xmiexport/tests/test_exportmodel.py
- gaphor/services/properties.py
- gaphor/services/tests/test_properties.py
- gaphor/storage/tests/test_parser.py
- gaphor/storage/tests/test_storage.py
- gaphor/storage/tests/test_storage_message_item_upgrade.py
- gaphor/tests/test_application.py
- gaphor/tests/test_babel.py
- gaphor/ui/mainwindow.py
- gaphor/ui/selftest.py
- gaphor/ui/uipreview.py
- po/check-babel.py
- tests/test_action_issue.py
- tests/test_load_model.py
- tests/test_model_consistency.py
- tests/test_models_up_to_date.py
- tests/test_package_removal.py
PEP 597 adds encoding warnings and will eventually make UTF-8 the default encoding in Python. This PR fixes encoding warnings to help prevent bugs introduced due to encoding warnings. For example, our `check-babel` module wouldn't run at all in Windows due to an encoding error.
I don't think should be a breaking change, we already try to set encoding to None if opening a model fails due to an encoding error.
In many places we open and write to files without the encoding specified
Encodings are explicitly set to UTF-8
> Fix PEP597 Encoding Warnings

- _packaging/gaphor.spec
- gaphor/i18n.py
This PR fixes two major issues with translations:
1. PyInstaller wasn't collecting any .mo translation files, so they weren't available in any of the packaged apps built using PyInstaller.
2. On Windows, Gaphor wasn't automatically setting the language based on the locale Windows was running with, so translations weren't working without manually setting the LANG environmental variable
App translations aren't working with packaged apps on Windows, macOS, and Linux with AppImage
Issue Number: #1969 
Translations are working on all platforms
> Fix Translations on Windows, macOS, and AppImage

- .github/scripts/metadata.sh
- .pre-commit-config.yaml
- _packaging/gaphor.spec
- poetry.lock
- pyproject.toml
When using a semver pre-release version in the form of 1.0.0-alpha, the pyinstaller-versionfile package was throwing a version validation error. It expects a version in the form of 1.0.0.0 (Windows Version Info format) or 1.0.0 only.
This PR:
1. Uses the semver package to process our version string
2. Passes in only the major, minor, patch
3. Updates our dev version format to match the [build metadata](https://semver.org/#spec-item-10) format in semver
4. Enables pre-commit hooks on our gaphor.spec
Versionfile parse error with pre-release versions
No errors
> Fix PyInstaller versionfile parse error with pre-release versions

- .github/actions/linux_appimage/action.yml
- .github/actions/macos_dmg/action.yml
- .github/actions/windows_executables/action.yml
In run https://github.com/gaphor/gaphor/actions/runs/3824238322/jobs/6520647088 we are getting a socket hangup error when trying to upload final release assets from Windows. We have seen this in the past with Linux as well when we were uploading the sdist and wheel.
This PR replaces use of https://github.com/AButler/upload-release-assets with the gh CLI. Others who have seen this error have reported success with this method.
Intermittent socket hang up errors with CI
No socket hang up
> Fix socket hang up error during release upload

- gaphor/ui/csscompletion.py
- gaphor/ui/elementeditor.py
I accidentally messed up https://github.com/gaphor/gaphor/pull/1951 when I tried to rebase it around the changes in the main branch.
> Add CSS function completion provider

- gaphor/ui/csscompletion.py
Appends `()` and moves the cursor between `(` and `)` when inserting a CSS function through autocompletion.
> Append `()` when inserting a CSS function

- gaphor/ui/csscompletion.py
Appends `: ` when inserting CSS properties. Example `border` gets inserted as `border: `.
> Append colon and space when inserting CSS props

- gaphor/UML/actions/activitymove.py
- gaphor/diagram/tools/__init__.py
- gaphor/diagram/tools/handlemove.py
- gaphor/diagram/tools/itemtool.py
- gaphor/diagram/tools/tests/test_handlemove.py
* items a line handle can't connect to are not grayed out
* guides do not work
Before mentioned functionality has been restored.
All logic (mixins) related to line handle movement is now in one place, which makes it less likely issues occur.
> Regression: line handles should snap to elements when moved around

- gaphor/i18n.py
When fallback is set to True, gettext uses a NullTranslator to return the message and an exception isn't raised if there is an issue with the translation files. We also are using a try-except block to print a warning message. With fallback set, the warning message is never printed.
This PR removes the fallback value, which causes it to default to False.
Warnings are never printed for missing translation files.
Warnings are restored.
> Fix translation warning never logged with missing mo files

- gaphor/ui/diagrams.py
- gaphor/ui/diagrams.ui
- gaphor/ui/mainwindow.ui
If no diagrams are open, and no tab bar is shown, it's pretty empty. It's hard to tell if there's an empty diagram opened or nothing at all.
If no diagrams are shown, a status widget is shown that directs users to opening/creating diagrams.
NB. Title capitalization is fixed. Now it reads **Open a Diagram**.
GTK4 only.
> Show something when no diagrams are opened

- gaphor/event.py
- gaphor/ui/diagrams.py
- gaphor/ui/filemanager.py
- gaphor/ui/mainwindow.glade
- gaphor/ui/mainwindow.py
We always show the tab bar. It's better, according to GNOME style guidelines, to hide the tab bar if there's only one tab shown.
However, we want to tell the user which diagram they're editing.
Issue Number: #1955 
The diagram name is shown in the header bar. The tab bar is hidden if only one diagram is opened.
We can also change this to showing the full path.
Updated window name:
I did some cleanup on some of the events, and reduced the state maintained by `MainWindow`.
> Show diagram name in header

- _packaging/use_gtk_4.py
- gaphor/ui/filedialog.py
- gaphor/ui/filemanager.py
- gaphor/ui/selftest.py
- gaphor/ui/tests/test_selftest.py
AppImage crashes when GTK4 is not installed on the system.
This is because it's looking for GSettings schema's only in system folders (e.g. `/usr/share`). Instead it should look in our package (`sys._MEIPASS/share`).
Issue Number: #2015 
Resources are looked up in the right data directory.
> Fix resource lookup for packaged Gaphor

- .github/actions/linux_appimage/action.yml
- gaphor/ui/selftest.py
AppImage does not start because of missing data dirs.
It's not taking into account the `share/` folder in our deliverables.
Follow up of #2016 
Issue Number: #2015
The problem is that we source schema files from 2 locations. Whichever location is copied last copies its `gschemas.compiled` file.
From the docker image:
```
~/jhbuild/install# ls share/glib-2.0/schemas/
gschema.dtd                org.gtk.gtk4.Settings.ColorChooser.gschema.xml  org.gtk.gtk4.Settings.FileChooser.gschema.xml
gschemas.compiled          org.gtk.gtk4.Settings.Debug.gschema.xml
org.gtk.Demo4.gschema.xml  org.gtk.gtk4.Settings.EmojiChooser.gschema.xml
~/jhbuild/install# ls /usr/share/glib-2.0/schemas/
10_gsettings-desktop-schemas.gschema.override …
```
> Another attempt at fixing the packaged data dirs

- docs/style_sheets.md
- gaphor/core/styling/__init__.py
- gaphor/core/styling/declarations.py
- gaphor/core/styling/properties.py
- gaphor/core/styling/tests/test_css.py
- gaphor/core/styling/tests/test_properties.py
If we want to use the same color/line width/... in multiple places, we have to define those explicitly.
Issue Number: #2018
It is now possible to define variables:
```css
* {
--bg-color: rgb(12, 12,12);
--line-width: 2.4;
}
diagram {
background-color: var(--bg-color);
}
association {
line-width: var(--line-width);
}
```
See also https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
Support for default/fallback values has not been implemented. Given our context is quite limited (e.i. we're not making a CSS framework), we can probably do without fallback values.
If variables do not resolve a value from the parent layer is used. E.g. if you provide an invalid variable for color, the default color is used.
> Add support for CSS variables

- gaphor/ui/mainwindow.ui
It seems the create diagram icon is a bit confusing.
Issue Number: #1927
The add-functionality is now a simple `+`. This gives us the freedom to add other elements as well, if we want (like Packages).
> Use normal `+` icon for new diagram dropdown

- gaphor/ui/selftest.py
The macOS/GTK4 tests fail often on the same test: self-test.
Increase the timeout for self-test to 60 seconds.
> Stabilize macOS/GTK4 tests

- gaphor/diagram/tools/dnd.py
- gaphor/ui/styling-gtk4.css
- gaphor/ui/tests/test_treecomponent.py
- gaphor/ui/treecomponent.py
Only one element can be selected in the model browser. 
Issue Number:  #2022
This PR requires #2047.
Also updated drag-between styling (now animates) and padding on tree items (#2053).
Drag source controllers are still attached to the individual rows. Adding it to the ListView resulted in a bad UX: if you wanted to drag an item you had to select it first before it could be dragged.
> Model browser multi select

- gaphor/ui/toolbox.py
Masks incoming modifier state with default mask to ignore additional flags.
Issue Number: #2067
Toolbox shortcuts now work as expected.
> Consider only default modifiers in toolbox shortcuts

- .github/workflows/labeler.yml
This is a workaround for https://github.com/actions/labeler/issues/442, which is causing the labeler action from removing labels that already exist. For example, dependabot adds a skip-changelog label and then labeler removes it.
> Workaround removing skip-changelog labels

- gaphor/C4Model/propertypages.glade
- gaphor/C4Model/propertypages.py
- gaphor/C4Model/propertypages.ui
- gaphor/SysML/propertypages.glade
- gaphor/SysML/propertypages.py
- gaphor/SysML/propertypages.ui
- gaphor/UML/actions/actionspropertypages.py
- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/actions/propertypages.glade
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/classes/associationpropertypages.py
- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/dependencypropertypages.py
- gaphor/UML/classes/enumerationpropertypages.py
- gaphor/UML/classes/propertypages.glade
- gaphor/UML/classes/propertypages.ui
- gaphor/UML/profiles/metaclasspropertypage.py
- gaphor/UML/profiles/propertypages.glade
- gaphor/UML/profiles/propertypages.ui
- gaphor/UML/states/propertypages.glade
- gaphor/UML/states/propertypages.py
- gaphor/UML/states/propertypages.ui
- gaphor/diagram/general/generalpropertypages.py
- gaphor/diagram/propertypages.py
Event handlers "leak" in GTK 4.
Add a function to unsubscribe watchers. It appeared handlers were not properly removed in GTK4, since in GTK4 widgets are not "destroyed", but only use reference counting.
Added a function to `gaphor.diagram.propertypages` to unsubscribe automatically on widget `destroy` (gtk3) or `unparent` (gtk4).
> Properly unsubscribe when property page is removed

- gaphor/UML/actions/partitionpage.py
- gaphor/core/modeling/diagram.py
- gaphor/diagram/copypaste.py
Exceptions are thrown when partitions with actions when more swimlanes are added.
Issue Number: #2138 
Changing partitions may cause actions to be moved around as well, since they should remain in the rigth swimlane.
Now the diagram items are updated as part of changing the swimlanes.
Also fixed the `Diagram.update_now()` interface: matrix-only updates are no longer used.
> Update diagram directly when partitions change

- gaphor/ui/diagrams.py
- gaphor/ui/diagrams.ui
When opening the SysML template, no diagrams are opened, but the tabview is in front. It should show the "Open a diagram" stack page.
Show the "Open a diagram" emblem whenever all diagrams are closed.
> Toggle the "no tabs" background based on notebook activity

- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/propertypages.ui
- gaphor/UML/tests/test_diagramitems.py
- gaphor/diagram/event.py
- gaphor/diagram/general/__init__.py
- gaphor/diagram/general/diagramitem.py
- gaphor/diagram/group.py
- gaphor/diagram/propertypages.py
- gaphor/diagram/propertypages.ui
- gaphor/diagram/tests/test_propertypages.py
- gaphor/diagram/tools/textedit.py
- gaphor/ui/diagrams.py
- gaphor/ui/event.py
- gaphor/ui/modelbrowser.py
- gaphor/ui/tests/test_elementeditor.py
- gaphor/ui/tests/test_handletool.py
- gaphor/ui/tests/test_mainwindow.py
- tests/test_diagram_tools.py
You cannot add a diagram as an element to another diagram, for example to reference it.
Issue Number: #2124 
You can add diagrams to diagrams.
Double clicking the diagram will open it. `F2` can (still) be used to edit the diagram name.
Models can become incompatible due to new presentation item.
* Name editor has been moved to `gaphor.diagram`, so we can also edit diagram names
* `DiagramOpened` event has been moved to `gaphor.diagram.event`, so an open event can be emitted from the diagram tools
> Add diagrams in diagrams

- docs/merge_conflicts.md
- gaphor/core/changeset/compare.py
- gaphor/core/changeset/tests/test_compare.py
- gaphor/storage/mergeconflict.py
- gaphor/storage/tests/test_mergeconflict.py
- gaphor/ui/filemanager.py
- gaphor/ui/modelmerge/organize.py
- gaphor/ui/modelmerge/tests/test_organize.py
- gaphor/ui/modelmerge/tests/test_organize_uml.py
The list of changes in the merge editor is long and not easy to comprehend.
Issue Number: #388 
Instead of comparing the incoming with the current model, the incoming model is compared with a common ancestor node. As a result, the change set only contains the changes made in the incoming branch. Those changes can be applied to the model.
> Merge editor now compare incoming changes with common ancestor commit

- gaphor/SysML/blocks/block.py
- gaphor/SysML/propertypages.py
- gaphor/UML/classes/classespropertypages.py
This PR enables operations on Blocks so that they are visible on the Block shape and in the Property Editor.
Operations and Attributes are hidden on Blocks
Issue Number: #1953 
Operations and Attributes are visible on Blocks
> Make operations visible on Blocks

- .github/workflows/full-build.yml
- _packaging/appimage/jhbuildrc
Updates the AppImage build to the latest GTK4, libadwaita to 1.3, and glib to 2.76.1. I also submitted a bug upstream to glib and turned off glib tests until it is fixed.
> Update AppImage build with GTK 4.10

- gaphor/storage/tests/fixtures.py
Fixes PEP597 encoding warnings caused by no encoding argument specified.
Encoding warnings with PYTHONWARNDEFAULTENCODING=true
No warnings
> Fix encoding warnings for no encoding argument

- gaphor/ui/elementeditor.py
Remove the completion code for now. This is a quick fix/workaround.
Gaphor crashes as soon as you enter something in the CSS editor
Issue Number: #2242
Disable auto-complete for now.
We can do a bugfix release after this change, so Gaphor does not crash.
> A quick fix for crashes in the CSS editor

- docs/conf.py
- gaphor/ui/__init__.py
- gaphor/ui/elementeditor.py
Element editor contains a left-over from the days of GTK 3.
It's been removed and code has been cleaned up.
> Remove GTK3 leftover from element editor

- gaphor/ui/csscompletion.py
- gaphor/ui/elementeditor.py
CSS Completion has been removed due to #2242.
This PR restores the CSS Completion feature. Since I had to apply the changes on 3 places, I decided to separate the GtkSource `CompletionProvider` code and callbacks and the code that provides the proposals.
> Restore CSS completion

- gaphor/__main__.py
- gaphor/main.py
- gaphor/tests/run_script.py
- gaphor/tests/test_main.py
- gaphor/ui/__init__.py
- gaphor/ui/selftest.py
- gaphor/ui/tests/test_main.py
- gaphor/ui/tests/test_selftest.py
- pyproject.toml
Currently command line parsing is done in the UI module. This limits the extensibility (and usability of Gaphor in non-UI environments).
Issue Number: #389
Command line arguments are parsed in `gaphor.main`. The arguments are nicely grouped.
It was also pretty easy to add script execution (I recall it being discussed somewhere). It also opens the door for plugin support: we can provide options to install plugins and list plugins.
```
usage: gaphor [-h] [-v] [-d] [-q] [--exec script] [-p] [--self-test] [--gapplication-service] [model ...]
Gaphor is the simple modeling tool.
options:
-h, --help            show this help message and exit
-v, --version         print version and exit
-d, --debug           enable debug logging
-q, --quiet …
```
> Execute scripts from the command line

- _packaging/gaphor.spec
- gaphor/entrypoint.py
- gaphor/main.py
- gaphor/plugins/diagramexport/exportcli.py
- gaphor/plugins/diagramexport/gaphorconvert.py
- gaphor/tests/test_main.py
- gaphor/ui/__init__.py
- gaphor/ui/tests/test_main.py
- pyproject.toml
- tests/test_diagramexport.py
in #2301 I added an option to execute a script from the command line. However, this approach does not scale.
What I wanted is to say something like `gaphor exec script.py`. This is different from an option, since now we have more control over what arguments are supported.
In the new behavior you can execute `gaphor exec script.py`. This can be extended by `gaphor export` for exporting diagrams, replacing `gaphorconvert`.
```
$ gaphor --help
usage: gaphor [-h] [-V] {exec,export,gui} ...
Gaphor is the simple modeling tool.
options:
-h, --help         show this help message and exit
-V, --version      print version and exit
subcommands (default: gui):
Get help for commands with gaphor COMMAND --help.
{exec,export,gui}
exec …
```
> Diagram export as gaphor CLI subcommand

- gaphor/UML/drop.py
- gaphor/UML/tests/test_drop.py
Messages with one end connected can't be dropped on a diagram
Issue Number: #2304
Dropping of (interaction) messages with only one end connected works.
> Fix drop for messages with one end connected

- gaphor/SysML/blocks/group.py
I was not able to let the properties of "Espresso Machine" (in the coffee machine example) be grouped in an espresso machine. Problem seemed to be that there was an association related to those properties.
Return `True` from the `group()` dispatch function when the property is already owned by the requested parent. This allows the properties to be grouped on their existing owner.
> Allow grouping of property with current owner element

- docs/coffee_machine_concept.md
- examples/coffee-machine.gaphor
- gaphor/SysML/blocks/tests/conftest.py
- gaphor/SysML/propertypages.py
- gaphor/SysML/propertypages.ui
- gaphor/SysML/requirements/tests/conftest.py
- gaphor/SysML/tests/conftest.py
- gaphor/SysML/tests/test_propertypages.py
- gaphor/UML/classes/association.py
- gaphor/UML/deletable.py
- gaphor/UML/deployments/connector.py
- gaphor/UML/deployments/tests/test_connect.py
- gaphor/UML/deployments/tests/test_connector.py
- gaphor/UML/deployments/tests/test_copypaste.py
- gaphor/UML/informationflow.py
- gaphor/UML/interactions/message.py
- gaphor/UML/uml.py
- gaphor/conftest.py
- gaphor/diagram/presentation.py
- gaphor/storage/storage.py
- gaphor/ui/modelmerge/tests/conftest.py
- gaphor/ui/modelmerge/tests/test_organize_uml.py
- models/UML.gaphor
`ItemFlow` can be applied to Connectors, but not Associations.
Issue Number: #2125
Support for `ItemFlow` on Associations.
The Coffee Machine tutorial has been updated as well: https://gaphor--2312.org.readthedocs.build/en/2312/coffee_machine_concept.html#context-diagram.
The editor for item flow now shows as an expander.
> Information Flow for Associations

- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/classes/associationpropertypages.py
- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/enumerationpropertypages.py
- gaphor/diagram/instanteditors.py
- gaphor/diagram/propertypages.py
- gaphor/diagram/tools/tests/test_txtool.py
- gaphor/plugins/console/console.py
- gaphor/plugins/console/consolewindow.py
- gaphor/plugins/errorreports/errorreports.py
- gaphor/ui/appfilemanager.py
- gaphor/ui/elementeditor.py
- gaphor/ui/errorhandler.py
- gaphor/ui/filedialog.py
- gaphor/ui/filemanager.py
- gaphor/ui/greeter.py
- gaphor/ui/help/__init__.py
- gaphor/ui/layout.py
- gaphor/ui/mainwindow.py
- gaphor/ui/statuswindow.py
- gaphor/ui/tests/test_filedialog.py
- gaphor/ui/tests/test_handletool.py
- gaphor/ui/uipreview.py
- tests/test_placement_tools.py
`Gtk.Widget.show()`, `Gtk.Widget.hide()`, and `Gtk.StyleContext.add_class()` are deprecated since GTK 4.10.
Issue Number: #2231 
Replace uses of mentioned methods with newer versions.
> Remove use of deprecated GTK methods

- gaphor/conftest.py
- gaphor/storage/storage.py
- gaphor/storage/tests/test_storage.py
- tests/test_model_consistency.py
Rename all `factory` arguments to `element_factory`, so the naming is in line with the rest of the app.
> Use consistent naming for element_factory in storage module

- .github/workflows/full-build.yml
This PR replaces using a PyPI token with the new trusted publisher feature. I also removed the skip check action since I haven't seen it actually skipping any runs.
> Enable PyPI trusted publisher

- gaphor/UML/states/propertypages.ui
- gaphor/plugins/errorreports/errorreports.ui
- gaphor/ui/mainwindow.ui
It appeares that using "yes" is a common practice for translatable strings in GNOME apps.
> UI: Mark translatable strings yes

- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/actions/parameter.ui
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/actions/tests/test_activitypropertypage.py
- gaphor/ui/styling.css
- gaphor/ui/treeitem.ui
`Gtk.TreeView` is deprecated. GTK 4 has a much nicer tree widget: `Gtk.ListVIew`. It's already used for the model browser. We should also use it in the property editor, for both consistency and ease of use.
`Gtk.ListView` has no header. This will be [introduced in GTK 4.12](https://docs.gtk.org/gtk4/property.ListView.header-factory.html). So we may want to postpone changing to `ListView`s.
> Replace deprecated Gtk.TreeView with ListView: Activity Parameter Nodes

- gaphor/ui/elementeditor.ui
- gaphor/ui/styling.css
Issue Number: #2359 
The editor panes for settings and the merge editor are wider now.
I could not make it work with a `GtkPaned`, so I just changed the width a little. The settings part is also changed, so it's easier to edit style sheets.
Before:
After:
> Make style sheet and merge editor panel wider

- _packaging/gaphor.spec
I noticed Tk(Inter) is bundled with our app. That makes no sense.
Nothing changed. TkInter has been excluded.
See https://github.com/pyinstaller/pyinstaller/wiki/Recipe-remove-tkinter-tcl
Also, there's no need for Gaphas dist-info, so that's also removed.
> Do no longer package TkInter

- .github/workflows/full-build.yml
- .gitignore
- docs/index.rst
- docs/plugins.md
- docs/style_sheets.md
- gaphor/main.py
- gaphor/plugins/__init__.py
- test-plugin/gaphor_test_plugin.py
- test-plugin/pyproject.toml
- tests/test_plugins.py
When Gaphor is packaged as Window exe or in a macOS app, there's no way to add extra functionality to the app.
Issue Number: #389
Gaphor can load and initialize services defined in a separate plugins folder (`$HOME/.local/gaphor/plugins-2` by default). This location can be overridden by an environment variable `GAPHOR_PLUGIN_PATH`.
This PR contains the working parts -- loading of plugins -- from #2353.
Plugin installation and maintenance is a lot harder can cannot be done from within Gaphor at the moment. This should be fixed in a future PR.
> Load plugins installed in plugin folder

- gaphor/core/modeling/event.py
- gaphor/core/modeling/properties.py
- gaphor/services/tests/test_undomanager.py
- gaphor/services/undomanager.py
Issue Number: #2366
The index of an element deleted from an association is recorded, so it can be placed
back on the same index when it was deleted.
> Fix order when undoing deletion from association

- gaphor/UML/actions/flowconnect.py
- gaphor/UML/actions/tests/test_flowconnect.py
Resolve issue #2278 - object flow cannot connect to fork node.
Issue Number: #2278
Flow nodes can now connect to fork nodes.
> Allow Object Flows to Connect to Join/Fork Nodes

- gaphor/SysML/blocks/connectors.py
- gaphor/SysML/blocks/tests/test_connectors.py
- gaphor/SysML/propertypages.py
- gaphor/SysML/propertypages.ui
- gaphor/SysML/tests/test_propertypages.py
Ports can be attached to properies but end up at toplevel in the model browser.
Issue Number: #2368 
* Properties can be assigned a proper type, like we do for `ItemFlow` and `Partition`.
* Ports can be attached to properties with a type assigned.
> Fix ports on properties

- gaphor/UML/actions/tests/test_flowconnect.py
- gaphor/plugins/console/consolewindow.py
- gaphor/ui/abc.py
- tests/test_action_issue.py
The UIComponent interface still advertizes a `ui_name` and `size` property. Both are not in use anymore.
Cleaned interface.
Updated the last tests that use test classes to functions.
> chore: clean up deprecated properties from UIComponent

- gaphor/SysML/blocks/proxyport.py
- gaphor/UML/actions/activity.py
- gaphor/UML/actions/pin.py
- gaphor/UML/interactions/executionspecification.py
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/stylesheet.py
Elements such as Parameters and Execution Specifications have a white background when used with dark mode.
Issue Number: #2437
The background color of overlaying elements changes with the color scheme.
Light mode:
Dark mode:
> Fix Parameter Node and Execution Specification with Dark mode

- .github/actions/setup_and_test/action.yml
- CHANGELOG.md
- po/build-babel.py
- pyproject.toml
Proposal for closing #2346.
- For all pre-releases, we build mo files for all translations
- For releases, we only create mo files for a subset (cs, es, de, nl, fi, hr, hu, and ru). These are the languages that are majorly complete, and we can add additional ones to the list as they progress. It isn't automatic, but shouldn't require too much maintenance.
All translations are used, even if only a few strings are translated
Issue Number: #2346
Only mature translations are used for release versions of Gaphor
> Only use mature translations for release

- .github/workflows/full-build.yml
This PR reverts commit e0cfee5e9a376aa5e21418d1103ecc19da584772, and moves back to the previous version of adwaita-icon-theme until we resolve why icons are showing up in Windows.
Toolbar icons are missing in Windows
Issue Number: #2448 
They are restored
> Windows: Fix missing toolbar icons

- gaphor/core/styling/__init__.py
- gaphor/core/styling/tests/test_cascading.py
Rendering throws exception when an element with a solid background is on the diagram
In #2439 we introduced variables for the background color, so solid items could change the background color in dark mode.
Issue Number: #2452
CSS variables are evaluated before font-size and color (with opacity) is finally calculated.
> Fix: resolve CSS style variables before using the values

- docs/getting_started.md
This PR extends the Model Preferences section in the Getting Started guide of the documentation with explanations of the current options.
Model Preferences are currently not explained, including what the expected behavior of the language selector is. 
Issue Number: #2461
Added explanations of the current options.
> Extend model preferences section in getting started guide

- gaphor/__init__.py
- gaphor/tests/test_version.py
Most libraries have a `__version__` attribute that contains the library version.
Since Gaphor is also a library, it seems reasonable to support a `__version__` in our toplevel module:
```python
>>> import gaphor
>>> gaphor.__version__
'2.19.3'
```
> Support `gaphor.__version__`

- gaphor/ui/modelbrowser.py
Double clicking on `<Relationships>` node causes an error.
Issue Number: Fixes #2449
Do not open nodes like `<Relations>`.
> Only open model browser elements with a model element

- gaphor/SysML/blocks/block.py
When drawing the operations compartment in Blocks, it was missing the top separator.
Top separator was missing
Top separator is restored
> Fix operations in Blocks missing top separator

- gaphor/SysML/blocks/proxyport.py
- gaphor/SysML/propertypages.py
- gaphor/SysML/propertypages.ui
- gaphor/SysML/tests/test_propertypages.py
Type of proxy ports is not shown
Issue Number: Fixes #2424
ProxyPort type is now shown if the "show-type" property is set.
> Toggle visibility of ProxyPort.type

- gaphor/ui/tests/test_modelbrowser.py
- gaphor/ui/treemodel.py
When you delete an element, the parent node in the model browser collapses (closes).
Issue Number: fixes #2488
Tree view does not collapse the node when an element changes inside.
> Tree view should not collapse when an element is deleted

- gaphor/UML/sanitizerservice.py
- gaphor/UML/tests/test_sanitizerservice.py
- tests/test_package_removal.py
This PR fixes a bug that would allow for large portions of the model to be deleted if the last presentation of the owning Package was deleted.
If the Remove Unused Elements option is selected, and you delete the last usage of a Package that has children like a package or activity, all the children are also deleted.
Issue Number: #2181 
Packages with children aren't removed automatically.
> Do not remove unused Packages with childen

- gaphor/UML/actions/__init__.py
- gaphor/UML/actions/action.py
- gaphor/UML/actions/actionspropertypages.py
- gaphor/UML/actions/actionstoolbox.py
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/actions/tests/test_callbehaviouraction.py
- gaphor/UML/uml.py
- gaphor/UML/umlfmt.py
- gaphor/ui/icons/hicolor/scalable/actions/gaphor-call-behavior-action-symbolic.svg
- models/UML.gaphor
> Add CallBehaviorAction

- gaphor/UML/tests/test_umlfmt.py
- gaphor/UML/umlfmt.py
When the name of a pin is changed, the change is not reflected in the model browser.
A Pin is also a MultiplicityElement, and that's how it's formatted.
Issue Number: fixes #2487 
Pin name is shown in the model browser.
> Format pins by their name

- poetry.lock
The build is currently failing due to a PyYAML issue caused by a Cython 3.0 release. This issue is being tracked today at https://github.com/yaml/pyyaml/issues/724 and a quick PR and release was made. Version 6.0.1 of PyYAML is now out that fixes the issue. This PR updates our depenencies.
Gaphor builds are failing.
They are passing :rocket:
> Fix dependency error by upgrading PyYAML

- gaphor/diagram/propertypages.py
- gaphor/diagram/propertypages.ui
- [ X] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [ X] I have read, and I understand the GNOME [Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)
Checkbox is displayed instead of a switch, making the UI inconsitent.
Issue Number: 2489
Replaced checkbox with switch, making the UI consistent.
> Replaced GtkCheckButton with GtkSwitch

- gaphor/SysML/propertypages.py
The state 'Show values' of a SysML block is not applied in properties page.
Issue Number: 2511
It is applied as expected.
> Providing value for 'Show value' in properties page

- gaphor/SysML/blocks/blockstoolbox.py
- gaphor/UML/classes/association.py
- gaphor/UML/classes/classconnect.py
- gaphor/UML/classes/classestoolbox.py
- gaphor/ui/icons/hicolor/scalable/actions/gaphor-direct-association-symbolic.svg
Direct association between classes and sysml blocks.
Currently it is very painful to create a direct (navigable) association. A normal association must be created, then going into properties, finding the tail element, and setting navigability. It takes just too much time.
Issue Number: 2516
A new toolbar button is added enabling the same outcome with a single click. 
I could not find how to properly do the translations so I need some help in that.
> Direct association

- docs/conf.py
- docs/modeling_language.md
- gaphor/UML/actions/copypaste.py
- gaphor/UML/actions/tests/test_copypaste.py
- gaphor/UML/tests/test_copypaste.py
- gaphor/diagram/copypaste.py
- gaphor/diagram/propertypages.py
- gaphor/diagram/tests/fixtures.py
- gaphor/diagram/tests/test_copypaste.py
- gaphor/diagram/tests/test_copypaste_full.py
- gaphor/diagram/tests/test_copypaste_grouping.py
- gaphor/diagram/tests/test_copypaste_link.py
- gaphor/ui/copyservice.py
- gaphor/ui/tests/test_copyservice.py
- tests/test_model_consistency.py
- tests/test_multiple_associations.py
Packages are only copied as is, without content.
Diagrams can be put on a diagram, and they can be copied. However, the contents of the diagram is not copied.
This is especially useful if you copy content between models.
Issue Number: #2422
* Elements are copied with their owned elements. So if you copy a package and do a full paste, the element and all owned elements are copied.
* Diagrams copy the elements in the diagram. You can now copy a diagram (from a diagram) and full-paste it. This will result in a copy of the diagram
* Update Modeling language docs with the (new) copy/paste interface and did some general improvements as well.
Cleaned up the copy and paste interfaces.
Copying is now done via the `copy_full()` function. This function …
> Deep copy for packages and diagrams

- gaphor/diagram/group.py
- gaphor/diagram/tests/test_group.py
Currently an exception is raised when you drag elements from one session and drop them in the model browser of another session
Issue Number: #2504
This PR fixes the exception by explcitly checking if elements are part of the same model.
To support DnD between models we need to use the internal copy functionality. But for that the copy functionality should be improved, as described in #2422.
> Allow only changing element ownership in the same model

- gaphor/UML/actions/actionspropertypages.py
- gaphor/UML/actions/pin.py
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/tests/test_umlfmt.py
- gaphor/UML/umlfmt.py
- poetry.lock
Add ability to set the pin type and multiplicity.
Pin types and multiplicities cannot be set for a particular pin.
Issue Number: #2485 
When selecting a pin a properties panel is displayed where the type and multiplicity of the pin can be set. The modification is displayed on the diagram and in the tree as well.
> Pin type multiplicity

- gaphor/diagram/tools/placement.py
So you cannot accentally drop another new item on the wrong parent.
To reproduce:
1. Open a diagram
2. hit `c` (for Class)
3. place class on the diagram (left-click)
4. While the instant editor is up, move the mouse cursor to a different place on the diagram
5. Close the instant editor by hitting `Enter`
6. hit `c` (for Class)
7. place class on the diagram (left-click)
8. See the new class being placed as a child of the first class
Item is no longer a dropzone item after placement.
> Ensure a newly placed item is no longer a dropzone item.

- gaphor/UML/copypaste.py
- gaphor/UML/tests/test_copypaste.py
- models/UML.gaphor
This is a follow-up PR on #2475 
Issue Number: #2536, #2475
Do not error if we copy complex structures.
> Avoid copy cycles when fully pasting diagram items

- gaphor/C4Model/iconname.py
- gaphor/SysML/__init__.py
- gaphor/SysML/diagramlabel.py
- gaphor/SysML/iconname.py
- gaphor/SysML/sysml.py
- gaphor/SysML/tests/test_diagramlabel.py
- gaphor/SysML/toolbox.py
- gaphor/UML/iconname.py
- gaphor/diagram/diagramlabel.py
- gaphor/diagram/diagramtoolbox.py
- gaphor/diagram/iconname.py
- gaphor/diagram/painter.py
- gaphor/ui/modelbrowser.py
- gaphor/ui/toolbox.py
- gaphor/ui/treemodel.py
- models/SysML.gaphor
* Adds SysMLDiagram which extends regular Diagram
* Adds diagram type specific header formatting
* All SysML diagrams created under SysML profile (modeling language) will be created as SysMLDiagram and treated as such throughout the model.
Issue Number: #2444
As a follow-up, it may be good to also have "refactor" option for regular diagrams which should be SysML diagrams.
This change and the ability to differentiate SysML diagrams opens up a large possibility to address SysML specific constraints and defaults more gracefully.
> Support SysMLDiagram type and diagram type specific header formatting

- docs/stereotypes.md
Added more explicit instructions for creating a profile package within sysML to the stereotype documentation
- [ x] Documentation content changes
The use of stereotypes to create a new profile is more explicit.
> Update stereotype docs

- gaphor/SysML/propertypages.py
- gaphor/SysML/propertypages.ui
- gaphor/SysML/tests/test_propertypages.py
- gaphor/UML/interactions/interactionspropertypages.py
- gaphor/UML/interactions/lifeline.py
- gaphor/UML/interactions/propertypages.ui
- gaphor/UML/interactions/tests/test_interactionspropertypages.py
- gaphor/UML/propertypages.py
- gaphor/UML/propertypages.ui
- gaphor/UML/uml.py
- gaphor/diagram/propertypages.py
- models/UML.gaphor
Lifelines cannot have a type
Issue Number: #2514
Be able to select a type (`ConnectableElement`) and show it on the element.
A lifeline represents a ConnectableElement, however, Classifiers are not connectable elements, except for Interface, Prpoerty and Parameter. Not sure how to assign a Block to a Lifeline.
> Type selection for Lifelines

- .github/scripts/metadata.sh
- .github/workflows/full-build.yml
- .github/workflows/hypothesis-test.yml
- gaphor/entrypoint.py
- poetry.lock
- pyproject.toml
Fix some odds and ends:
* test step labels
* improve hardening rules
* Bump minimal Python version to 3.10
* Update certifi, fixing a security vulnerability.
> Pipeline maintenance, require Python 3.10+

- gaphor/SysML/diagramtype.py
- gaphor/SysML/tests/test_diagramtype.py
- gaphor/SysML/toolbox.py
- gaphor/diagram/diagramtoolbox.py
- gaphor/ui/modelbrowser.py
- gaphor/ui/toolbox.py
Allows creating diagrams in SysML profile such that they conform with the specification. This is achieved through showing new diagram creation options which are legal; or have a default defined which would autocreate necessary element which can contain the diagram.
Issue Number: #2544
https://github.com/gaphor/gaphor/assets/45357878/1998239b-2f38-4234-b207-dc0fb8b2bff4
Once this gets accepted, #2544 can be resolved.
A known issue with this solution is that it is still possible to drag the diagrams around and create a configuration of the model where they are not conforming with the standard.
> Constrain SysML diagram creation in the model explorer to conform with SysML 1.6 specification

- CHANGELOG.md
- gaphor/SysML/requirements/requirementstoolbox.py
- gaphor/ui/icons/Makefile
- gaphor/ui/icons/hicolor/scalable/actions/gaphor-derive-reqt-symbolic.svg
- gaphor/ui/icons/stencil.svg
* Changed icon id in stencil.svg derive → derive-reqt
* Ran makefile to re-generate icons from the stencil
* Made necessary changes in hardcoded icon paths in requirementstoolbox
The bug most probably originated by a previous makefile run removing derive-reqt icon because it was not in the stencil.
Issue Number: https://github.com/gaphor/gaphor/issues/2622
> Fix derive-reqt modelbrowser icon

- gaphor/SysML/toolbox.py
Interface blocks cannot be added using the elements creation feature in the tree.
Issue Number: #2606 
Interface blocks can be added using the elements creation feature in modeling tree.
> Add interface block to element creation menu

- gaphor/SysML/blocks/block.py
This is a follow-up to #2628 that ensures references are displayed as well as parts. Closes #2613.
Shared associations are shown as parts
Issue Number: #2613
Shared associations are shown as references
> Fix blocks not showing references

- gaphor/diagram/propertypages.py
- gaphor/diagram/propertypages.ui
The type of the selected element is not visible. 
Issue Number: #2607 
The type of the selected element is displayed in the properties panel.
> Display type of element in the properties panel

- .coveragerc
- gaphor/UML/interactions/lifeline.py
- gaphor/UML/states/pseudostates.py
- gaphor/abc.py
- gaphor/babel.py
- gaphor/storage/tests/test_storage_upgrades.py
- gaphor/ui/diagrams.py
- gaphor/ui/macosshim.py
Ignore parts that are never executed, such as protocols, overloaded and abstract methods.
Make use of tuples in `for ... in (...)` statements consistent.
> Improve coverage reporting

- gaphor/SysML/__init__.py
- gaphor/SysML/sysml.py
- gaphor/SysML/sysmlfmt.py
- gaphor/SysML/tests/test_sysmlfmt.py
- models/SysML.gaphor
Relationships like Trace, DeriveReqt end up in the Model  Browser root.
Issue Number: fixes #2621 
This fixes those requirement relations to end up in the root of the model.
Not sure if we want this relationship on the source or target side. I choose target for now.
I also added a format function (not shown on screenshot).
> Add ownership rules to DirectedRelationshipPropertyPath.targetContext

- gaphor/UML/toolbox.py
When user wants to add a new stereotype to the model in the model browser a profile is being created.
Issue Number: #2606 
A stereotype is created as expected.
> Fixed Profile is created instead of Stereotype in model browser

- CHANGELOG.md
- gaphor/UML/states/propertypages.py
- gaphor/UML/states/propertypages.ui
- gaphor/UML/states/tests/test_propertypages.py
Adds drop-down selection to select entry, exit, do behaviors amongst the existing behaviors.
Currently, a textfield is used to define entry, exit, do behaviors which always create new activities. It is not possible to select existing activities.
Ideally, I would like to preserve the option to create the behavior when it does not exist on the property page; or defer its creation at the later point and just keep it as a text.
> Support state entry, exit, do behavior selection amongst the existing behaviors via dropdown

- gaphor/UML/tests/test_uml2_overrides.py
- gaphor/UML/umloverrides.py
Issue Number: Fixes #2673
Only unique elements are returned.
> Remove duplicated elements in Component.provided property

- docs/style_sheets.md
Fixes a misspelling of the word `generalization` in the style sheets documentation.
In the `Supported selectors` section of the style sheets documentation, `generalization` is misspelled as `generaliation`.
> Fix style sheets docs spelling error

- gaphor/UML/uml.py
- gaphor/ui/modelbrowser.py
- gaphor/ui/tests/test_modelbrowser.py
- gaphor/ui/tests/test_treemodel.py
- gaphor/ui/treemodel.py
- models/UML.gaphor
When an association end is marked as non-navigable, it ends up in the root of the Model Browser.
Issue Number: Fixes #2731
Next to `Element.owner`, `NamedElement.memberNamespace` (/`Namespace.member` is used as a fallback to place an element in the Model Browser.
This should reduce the cases where an element ends up in the root of the model unintended.
After a discussion with @marek-piirikivi on Matrix, we decided it's probably better to support membership in the model browser. The alternatice was to rework how Associations are modeled (#633), but that will become a messy change.
> Members in model browser

- .github/workflows/full-build.yml
This PR changes from using the default Ubuntu runner on GitHub Actions to using Fedora 39. :star_struck:  This allows us to have more recently released versions of GTK and related dependencies to test against, and should unblock #2756 and #2320.
Additionally, I dropped the Python 3.10 build since Python 3.12 is now released.
Linux tests are run on Ubuntu 22.10
Linux tests are run on Fedora 39
I initially tried to use a Ubuntu 23.10 image, but I ran in to a lot of problems installing the different versions of Python using the deadsnakes PPA. Ubuntu disables ensurepip and pip wasn't working outside a virtualenv. Fedora was much smoother to get going.
> Build on CI with a Fedora 39 image

- poetry.lock
- pyproject.toml
This PR reverts the update to PyInstaller 6.1.
The build is failing due to a breaking change in PyInstaller 6.x
Builds passes
We'll have to fix the install scripts as a follow up.
> Revert update to PyInstaller 6.1

- .pre-commit-config.yaml
- gaphor/SysML/blocks/block.py
- gaphor/SysML/blocks/interfaceblock.py
- gaphor/SysML/blocks/property.py
- gaphor/SysML/requirements/requirement.py
- gaphor/UML/classes/association.py
- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/component.py
- gaphor/UML/classes/enumeration.py
- gaphor/UML/classes/interface.py
- gaphor/UML/classes/klass.py
- gaphor/UML/classes/stereotype.py
- gaphor/UML/deletable.py
- gaphor/UML/deployments/artifact.py
- gaphor/UML/deployments/node.py
- gaphor/codegen/coder.py
- gaphor/diagram/general/metadata.py
- gaphor/diagram/presentation.py
- gaphor/diagram/text.py
- po/check-babel.py
- pyproject.toml
Ruff format is now in beta and seems to be working well. It provides formatting as a drop-in replacement for Black. Ruff also has built-in pyproject.toml checking, so I removed the check toml hook. Finally, Ruff has some of the rules for refurb included, and will get more over time.
The speed advantage of minimizing pre-commit hooks besides Ruff and mypy is significant.
Black for code formatting
Ruff format for code formatting
> Replace Black, check toml, refurb with Ruff

- .github/actions/macos_dmg/action.yml
- .github/workflows/full-build.yml
Fixes #2781.
altool is used for notarization using GitHub Actions
Use notarytool and stapler directly.
> Upgrade notarization from altool to notarytool

- .github/workflows/full-build.yml
- _packaging/gaphor.spec
- _packaging/windows/versionfile_metadata.yml
- _packaging/windows/win_installer.nsi
- poetry.lock
- pyproject.toml
This PR updates PyInstaller. It required a minor change to tell the NSIS installer where the LICENSE file was located. Version 6.x of PyInstaller includes a clean directory structure and hides all the files but the exe in an _internal folder.
All the install files for Gaphor are in the same directory.
Only the icon and the exe are presented to the user in the installation directory
> Update PyInstaller to version 6.1

- gaphor/ui/help/__init__.py
Links in the About dialog on macOS are not opened
Issue Number: #2798
Open the links ourselves, since we cannot rely on D-Bus.
> Fix About dialog links on macOS

- .github/workflows/full-build.yml
This PR updates Gvsbuild to version 2023.11.0, which includes libadwaita 1.4.0 along with other updates.
Unable to use the newest features in libadwaita
Latest version of libadwaita is on all platforms
> Windows: Use libadwaita 1.4.0

- CHANGELOG.md
- gaphor/SysML/blocks/connectors.py
- gaphor/SysML/drop.py
- gaphor/SysML/tests/test_drop.py
- gaphor/SysML/toolbox.py
- gaphor/ui/icons/Makefile
- gaphor/ui/icons/hicolor/scalable/actions/gaphor-proxy-port-symbolic.svg
- gaphor/ui/icons/stencil.svg
I added additional check to see if there exists an item on the diagram that may own the proxy port.
Issue Number: #2612
Additionally fixed proxy port drag icon. Automatically generated icon name is "proxy-port".
> Proxy Port Improvements

- _packaging/gaphor.spec
Small updates to the spec file:
1. Fix PEP 597 encoding error
2. Remove an unused import
3. Remove a version check, since all builds of Gaphor should be with Python 3.11+.
Encoding warnings during CI/CD pipeline runs
Fewer warnings
> PyInstaller Spec File Updates

- .github/workflows/full-build.yml
Currently, when pushing a branch and opening a PR, GitHub Actions runs two complete builds. This PR tries to reduce duplicate runs by only running the full build when:
1. A PR is opened against the main branch
2. Push to the main branch
3. On release
4. On manually trigger a build with workflow dispatch from the actions menu
The tradeoff of this will be that if you want to run GitHub Actions, you'll need to open a draft PR or manually start it from the Actions tab, since pushing to a branch will not start a run.
I also added logic to cancel running previous workflows using concurrency.
2 full builds for each push of a PR
Avoid duplicate builds under most circumstances
> Reduce duplicate GitHub Action runs

- gaphor/ui/diagrampage.py
Issue Number: #2860 
Clear event handler when the diagram widget(s) are destroyed.
> Fix TypeError when changing to dark mode

- gaphor/i18n.py
- gaphor/settings.py
- gaphor/ui/__init__.py
- gaphor/ui/help/__init__.py
- gaphor/ui/help/preferences.ui
- gaphor/ui/tests/test_help.py
If a preferred color scheme is selected, it's not set when you (re)start the application.
I made the Settings object a more rich object and moved many of the settings there. This makes the interface we have to use easier (no optional `None` object).
Changed the message that settings cannot be loaded to warning, so it's shown before the logging module is configured.
The application color scheme is updated according to the setting in a reactive fashion.
> Settings cleanup

- org.gaphor.Gaphor.json
When opening the project with Builder and trying to run it, the build is failing due to the wrong path for the gschema settings definition.
Build fails due to file not found
Build passes and project runs.
> Fix wrong path in project flatpak manifest

- gaphor/ui/copyservice.py
An error message is written when a user tries to paste from an empty clipboard.
Issue Number: #2737
The exception is caught.
Do no longer confuse users.
> Catch errors when a clipboard is empty

- gaphor/diagram/group.py
- gaphor/diagram/tests/test_group.py
In the model browser, elements cannot be dragged to the model root.
Issue Number:  #2734
Elements can be dragged to root.
> Fix grouping: allow to group to "root"

- .github/actions/install/action.yml
- .github/workflows/full-build.yml
My [pipx improvement](https://github.com/pypa/pipx/pull/1002) to use pylauncher to get the Python version from earlier in the year was released in pipx 1.3. This allows us to have common code to install using pipx, but also broke the build in Linux because the Linux runners have pylauncher and we weren't using the `--python 3.12` syntax needed.
Linux build is failing
Linux build is passing
> Fix pipx install error in Linux

- .github/labeler.yml
- .github/workflows/labeler.yml
The labeler action updated to v5 which was a breaking change. It passed the tests here:
https://github.com/gaphor/gaphor/actions/runs/7093586044
Labeler action has broken the build
The build passes now
> Update labeler to be compatible with v5 release

- .github/actions/install/action.yml
- .github/workflows/full-build.yml
The macOS build fails when installing dependencies with an error:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.12
Target /usr/local/bin/2to3-3.12
already exists. You may want to remove it:
rm '/usr/local/bin/2to3-3.12'
```
Pipx is said to be pre-installed on all runners. Although it doesn't seem to work on all.
It looks like the WIndows runner is dependent on python-launcher.
For macOS we do not need that per se. Hence I removed it and just changed the python version so it matches the old style (`python3.12`).
> Fix macOS build

- gaphor/ui/help/preferences.ui
- gaphor/ui/mainwindow.py
- gaphor/ui/mainwindow.ui
- gaphor/ui/notification.py
- gaphor/ui/tests/test_notifier.py
We've been using old-skool in-app notifications till now. The Preferences window already uses toasts.
Issue Number: #2760
We use toasts :)
> Replace in-app notificatins by Adwaita Toasts

- gaphor/UML/actions/propertypages.ui
- gaphor/UML/classes/propertypages.ui
- po/ca.po
- po/cs.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/gaphor.pot
- po/gl.po
- po/hr.po
- po/hu.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sl.po
- po/sv.po
- po/ta.po
- po/tr.po
- po/zh_Hans.po
The Info icon for help is not showing.
Replaced by `ⓘ`. Now it shows
Should check if it looks okay on Linux and Windows too.
> Update ⓘ icon, so it also shows on macOS

- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/actions/parameter.ui
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/actions/tests/test_activitypropertypage.py
- gaphor/ui/__init__.py
- gaphor/ui/modelbrowser.py
- gaphor/ui/styling.css
- gaphor/ui/tests/test_modelbrowser.py
- gaphor/ui/tests/test_treemodel.py
- gaphor/ui/textfield.py
- gaphor/ui/treeitem.ui
- gaphor/ui/treemodel.py
- gaphor/ui/treesearch.py
**This PR should only be merged if we're sure it does not cause any crashes.**
The Activity Parameter property page had been reverted to `Gtk.TreeView`, since the `Gtk.EditableLabel` caused the app to crash.
Issue Number: #2433 
We want to get rid of deprecated API's.
`Gtk.EditableLabel` exposes some behavior that we currently have differently (e.g. the text should not change to editable state when a row is selected, only after a double click).
We have a new widget: `TextField`, that contains the text edit logic we use in the model browser. This widget looks more stable and works for the Parameter ListView too.
Added a placeholder text to the Parameter table, so it's more clear what a user can do in the box:
> Reapply #2329 - Gtk.ListView for Activity Parameters

- gaphor/ui/diagrampage.py
`Gtk.CssProvider.load_from_data` is deprecated in GTK 4.12:
```
gaphor/ui/tests/test_handletool.py::test_iconnect
/Users/arjan/Development/gaphor/.venv/lib/python3.11/site-packages/gi/overrides/Gtk.py:1641: DeprecationWarning: Gtk.CssProvider.load_from_data is deprecated
super(CssProvider, self).load_from_data(text, length)
```
Issue Number: #2231
Replace by `Gtk.CssProvider.load_from_string`.
However, this API is introduced in GTK 4.12.
GTK 4.12+ is required once this change is merged.
> Replace deprecated use of CssProvider.load_from_data

- gaphor/ui/styling-macos.css
- gaphor/ui/styling.py
The Adwaita theme draws a wide shadow around the window. This shadow is part of the view on macOS.
You can see this easily when you open a file. The parent window is overlayed with a "sheet":
The shadow has been tweaked to look more like a macOS shadow, and the shadow size is smaller. This improves the usability: the big (invisible) border is gone, so if you click on an underlying window, it will actually work.
Also the shadow looks a bit more mac-like:
GTK issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/6255
> Less padding around windows on macOS

- gaphor/ui/styling-box-shadow.css
- gaphor/ui/styling.py
As discussed in #2952, the shadow for macOS is very wide, and the shadow is drawn as part of the `NSView`, hence mouse clicks are consumed.
The same issue appears on Windows.
Update the window shadow style for both macOS and Windows.
The shadow style is now resembling the default shadow style in GTK.
I found that `CssProvider.load_from_path()` does not cascade, so only the shadow styling was loaded. This has been fixed.
> Apply custom window shadow to macOS and Windows

- gaphor/diagram/general/generalpropertypages.py
- gaphor/ui/appfilemanager.py
- gaphor/ui/filedialog.py
- gaphor/ui/tests/test_filedialog.py
- po/ca.po
- po/cs.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/gaphor.pot
- po/gl.po
- po/hr.po
- po/hu.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sl.po
- po/sv.po
- po/ta.po
- po/tr.po
- po/zh_Hans.po
Issue Number: #2231 
Use the modern `FileDialog` API.
Not sure if it's still using the native dialogs on Windows and macOS.
`Gtk.FileDialog` is introduced in GTK 4.10. ~We're still building on 4.6 (Ubuntu 22.04). 
I think we can wait until we have GTK 4.10+ available on our build machines.~
> Replace deprecated Gtk.FileChooser by FileDialog

- gaphor/UML/actions/activity.py
- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/actions/tests/test_activitypropertypage.py
- gaphor/UML/classes/associationpropertypages.py
- gaphor/UML/propertypages.py
Types cannot be defined on parameter nodes
Issue Number: #2482
Types are supported.
@sz332 Should the direction be visible in the diagram as well (similar to `Show Type`)?
Update: direction can be toggled.
> Add types for parameters

- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/classes/associationpropertypages.py
- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/enumerationpropertypages.py
- gaphor/UML/classes/propertypages.ui
- gaphor/UML/classes/tests/test_associationpropertypages.py
- gaphor/UML/profiles/propertypages.ui
- gaphor/UML/profiles/stereotype-cell.ui
- gaphor/UML/profiles/stereotype-name-cell.ui
- gaphor/UML/profiles/stereotype-value-cell.ui
- gaphor/UML/profiles/stereotypepropertypages.py
- gaphor/UML/profiles/tests/test_stereotypepage.py
- gaphor/UML/profiles/tests/test_stereotypepropertypages.py
- gaphor/UML/propertypages.py
- gaphor/UML/recipes.py
- gaphor/UML/text-field-cell.ui
- gaphor/ui/styling.css
- test-models/stereotypes.gaphor
Issue Number: #2231 , #2155
Stereotype property page is using `Gtk.ColumnView`, the modern alternative to `Gtk.TreeView`.
The stereotype view is somewhat simplified (no expander buttons). I expect this will work, as long as there are not too many stereotypes applicable for an element. Values for unapplied stereotypes are insensitive.
* fix removal of "Show Stereotypes" option.
* Reworked all `ColumnView` property editors to start editing on the `activate` signal (double-click or <kbd>Enter</kbd>).
> Convert Stereotype property editors to ListView

- gaphor/ui/tests/test_modelbrowser.py
- gaphor/ui/treemodel.py
When creating a stereotype, a ghost/rogue element appears at the root of the model browser.
Issue Number: #2987
When removing an element, remove it both from the `owner` and from the `memberNamespace` branches in the model browser.
> Remove both owner and memberNamespace in model browser

- gaphor/UML/actions/partition.py
- gaphor/UML/classes/tests/test_class.py
- gaphor/core/modeling/properties.py
- gaphor/diagram.css
- gaphor/diagram/shapes.py
Any item with a Box shape and no children, does not draw.
This goes for Swimlanes (partitions), but also rectangles.
Issue Number: #2988 
Swimlanes are shown again.
> Fix swimlanes

- .github/actions/install/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/full-build.yml
- .github/workflows/hypothesis-test.yml
Currently, pipx is failing on CI due to a bug with version 1.4.1. This PR removes use of pipx to straight pip install poetry in the current environment.
CI builds are failing due to a pipx not passing the correct path to Python.
CI builds are passing.
> Remove use of pipx in CI

- .github/workflows/full-build.yml
- .github/workflows/hypothesis-test.yml
Alternative for #3014 
We use Xvfb for testing in CI
Use Mutter instead: Wayland has the future.
> Run Linux tests on Mutter, instead of Xvfb

- CHANGELOG.md
- gaphor/core/modeling/collection.py
- gaphor/core/modeling/tests/test_style_attributes.py
- pyproject.toml
This PR fixes a TypeError when trying to look up an attribute for a collection type caused by the class missing a `__hash__` definition. This was causing some models to fail to load. I also added two tests, one to test a passing example of a `attrname` lookup, and a 2nd that was failing with a collection object and is now passing.
Some models are failing to load
Issue Number: #2995
Models successfully load
> Fix models failing to load for collection not hashable TypeError

- CHANGELOG.md
- gaphor/ui/filedialog.py
Image filters were not shown.
Image filters are shown.
> Fix file filters for image export dialog

- .github/workflows/full-build.yml
I noticed during the last two releases, that the dispatch action is failing to update the flatpak due to a no matching distribution error. When I restart the workflow it immediately passes, so I think PyPI needs a little time to sync the publish operation. This PR adds a wait time before running the workflow.
Dispatch workflow is failing, see https://github.com/flathub/org.gaphor.Gaphor/actions/runs/7521064978/attempts/1
Dispatch should pass
> Fix no matching distribution right after publish

- gaphor/SysML/blocks/proxyport.py
- gaphor/SysML/relationships.py
- gaphor/UML/actions/action.py
- gaphor/UML/actions/activity.py
- gaphor/UML/actions/activitynodes.py
- gaphor/UML/actions/flow.py
- gaphor/UML/actions/objectnode.py
- gaphor/UML/actions/pin.py
- gaphor/UML/classes/association.py
- gaphor/UML/classes/dependency.py
- gaphor/UML/classes/interfacerealization.py
- gaphor/UML/deployments/connector.py
- gaphor/UML/interactions/interaction.py
- gaphor/UML/interactions/message.py
- gaphor/UML/profiles/extension.py
- gaphor/UML/states/finalstate.py
- gaphor/UML/states/pseudostates.py
- gaphor/UML/states/region.py
- gaphor/UML/states/state.py
- gaphor/UML/states/transition.py
- gaphor/UML/usecases/extend.py
- gaphor/UML/usecases/include.py
- gaphor/core/styling/compiler.py
- gaphor/core/styling/tests/test_compiler.py
- gaphor/diagram.css
- gaphor/diagram/general/comment.py
- gaphor/diagram/general/diagramitem.py
- gaphor/diagram/shapes.py
Only "bold" names are stylable.
Issue Number: #3023
All name entries can be styled.
Added sibling (`region. region`) combinator to support State machine regions.
> Make all names stylable by CSS

- .readthedocs.yaml
- poetry.lock
- pyproject.toml
We're using [optional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) to define the dependencies for our documentation generation on Read the Docs. This looks a bit out of order, since there's no use for those optional dependencies, except for the documentation generation.
Use Poetry. Now `docs` is just a Poetry group, like any other group.
I think this is more consistent.
> Install Poetry as part of the RtD build

- gaphor/core/tests/test_eventmanager.py
- gaphor/plugins/errorreports/errorreports.py
- gaphor/plugins/errorreports/tests/test_errorreport.py
- gaphor/tests/raises.py
- gaphor/tests/test_raises.py
- poetry.lock
- pyproject.toml
- tests/test_undo.py
We're building and testing Python 3.11 and 3.12. However, the project suggests it works with Python 3.10 as well.
Update minimal Python version to 3.11.
Remove uses of exceptiongroup module. 3.11 has native support for those.
> Update minimal Python version to 3.11

- gaphor/ui/greeter.py
If a model is big, a user does not get any feedback when it's selected in the greeter.
A small quality of life thing, that provides feedback when a user clicks on a recent model or template.
> Make greeter window insensitive when a model is selected

- gaphor/ui/diagrampage.py
The contrast between the diagram and the side bar is a bit off, since both use the same background color.
Use Adwaita's default "view" style as background for diagrams.
> Give the diagram a default "view" background

- gaphor/ui/elementeditor.py
- gaphor/ui/elementeditor.ui
- gaphor/ui/styling.css
- gaphor/ui/tests/test_elementeditor.py
It's hard to guess what CSS nodes are part of an item in a diagram.
Issue Number: #3023
Below the style editor, a node layout is given for the currently selected element.
> Show CSS nodes below style sheet editor

- .github/actions/windows_executables/action.yml
- .github/workflows/full-build.yml
The PyInstaller bootloader is often flagged by virus scanners as a virus or trojan. This PR builds our own bootloader on CI on Windows which should have a different virus scanner signature than ones pre-built.
Avast, Windows Defender, AVG, Google Smartscanner, and others were detecting that Gaphor was a Trojan.
All detect as clean.
> Build our own Gaphor bootloader

- gaphor/core/modeling/presentation.py
- gaphor/diagram/connectors.py
- gaphor/diagram/general/tests/test_comment.py
- gaphor/diagram/tests/test_presentation.py
- tests/conftest.py
- tests/test_undo.py
Create elements, copy and paste them, then hit undo. Bang!
Issue Number: fixes #2895
You can safely undo a paste action.
Deleting items in a diagram behaves different.
* Connecting items on a diagram are no longer automatically removed.
> Fix undoing pasted items

- gaphor/plugins/diagramexport/__init__.py
- gaphor/plugins/xmiexport/__init__.py
- gaphor/ui/filedialog.py
- gaphor/ui/filemanager.py
- gaphor/ui/tests/test_filedialog.py
- org.gaphor.Gaphor.json
Files are not properly saved from Flatpaks if you do not define the `.gaphor` extension to the file.
Issue Number: #3085
Instead of adding an extension (which does not sync via XDP portals), provide a default name with extension.
This allows users to easily change the file name, with the extension already visible in the file entry field.
Do no longer "magically" add an extension.
> Fix file saving for FreeDesktop Portals

- gaphor/plugins/console/console.py
- gaphor/ui/appfilemanager.py
- gaphor/ui/errorhandler.py
- gaphor/ui/filemanager.py
- gaphor/ui/mainwindow.py
- gaphor/ui/uipreview.py
Presenting a window also triggers the window to be shown on top.
> Present windows, rather that setting them visible

- .github/workflows/full-build.yml
Since we have been having a lot of problems with false positives with virus scanners, this PR adds a scan with Virus Total each time we build the Windows installer. If it is a release, it adds links to the scan results. 
> Add virus scan with VirusTotal to CI

- gaphor/SysML/blocks/block.py
- gaphor/SysML/blocks/tests/test_block.py
- gaphor/core/modeling/collection.py
Block stereotype is always shown
Issue Number: Fixes #2975
Show only "block" stereotype if no other stereotypes are applied.
I'm not sure if this should be applied to other similar elements.
> Do not show "block" stereotype if other stereotypes are applied

- gaphor/core/format.py
Fixes #2587
Diagram type is shown in model browser:
> Display diagram type in model browser

- .github/dependabot.yml
Right now, Dependabot does daily updates and every dependency gets a separate PR. This PR reduces dependency merge overhead and CI/CD builds by grouping updates and reducing frequency to weekly.
Each dependency update gets a separate PR and dependencies are updated daily
Dependencies are in grouped PRs by package ecosystem and dependencies are updated weekly
> Change Dependabot to weekly grouped updates

- .github/workflows/full-build.yml
Dependabot and other builds are failing for the virus scan because they don't have access to the API key. This PR updates this build to only do virus scans when it is a mainline build.
External PRs are failing because they don't have access to secrets.
All PRs are passing.
> Only run virus scan on mainline builds

- gaphor/diagram/instanteditors.py
- gaphor/ui/diagrampage.py
- gaphor/ui/modelbrowser.py
It's hard to find the active diagram in the model browser.
Issue Number: Fixes #2597
Right-click in a diagram will show a popup menu. The popup menu contains an action to select the diagram or (hovered) item in the model browser.
> Find diagram in model browser

- .github/workflows/full-build.yml
In #3138, the syntax wasn't correct and now we are getting a failure `The workflow is not valid. .github/workflows/full-build.yml (Line: 399, Col: 9): Unrecognized named-value: 'env'. Located at position 1 within expression: env.mainline_build == 'true'`.
We are getting a build error.
Build error resolved.
> Fix conditional must use context for env variables

- gaphor/SysML/propertypages.ui
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/classes/propertypages.ui
- gaphor/UML/profiles/propertypages.ui
- gaphor/UML/states/propertypages.ui
- gaphor/diagram/propertypages.ui
- gaphor/ui/elementeditor.py
- gaphor/ui/help/shortcuts.ui
- gaphor/ui/styling.css
Property editors are often (but not always) encapsulated in a `GtkExpander`. There's little need for that, since the number of editors is not *that* long.
Simplify property editors. 
* Info/help boxes are now placed on a more logical place.
* Expanders have been removed.
* _Show Xxx_ switches are placed after data entry.
This will make it easier to split model and view based properties in the future. In the end we want to be able to use the property editor for elements selected in the Model Browser.
> Clean up property pages

- .github/workflows/full-build.yml
Apparently https://github.com/gaphor/gaphor/pull/3146 didn't fix the build issue with the conditional, my fault. This is due to the fact that environmental variables aren't available in the context of job.if, and only in job.step.if as shown here: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
Unrecognized named-value: 'env'
No error
> Fix env variables aren't accessible within job.if

- .github/workflows/full-build.yml
- gaphor/SysML/blocks/tests/test_connectors.py
- gaphor/UML/actions/pinconnect.py
- gaphor/UML/actions/tests/test_flowconnect.py
- gaphor/UML/actions/tests/test_pinconnect.py
- gaphor/UML/classes/tests/test_associationconnect.py
- gaphor/UML/classes/tests/test_dependencyconnect.py
- gaphor/UML/interactions/interactionsconnect.py
- gaphor/UML/interactions/tests/test_executionspecification.py
- gaphor/UML/interactions/tests/test_messageconnect.py
- gaphor/UML/states/tests/test_transition_connect.py
- gaphor/conftest.py
- gaphor/diagram/connectors.py
- gaphor/diagram/general/tests/test_comment.py
- gaphor/services/properties.py
- gaphor/services/tests/test_properties.py
- tests/conftest.py
- tests/test_remove_unused_elements.py
If you disable the "Remove Unused Elements" option, and remove a diagram, the relations in that diagram are removed anyway.
Issue Number: Fixes #2616 and #3047.
All unlinking is left to the _SanitizerService_. This service knows if the "Remove Unused Elements" option has been disabled and acts accordingly.
Without a configured Sanitizer Service, relationships are no longer removed on model level when a relation is broken in a diagram.
The change itself is quite simple: remove the unlink call from the connector. Fixing the tests took most of the time 😄 .
* Fixed Pin  interaction Messages and Execution Specification too.
* Use custom properties cache folder, so user settings are not intervening with tests.
* Added a hack to the macOS build, to …
> Fix retain relations

- po/build-babel.py
This PR enables 3 more translations since they are above 80% translated.
Gaphor is missing translations for Portuguese (Brazil), Chinese (Simplified), and Turkish.
Translations enabled
> Mark pt_BR, zh_Hans, and tr as mature translations

- gaphor/ui/mainwindow.py
- gaphor/ui/styling.css
With #3183 the title style for the Property Editor is gone.
This PR fixes that.
Also sets the full screen state properly.
> Fix title style for Property Editor

- .github/workflows/full-build.yml
- gaphor/main.py
- gaphor/tests/test_main.py
- gaphor/ui/__init__.py
- gaphor/ui/tests/test_selftest.py
- org.gaphor.Gaphor.json
- pyproject.toml
Self test is an option. This is from the time we did not have commands.
Now you can self-test by calling `gaphor self-test`.
> Make self-test a command, instead of an option

- .github/workflows/full-build.yml
Updates Gvsbuild. I also fixed the libpng errors we use to get my having Git in the path, so no need to move the Git binary out of the way.
> Update Gvsbuild to version 2024.3.0

- gaphor/SysML/blocks/property.py
- gaphor/UML/actions/activity.py
- gaphor/UML/classes/klass.py
- gaphor/UML/interactions/lifeline.py
- gaphor/UML/interactions/message.py
- gaphor/UML/umlfmt.py
Lifeline should show name of represented type (`ConnectableElement`)
Issue Number: Fixes #2514
Show represented name and type.
In addition I changed all cases where `TypedElement.typeValue` is used to also check for `TypedElement.type.name`. In all cases `type` takes precedence over `typeValue`, since type is actually linked to a model element and `typeValue` is something specifically added for Gaphor.
Also fixed messages: when attached to "life lines" without an actual lifeline, they act as a communication diagram.
In this case, lines so not need to be horizontal.
It would be nice if the Property Editor also shows settings for elements selected in the Model Browser. E.g. now it's not possible to change the attribute type easily.
> Use TypedElement.type for Lifeline and other types

- gaphor/UML/uml.py
- gaphor/core/modeling/__init__.py
- gaphor/diagram/propertypages.py
- gaphor/diagram/propertypages.ui
- gaphor/diagram/tests/test_propertypages.py
- gaphor/ui/styling.css
- models/UML.override
Issue Number: Fixes #2750 
A section at the bottom of the property editor shows some details about the selected item:
> Show element details

- gaphor/UML/actions/partitionpage.py
- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/enumerationpropertypages.py
- gaphor/UML/sanitizerservice.py
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/event.py
- gaphor/core/modeling/presentation.py
- gaphor/diagram/propertypages.py
- gaphor/services/undomanager.py
- gaphor/ui/diagrampage.py
- gaphor/ui/diagrams.py
The new update model is still not fool proof. Mostly updates coming from changes in the model are not always reflected in the diagrams.
The main issue is that I'd like to batch updates, but those update do have to happen within the context of the current transaction. Ergo, they can not happen completely asynchronous (as was the case previously).
Just requesting an update is not enough.
This is now solved by updating directly after an update request is done. This has the possible risk of doing double work. However, it's our only guarantee at the moment to make sure the diagrams are up to date.
The `request_update()` methods still schedule a diagram item for an update. The update now happens when a transaction is committed.
To …
> More fixes for broken updates

- gaphor/ui/help/preferences.ui
Translatable properties accept yes-no, true-false, 1-0, but the first one is more common and usually used.
> ui: Use translatable=yes

- gaphor/ui/tests/test_filemanager.py
- gaphor/ui/tests/test_modelchanged.py
Fixes a few encoding warnings recently introduced in the tests. There is a ruff rule for this called [PLW1514](https://docs.astral.sh/ruff/rules/unspecified-encoding/), but it is only available if preview rules are enabled.
> Cleanup some encoding warnings

- gaphor/SysML/propertypages.py
- gaphor/SysML/propertypages.ui
- gaphor/SysML/requirements/requirement.py
- gaphor/SysML/sysml.py
- gaphor/SysML/tests/test_propertypages.py
- gaphor/diagram/presentation.py
PR that addresses feature request to support controlling visibility of requirement's text
Additionally:
- requirement text is always visible on diagram
- requirement box (on diagram) automatically expands in height when more text is added, but does not reduce in height when text is removed
Issue Number: #2967
- requirement is added to diagram as item (similar to blocks)
- Whether requirement text is shown on diagram can be toggled in property window of requirements
- Upon a change in text the height is automatically cropped to the minimum required.
hopefully not, but would love to hear your verdict :)
> Control visibility of requirements

- .github/workflows/full-build.yml
- _packaging/gtk4.rb
4.14.0 does not have the delay in screen updates.
This workaround should be reverted as soon as 4.14.4 is available.
> Workaround: Install GTK 4.14.0 on macOS untill 4.14.4 is available

- gaphor/ui/icons/hicolor/scalable/emblems/SysML.svg
Launching Gaphor on Windows gives the following error: `(gaphor:18052): Pango-WARNING **: 12:50:04.556: couldn't load font "MyriadPro Not-Rotated 7.654", falling back to "Sans Not-Rotated 7.654", expect ugly output.`
I realized that the MyriadPro font was being used in the SysML logo. This PR updates the SysML logo to use a Sans font directly.
> Windows: Fix couldn't load MyriadPro font warning

- .github/actions/macos_dmg/action.yml
- .github/workflows/full-build.yml
The gh action is outdated, and I think we have better control over what's going on.
The action for certificate importing is outdated (Node 16). It's basically executing a script, so let's just do that: execute a script.
> Replace macOS certificate import by a script

- gaphor/ui/filemanager.py
Issue Number: #3275
time-out after save action, before file monitor is restarted
> Ignore event_type to prevent unexpected model changed popup

- gaphor/storage/storage.py
- gaphor/ui/diagrams.py
Diagrams do not have focus by default. This is not handy, since it causes users to click on a diagram once before they can actually use keyboard shortcuts.
The diagram always gets focus:
* When opened
* When another diagram is selected
This way shortcuts work instantly.
Additionally, there was an issue that not all items are updated after loading (due to the new diagram update strategy). Now diagrams are explicitly updated after loading.
> Ensure the diagram always has default focus

- .github/actions/install/action.yml
- .github/actions/windows_executables/action.yml
- .github/workflows/full-build.yml
- .github/workflows/hypothesis-test.yml
- docs/windows.md
This PR updates the CI/CD pipeline and dev environment instructions to directly download a pre-built version of GTK, rather than building it from source ourselves. The release of Gvsbuild today is the first one that distributed GTK as a release asset.
Also Step Security's Harden Runners only work with Ubuntu VMs, so I removed them for the Windows, macOS, and Fedora workflows.
We have to rebuild GTK ourselves for Gaphor on Windows
We download GTK and use it
> Windows: Download GTK instead of building

- .github/constraints.txt
- .readthedocs.yaml
- CHANGELOG.md
Moves from Python 3.11 to Python 3.12 with readthedocs.
> Use Python 3.12 with readthedocs, bump dependencies

- gaphor/application.py
- gaphor/core/modeling/elementfactory.py
- gaphor/core/modeling/event.py
- gaphor/core/modeling/tests/test_elementfactory.py
- gaphor/event.py
- gaphor/services/properties.py
- gaphor/services/tests/test_properties.py
- gaphor/services/undomanager.py
- gaphor/storage/storage.py
- gaphor/tests/test_application.py
- gaphor/ui/elementeditor.py
- gaphor/ui/filemanager.py
- gaphor/ui/mainwindow.py
- gaphor/ui/modelchanged.py
- gaphor/ui/modelmerge/editor.py
- gaphor/ui/recentfiles.py
- gaphor/ui/tests/test_modelbrowser.py
- gaphor/ui/tests/test_recentfiles.py
- tests/run_with_merge_conflict.py
Issue:  #2831
We had three events: SessionCreated, ModelLoaded, and ModelReady.
SessionCreated is emitted when a new session is launched. A session may be based on an existing model (`filename` is set).
ModelLoaded is emitted when a model is loaded, and it also contains the file name
ModelReady is emitted when a model is loaded.
Cleaned up event structure.
There's some overlap in those events. Back in the day we had the option to load a model in an existing session. We do not allow that anymore. Therefore the ModelLoaded event is a redundant and has been removed.
I ran into this while implementing #3284.
> Get rid of ModelLoaded event (recovery 1/3)

- gaphor/UML/sanitizerservice.py
- gaphor/application.py
- gaphor/event.py
- gaphor/main.py
- gaphor/storage/recovery.py
- gaphor/storage/tests/test_recovery_eventlog.py
- gaphor/tests/test_main.py
- gaphor/ui/__init__.py
- gaphor/ui/appfilemanager.py
- gaphor/ui/filemanager.py
- gaphor/ui/greeter.py
- gaphor/ui/selftest.py
- tests/test_session_recovery.py
This is an attempt to perfect a way to recover work after Gaphor has crashed, or terminated. The idea is that a user doesn't loose his work in case of a failure.
I see three approaches at this point:
1. On application startup, show to-be recovered sessions in the Greeter window and allow users to recover them, or delete them 
2. When a model is loaded, any unsaved changes are automatically applied.
3. The application instantly opens with all user sessions, as if nothing happened.
In #3284, models are recovered by file name. This does not work if:
1. A model is opened multiple times: now, changes are just not tracked in the subsequently opened models
5. A model is opened by multiple processes: Only one event log will be saved.
6. No event log is …
> Session recovery (recovery 4/3)

- gaphor/plugins/autolayout/pydot.py
- gaphor/plugins/autolayout/tests/test_pydot.py
Issue Number: #3328
Windows line breaks are also handled.
> pydot: clean line continuations with windows line endings

- gaphor/core/modeling/presentation.py
- gaphor/diagram/presentation.py
- gaphor/storage/recovery.py
- tests/test_session_recovery.py
Fix an issue I ran into when recovering an auto-layout model.
* Create a new model
* Add a line
* Split the line in a few segments
* move both ends
* Merge the line back to 1 segment
* Interrupt Gaphor (ctrl-C)
* Start gaphor again, see it crash
Issue Number: #2831
The Handle position event contains the new location, so we can record it, even if the handle has been removed in the mean time.
Now all recovery events are written with info from the event only. No lookups (except for id) need to be done on the element.
> Fix issue when recovering from split and merged segments

- gaphor/ui/textfield.py
Property editor becomes bigger if text is (too) long.
Issue Number: fixes #3235
Text ellipsizes at the end if it's too long to fit in the text box.
> Ellipsize long texts at the end

- gaphor/UML/classes/associationpropertypages.py
The problem is that Transaction handling has some caveats at the moment. this is because events are immediately forwarded to the undo manager when they happen, contrary to the "normal" behavior, which makes sures events are executed in order.
This gets a bit troublesome when a new transaction is started while there are still events in the queue. This PR fixes that for association end names by only starting a transaction if the change is not made twice.
Issue Number: Fixes #3348
Selecting an association with association ends filled in does no longer cause an exception.
The real solution is fixing #3351.
> Fix select association AssertionError

- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/enumerationpropertypages.py
* (regression) Deletion of attribute/operation/enumeration/parameter in property editor does not work. 
Deletion works: it's wrapped in a transaction.
Other things I like to fix here:
* Double click to edit a stereotype value
* Attribute/operation/enumeration reorder does not properly redraw the diagram item.
> Fix deletion of attribute/operation in element editor

- .github/actions/macos_dmg/action.yml
- .github/actions/windows_executables/action.yml
- .github/workflows/full-build.yml
This PR fixes a build issue with the VirusTotal action trying to write to the release. It also cleans up some of the other actions to pin hashes and add a top level permission.
Build is failing for release
> Fix VirusTotal Action is Failing Release Build

- gaphor/UML/classes/classespropertypages.py
- gaphor/UML/classes/klass.py
- gaphor/UML/classes/propertypages.ui
- gaphor/UML/tests/test_umlfmt.py
- gaphor/UML/umlfmt.py
Issue Number: Fixes #3327
Added a checkbox ("readOnly") to the attributes editor. Setting the `readOnly` property will make it visible in the class.
I considered editing tags/modifiers directly, but it's hard to keep those up to date. Also, there are a couple of. specific modifiers, and we can't expect users to know those by heart.
> Read-only attributes

- gaphor/UML/tests/test_umllex.py
- gaphor/UML/umllex.py
You cannot define a combination of visibilitity (and derived) and multiplicity, without providing an association end name.
Be more lenient with what to accept. Parse visibility and derived properties too.
> Be more lenient with association end multiplicity

- gaphor/application.py
- gaphor/event.py
- gaphor/ui/filemanager.py
- gaphor/ui/greeter.py
When a large model is loaded (e.g. `models/UML.gaphor`), it looks like nothing happens for a while.
Issue Number: fixes #3392
Postpone model loading until the main window is present. This has the additional advantage that dialogs are always placed over a window (no more warnings).
> Show main window first when loading model from command line

- gaphor/UML/states/propertypages.py
- gaphor/UML/states/propertypages.ui
- gaphor/UML/states/transition.py
- gaphor/UML/uml.py
- models/UML.gaphor
Adds `trigger` and `action` to a State Transition Models, in addition to `guard`, as per Issue [#2845](https://github.com/gaphor/gaphor/issues/2845)
trigger and action associations have been added to the UML model Transition Class Diagram , and the code updated to edit and display these attributes as `trigger [guard] /action`
Currently, only `guard` text can be entered, which is displayed below the transition as `[guard]`. 
Issue Number: [#2845](https://github.com/gaphor/gaphor/issues/2845)
Now `trigger` and `action` can independently be entered in the properties dialog, and are displayed according to the UML spec `trigger[guard]/action` on the transition. The text is _below_ the …
> Stm trigger action

- gaphor/C4Model/c4model.py
- gaphor/C4Model/diagramitems/__init__.py
- gaphor/C4Model/diagramitems/dependency.py
- gaphor/C4Model/iconname.py
- gaphor/C4Model/propertypages.py
- gaphor/C4Model/toolbox.py
- gaphor/core/modeling/diagram.py
- gaphor/core/modeling/tests/test_style_attributes.py
- gaphor/diagram.css
- models/C4Model.gaphor
Issue Number: fixes #3381
A special type of dependency can be used in C4 models, where the technology can be specified.
Also fixed how item attributes are fetched, so now the `[children=""]` expression in our CSS works again.
> Add a special C4 Dependency with a technology field

- .github/workflows/full-build.yml
An artifact with a funny name (`gaphor-x86_64`) is uploaded as artifact.
It looks like the flatpak-builder action now uploads artifacts. We do not need that.
> Do not upload development flatpak artifact

- docs/conf.py
On 2024-10-07, RTD will enable RTD Addons by default on all projects. This PR ensures that the html baseurl is injected in order to use our custom domain.
Everyone can read more about this here:
https://about.readthedocs.com/blog/2024/07/addons-by-default/
Once this is merged, I should be able to enable addons ahead of time by following these steps: https://docs.readthedocs.io/en/stable/addons.html#enabling-read-the-docs-addons
> Prepare for RTD migration to Addons

- gaphor/ui/macosshim.py
See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7260.
We no longer have to set up the keybindings by ourselves.
> No longer need to set up key bindings on macos for GTK 4.16

- gaphor/ui/greeter.py
- gaphor/ui/mainwindow.py
- gaphor/ui/modelbrowser.py
- gaphor/ui/tests/test_modelbrowser.py
`Gtk.StyleContext`, and `Gtk.Widget.get_style_context()` are deprecated since GTK 4.10.
Instead, set style classes on widgets directly.
> Remove use of deprecated Gtk.StyleContext

- docs/windows.md
Based on discussion on matrix, improving the documentation to ensure that the tree structure is present after unziping the Gvsbuild files.
> Windows: add tree of files expected in docs

- gaphor/diagram/general/generalpropertypages.py
- gaphor/ui/filedialog.py
- gaphor/ui/tests/test_filedialog.py
While playing on #3428 I noticed how in [gaphor/diagram/general/generalpropertypages.py](https://github.com/gaphor/gaphor/blob/48b4ef6862f99d223ca5605614216f81c65cc621/gaphor/diagram/general/generalpropertypages.py) attributes of the `image` object are accessed after its `close()`.
https://github.com/gaphor/gaphor/blob/48b4ef6862f99d223ca5605614216f81c65cc621/gaphor/diagram/general/generalpropertypages.py#L140-L151
Moreover, in current implementation the user is allowed to select multiple image files:
https://github.com/gaphor/gaphor/blob/48b4ef6862f99d223ca5605614216f81c65cc621/gaphor/diagram/general/generalpropertypages.py#L135-L137 
Todo:
1. Add a `Picture` to a diagram;
2. `Select picture...`
3. The user is allowed to select more than one file
1. Add a `Picture` to a diagram;
2. …
> Select single image file and avoid accessing image attributes after close

- gaphor/SysML/blocks/connectors.py
- gaphor/UML/recipes.py
- gaphor/UML/tests/test_recipes.py
- gaphor/ui/modelbrowser.py
- gaphor/ui/tests/test_modelbrowser.py
- gaphor/ui/treemodel.py
`ConnectorEnd`s show in the model root after a model is loaded.
Issue Number: Fixes #3445
`ConnectorEnd`, or any `MultiplicityElement` are no longer shown at top level.
> Fix unowned elements

- gaphor/ui/diagrampage.py
- gaphor/ui/modelbrowser.py
Fix broken popups introduced by #3415.
By default [Gtk.GestureClick](https://docs.gtk.org/gtk4/class.GestureSingle.html) only triggers on the primary mouse button.
@tompkins-ct this should fix the issue you're facing.
> Capture all button presses for popup menus

- .github/workflows/gvsbuild-updater.yml
- gaphor/ui/tests/test_filedialog.py
Fixes two issues:
- Fixes a permissions issue when trying to push during a workflow dispatch introduced in #3389
- Fixes usage of PosixPath in tests since this isn't cross platform for Windows introduced in #3430 
> Fix Gvsbuild automation and Windows tests

- gaphor/UML/tests/test_umllex.py
- gaphor/UML/umllex.py
- gaphor/codegen/coder.py
Modify regex
https://github.com/gaphor/gaphor/blob/6fee35e8a9413b28c3b32e5d3a1a0697dc244605/gaphor/UML/umllex.py#L36
to treat differently the `default` match in case the text is sorrounded by either `"` or `` ` ``.  In this latter case regex 
(?P<oq>[\"'])(?:(?=(?P<ec>\\?))(?P=ec).)*?(?P=oq)
applies (it should allow for escaped quotes between quotes. 
Also, fixes the generation of code from the model. In the following snippet `coder.py` applies double quotes regardless if `a.defaultValue` is already quoted or not. In the former case the generated Python code is not valid.
https://github.com/gaphor/gaphor/blob/62b2fa0d0719362e6d644a332cc55ec3b66daa46/gaphor/codegen/coder.py#L307-L308
Issue Number: Fixes #3432
See the issue for more information
See the issue expected behavior.
> Allow spaces in string attribute value

- gaphor/UML/classes/interfacerealization.py
- gaphor/UML/classes/tests/test_realizationconnect.py
- gaphor/UML/uml.py
- gaphor/storage/tests/test_storage_uml_2_5_upgrade.py
- gaphor/storage/tests/test_storage_upgrades.py
- models/UML.gaphor
Misspelled property in UML model
Issue Number: Fixes #3455 
Proper name: `implementingClassifier`.
There's no need to an upgrade in the storage module, since `InterfaceRealization.implementatingClassifier` is a redefined property.
> Fix InterfaceRealization.implementingClassifier name

- gaphor/plugins/diagramexport/__init__.py
- gaphor/plugins/diagramexport/exportall.py
- gaphor/plugins/diagramexport/exportcli.py
Creating a full export of all diagrams in a model was already possible from the command-line. This can be intimidating for people who are less used to working in a CLI environment. I encountered this issue at my work where some system engineers were going through their model and manually exporting diagrams one-by-one, which is not a good use of their time. I quickly whipped up a plugin for them to do a dump to PNG. This PR is the cleaned up version of that plugin with support for all 4 formats that Gaphor currently supports.
Additionally this also adds support for EPS export on the CLI which was missing before.
Export is only available for a single diagram in the UI …
> Add option to export all diagrams from UI (same as CLI)

- gaphor/extensions/sphinx.py
The use of `relative_to` causes a failure when building Sphinx documentation using an out of source build because it cannot create a relative path by walking up through parent directories prior to the `walk_up` option available in Python 3.12
Failure to include generated images when using out of source Sphinx builds.
Out of source Sphinx builds are supported.
> Fix Sphinx extension relative image path for out of source builds

- docs/windows.md
The silent Graphviz installer doesn't automatically add dot to the path. This change updates the docs to add it to the Path when adding GTK to the path.
> Windows docs: Add Graphviz to path

- .github/actions/macos_dmg/action.yml
- .github/workflows/full-build.yml
When trying to release version 2.27.0, we are getting an error when trying to upload the macOS release assets to the release. This is because we need to pass the release version to the `gh upload` command, but the version is currently mixed with the architecture suffix. This PR splits the version and the arch to two separate inputs so that we can keep the version to the actual version number and use the arch as a separate suffix where needed.
> Fix macOS release upload

- _packaging/gaphor.spec
According to the apple docs, the conformance type should be some sort of super-type for our Gaphor model.
Since our models are saved as XML, I suppose `public.xml` is the most approprate.
https://developer.apple.com/documentation/uniformtypeidentifiers/defining-file-and-data-types-for-your-app?language=objc
> macos: Fix Gaphor model file conformance

- gaphor/ui/help/__init__.py
About dialog has a workaround for opening links on Darwin. It did not work before.
Links work in a (to be released) GLib version, not to far in the future, I hope.
See https://gitlab.gnome.org/GNOME/glib/-/issues/3484.
> Remove workaround for opening links on macOS

- _packaging/gaphor.spec
That's the minimum version of (the next) GTK version.
Minimum macOS version is set to 10.13
GTK4 will require macOS 10.15 or newer.
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7881
> Minimum macOS system version is 10.15

- gaphor/core/format.py
- gaphor/diagram/deletable.py
- gaphor/ui/modelbrowser.py
- gaphor/ui/tests/test_modelbrowser.py
- gaphor/ui/tests/test_treemodel.py
- gaphor/ui/treemodel.py
The model browser mainly depends on the `Element.owner/ownedElement` relationship for ownership.
It also supports `memberNamespace`, mainly for association ends without owner.
Builds on #3568.
Issue Number: #3540
Fixes #3557
Separate the concept of ownership out of the model browser, so it can be extended. 
The `owner()` dispatch method tells who's the owner of an element: another element, `Root`, or `None`. In case of `None`, the element is not supposed to be shown in the model browser.
A separate element ownership function.
The only issue is that event handling (in `ModelBrowser`) still checks for the properties used. This should change at some point, but I think this is already a nice simplification.
I do love to get rid of the `owns()` …
> Make model browsers ownership concept extendible

- gaphor/UML/profiles/propertypages.ui
- gaphor/UML/profiles/stereotype-value-cell.ui
- gaphor/UML/profiles/stereotypepropertypages.py
To edit a stereotype slot value you have to use `F2`.
Now double click also works, as with attribute and operations editors.
> Enable double click to edit stereotype values

- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/full-build.yml
- .github/workflows/gvsbuild-updater.yml
- .github/workflows/hypothesis-test.yml
- .github/workflows/labeler.yml
- .github/workflows/pre-commit-updater.yml
- .github/workflows/release-drafter.yml
- .github/workflows/scorecard.yml
1. We were getting permission errors when pushing a branch using my account PAT. I added a GitHub App to the Gaphor org, and this PR makes use of it to make the PR updates instead.
2. Updates Linux runners to Ubuntu 24.04
3. Enables network access for Immutable Actions per the [breaking change](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/#updates-to-the-network-allow-list-for-self-hosted-runners-and-azure-private-networking) announcement
> Fix Gvsbuild and Pre-commit PR updates

- gaphor/core/modeling/base.py
- gaphor/core/modeling/presentation.py
- gaphor/core/modeling/tests/test_diagram.py
- gaphor/services/undomanager.py
- tests/test_architecture.py
This PR builds on #3582
The undo order is not always right for presentation elements.
Issue Number: #3577
Diagrams will always be removed after all presentations are removed. This way the undo order is maintained.
This opens the opportunity to have different types of diagrams. It could be that we create separate `ClassDiagram`, `SequenceDiagram`, etc. types, instead of using the diagramType objects we currently use.
> Fix undo order

- docs/linux.md
- gaphor/ui/filemanager.py
- gaphor/ui/statuswindow.py
- gaphor/ui/tests/test_main.py
An issue arose with the Adwaita dialogs: if a dialog is closed to quickly, the close call is ignored and the dialog remains visible. 
This avoids flicker when smaller files are saved.
A workaround is in place for issue https://gitlab.gnome.org/GNOME/libadwaita/-/issues/970.
Small update for setting up a local Gaphor dev environment on Fedora.
> Only show status window on save for big files

- gaphor/ui/treemodel.py
Sometimes elements remain in the model.
In this case (classes with association), elements could remain, because their either `owned` or in the `memberNamespace`.
Issue Number: Fixes #3557
The model is more up to date.
I had some extensive tests, but they could not expose the issue, so i did not commit those.
> Fix issues with element remaining in model

- gaphor/C4Model/modelinglanguage.py
- gaphor/C4Model/toolbox.py
- gaphor/RAAML/modelinglanguage.py
- gaphor/RAAML/toolbox.py
- gaphor/SysML/modelinglanguage.py
- gaphor/SysML/toolbox.py
- gaphor/UML/actions/propertypages.ui
- gaphor/UML/classes/propertypages.ui
- gaphor/UML/modelinglanguage.py
- gaphor/UML/tests/test_treemodel.py
- gaphor/UML/toolbox.py
- gaphor/UML/treeitem.ui
- gaphor/UML/treemodel.py
- gaphor/abc.py
- gaphor/core/modeling/modelinglanguage.py
- gaphor/diagram/general/modelinglanguage.py
- gaphor/diagram/propertypages.py
- gaphor/diagram/tests/fixtures.py
- gaphor/services/modelinglanguage.py
- gaphor/templates/blank.gaphor
- gaphor/ui/modelbrowser.py
- gaphor/ui/tests/test_modelbrowser.py
- gaphor/ui/tests/test_treesearch.py
- gaphor/ui/treesearch.py
- tests/test_architecture.py
Currently the model browser only works with UML (derived) modeling languages.
Issue Number: #3577 
The Model Browser model is now part of the model.
It can be exposed through the `ModelingLanguage` class. The tree model type is then instantiated via dependency injection.
Every modeling language now has an associated model class for the Model Browser. The model browser takes care to leave the model as is for modeling languages that use the same tree model type (all our current languages).
* Improved new-diagram menu for diagrams.
> Decouple UML concepts from model browser

- gaphor/UML/sanitizerservice.py
- gaphor/settings.py
- gaphor/ui/elementeditor.py
- gaphor/ui/elementeditor.ui
- gaphor/ui/help/__init__.py
- gaphor/ui/help/preferences.ui
- gaphor/ui/installschemas/org.gaphor.Gaphor.gschema.xml
- gaphor/ui/toolbox.py
- tests/test_remove_unused_elements.py
Settings for tool reset and automatic model maintenance used to be configured on a per-model basis.
Settings moved from a model-based to global settings. This should make our settings story more consistent. Now all we have
I think we discussed this idea a while back as part of Mareike's study on MBSE tooling for neurodivergent people.
NB. Do not forget to run `gaphor install-schemas`.
> Move editing settings to global preferences window

- gaphor/ui/diagrams.py
- gaphor/ui/event.py
- gaphor/ui/modelbrowser.py
Double-click adds a model element to the active diagram. This is perceived as confusing.
Issue Number: Fixed #3262
Do not add a new presentation to the diagram, instead select the element if it's in the diagram. Show a message if it's not in the diagram.
> When double-clicking on a model element, select it in diagram

- .github/actions/install/action.yml
- .github/actions/macos_dmg/action.yml
- .github/actions/windows_executables/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/full-build.yml
- .github/workflows/gvsbuild-updater.yml
- .github/workflows/hypothesis-test.yml
- .github/workflows/labeler.yml
- .github/workflows/pre-commit-updater.yml
- .github/workflows/scorecard.yml
- .github/zizmor.yml
See https://blog.pypi.org/posts/2024-12-11-ultralytics-attack-analysis/
Looks like zizmor is the go-to tool.
Your composite actions (`action.yml`) files are not checked. It's on zizmor's backlog, though: https://github.com/woodruffw/zizmor/issues/173. 
The most common issue found are [template injection](https://woodruffw.github.io/zizmor/audits/#template-injection), and [artipacked](https://woodruffw.github.io/zizmor/audits/#artipacked).
In the `labeler` workflow we use a [dangerous trigger](https://woodruffw.github.io/zizmor/audits/#dangerous-triggers). Should we delete this workflow and set labels ourselves again?
```
error[dangerous-triggers]: use of fundamentally insecure workflow trigger
--> …
```
> Strengthen pipeline security with Zizmor

- docs/models/core.rst
- docs/sphinx.rst
- gaphor/extensions/sphinx.py
Diagrams are not easy to style. Small diagrams show up big in the documentation.
Since images are wrapped in a figure, this also opens some (CSS) styling options.
This change also allows us to add a caption.
> Render diagrams with Sphinx as Figures

- docs/scripting.md
Updated docs to reference UML.recipes which has some handy functions for model creation and editing. And also added reference to modelling language tests cases which illustrate behaviour of the elements. 
> Add reference to UML.recipes in Scripting docs

- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/actions/objectnode.py
Issue Number: fixes #3466, fixes #3597
ObjectNode can be typed, and type is shown in the node.
> Set type on object node

- gaphor/UML/group.py
- gaphor/UML/tests/test_group.py
Properties and Operations can not be moved to another owner.
Issue Number: fixes #3572 
Properties and Operations can be moved to another owner.
Association ends (properties attached to an association) *cannot* be moved, since that could create inconsistencies between model and diagram.
> Allow to move properties and operations around in the Model Browser

- gaphor/C4Model/iconname.py
- gaphor/diagram.css
Elements contained in a diagram frame have left aligned text.
Also fixed the mapping from C4 elements to their icons.
> Update diagram frame styling

- gaphor/UML/general/diagramitem.py
We now have different diagram types, instead of one diagram type with a `diagramType` property.
However, the mapping from diagram type to diagram item was not loaded.
Issue Number: fixes #3698
Diagram type mappings (representations) are loaded.
> Initialize model specific diagram types

- .github/actions/macos_dmg/action.yml
- .github/workflows/full-build.yml
During mainline builds, we were getting a build failure during notarization caused by a typo in one of the variable expansions.
> Fix variable expansion during notarization

- gaphor/ui/diagrampage.py
Fixes #3741
This doesn't improve touch interaction much, just avoids the context menu code erroring out.
Issue Number: #3741 
Doesn't error.
It would be nice to improve touch inut overall, like allowing box selection, draging elements and not preserving as much scroll momentum when dragging. I don't have a touch-enabled developing machine, so testing code changes requires a bit of work. Maybe I'll take a stab at it in the future.
> Fix exception when dragging with touch

- gaphor/UML/classes/propertypages.ui
Issue Number: Fixes #3745
Association member end names are ellipsized, so long names do not make the property editor unnecessary wide.
@tompkins-ct This is the fix, right?
> Ellipsize long class names in association property editor

- gaphor/diagram/styleeditor.ui
- gaphor/plugins/console/consolewindow.py
- gaphor/plugins/errorreports/errorreports.ui
- gaphor/ui/greeter.ui
- gaphor/ui/styling.py
On macOS, the window looks a bit off, since it does not contain the signature window controls.
This is an implementation of native window controls, which will hopefully make it in GTK 4.18.
See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/8071
This PR requires GTK 4.18, or the latest development version with MR.
> Prepare for native window controls (macOS)

- gaphor/diagram/export.py
- gaphor/ui/clipboard.py
- gaphor/ui/tests/test_clipboard.py
Diagram data can't be copied to other apps.
Issue Number: #3664
Apart from the (internal) copy buffer, also provide PNG and SVG images, so diagrams can be copied in other apps.
* Paste function is now async/await instead of callbacks.
> Copy PNG and SVG to the clipboard

- gaphor/UML/general/imagepropertypage.py
- gaphor/UML/general/tests/test_imagepropertypage.py
- gaphor/action.py
- gaphor/application.py
- gaphor/asyncio.py
- gaphor/core/eventmanager.py
- gaphor/core/tests/test_eventmanager.py
- gaphor/plugins/diagramexport/export.py
- gaphor/tests/test_action.py
- gaphor/tests/test_application.py
- gaphor/ui/appfilemanager.py
- gaphor/ui/errordialog.py
- gaphor/ui/filemanager.py
- tests/test_session_recovery.py
- tests/test_undo.py
We need to schedule special "background tasks" in order to perform async code.
For EventManager events, allow event handlers to be async functions. This makes it more ideomatic to work with async code.
Actions can also be async. However, an action can only be executed one at a time.
Cleaned out the `gaphor.asyncio` module. Now it only has 2 functions that can be removed once PyGObject 3.52 has been released.
> Async actions and event handlers

- gaphor/C4Model/propertypages.py
- gaphor/C4Model/propertypages.ui
- gaphor/SysML/propertypages.py
- gaphor/UML/actions/actionseditors.py
- gaphor/UML/actions/actionspropertypages.py
- gaphor/UML/actions/activitypropertypage.py
- gaphor/UML/actions/partitionpage.py
- gaphor/UML/classes/associationpropertypages.py
- gaphor/UML/classes/classeseditors.py
- gaphor/UML/general/commenteditor.py
- gaphor/UML/states/propertypages.py
- gaphor/diagram/general/generalpropertypages.py
- gaphor/diagram/instanteditors.py
- gaphor/diagram/propertypages.py
- gaphor/event.py
- gaphor/services/tests/test_undomanager.py
- gaphor/services/undomanager.py
- gaphor/ui/mainwindow.py
Currently, when undoing text via the central undo option, text is undone one character at a time.
Transactions are closed for amending when focus changes on the window.
Text edit actions are amended to an existing transaction (`context="editing"`).
This means that if you undo one edit action, the text is changes to what it was before.
* It could be that bogus undo transactions are created if a user changes something in a text field and the reverts it by itself.
* amendable transactions (edit transactions) are closed when the user switches focus to another widget.
> Improve text undo

- docs/windows.md
I checked the windows instructions. Made a few minor changes (e.g. python versions).
One thing I noticed is that I only need to install pycairo from gvsbuild. PyGObject works fine, at least on my setup.
It also works if I disallow installing the precompiled binaries for pycairo:
```
poetry config --local installer.no-binary pycairo
poetry install
```
Maybe those are alternatives to force-installing the builds made with GVSBuild. We can also add this bit of configuration in a `poetry.toml` file. Is that file supposed to be checked in?
BTW. I do not see any instructions on installing compilers. Is that done automatically nowadays?
> Update Windows development instructions

- gaphor/ui/elementeditor.py
- gaphor/ui/elementeditor.ui
- gaphor/ui/styling.css
Add a little section to the property editor to make people aware that Gaphor is free and open source.
Not sure if it should still show if the "Show Tips" switch is disabled.
* Improved CSS for tips section.
> Add a small teaser text for Gaphor

- gaphor/ui/greeter.py
- gaphor/ui/mainwindow.py
GNOME Shell uses the "new-window" action to open new main windows for an application. Renaming that action to this common name allows application launchers to use it.
GNOME Shell does not provide a "New Window" option for Gaphor, because the "new-window" action is not implemented.
GNOME Shell provides a "New Window" action for Gaphor that opens a new greeter window if not already present.
> Rename new-model action to new-window

- gaphor/ui/__init__.py
This raises the window when the user launches the application and the main window is already open.
Nothing happens when the main window is already open and the application is launched second time, the window is left in the background.
Existing main window will be raised on second launch.
> Present existing window on activation

- gaphor/storage/storage.py
Forces upper limits to take the value '*' if they are strings hence overwriting values like 'N' or 'max_items'
Allows model to load, but may not be a thorough solution.  
- [ x] I have read, and I understand the GNOME [Code of Conduct](https://conduct.gnome.org/)
- [x ] Bug fix
If associations have upper limits defined as any string othe than '*' the model fails to load.
Issue Number: 3806
Overwirte string with '*'
- [ x] No
> 3806 - forced upper limits that are strings to take value '*'

- gaphor/ui/__init__.py
- gaphor/ui/actiongroup.py
Ctrl+q doesn't work on Linux (and probably also not on Windows).
Issue Number: #3821 
Ctrl+q works again.
> Fix Ctrl+q: retrieve shortcuts from Application class

- gaphor/SysML/drop.py
- gaphor/UML/compartments.py
- gaphor/UML/drop.py
- gaphor/UML/tests/test_drop.py
- gaphor/diagram.css
- gaphor/diagram/drop.py
- gaphor/diagram/group.py
- gaphor/diagram/tools/dnd.py
- gaphor/diagram/tools/placement.py
Grouping didn't work when dragging elements from Model Browser or Toolbox.
Issue Number: fixes #3769, fixes #3750
Grouping works, with drop zone support.
To test, drop an element from the model browser on another element in a diagram (e.g. drop one class on either of 2 packages).
Diagram frames will no longer change ownership of elements dragged onto them.
Maybe iterate items at a point, instead of only looking at the topmost one?
> Highlight drop zone during DnD operation

- data/org.gaphor.Gaphor.desktop
- gaphor/main.py
- gaphor/ui/__init__.py
And specify the "new-window" action in the desktop file. This allows application launchers to provide direct access to this action.
The "new-window" action is not accessible through the application launcher of KDE Plasma.
The "new-window" action is accessible through any application launchers that support desktop actions.
> Add "greeter" command-line option

- gaphor/plugins/diagramexport/exportall.py
L15 of exportAll.py refered to nestedPackage not owningPackage
Issue Number: #3825
Diagrams now export as expected.
> Fix nestedPackage error when exporting all diagrams to PDF

- data/org.gaphor.Gaphor.desktop
- data/org.gaphor.Gaphor.service
And mark the application as D-Bus activatable. This allows application launchers to activate it via D-Bus.
Reference:
https://specifications.freedesktop.org/desktop-entry-spec/1.3/dbus.html
Gaphor is not launchable via D-Bus, so application launchers could able to launch it only by executing the launcher script.
Application launchers that support activating apps via D-Bus are able to do that for Gaphor.
The file needs to be installed into the following path, otherwise the desktop launcher won't work:
/usr/share/dbus-1/services/org.gaphor.Gaphor.service
> Add D-Bus service file

- gaphor/ui/diagramview.py
- gaphor/ui/elementeditor.ui
- gaphor/ui/styling-macos.css
When tips are not shown, unselecting all elements fades out the tips text (again).
The font for labels and such on macOS is too small: 12pt (user) vs 13pt (system) font size. See https://developer.apple.com/design/human-interface-guidelines/typography#macOS.
> Styling tweaks

- gaphor/core/modeling/diagram.py
- gaphor/entrypoint.py
The `logger.warn()` method is deprecated:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
This PR resolves the deprecation warnings of the `logger` library.
> Resolve warnings of Logger library

- gaphor/UML/interactions/interactionsconnect.py
- gaphor/UML/interactions/message.py
- gaphor/UML/umllex.py
- gaphor/UML/umloverrides.py
- gaphor/diagram/connectors.py
- gaphor/diagram/presentation.py
- gaphor/diagram/shapes.py
- gaphor/diagram/tests/fixtures.py
- gaphor/diagram/tests/test_text.py
- gaphor/diagram/text.py
Issue Number: fixes #3909 
Label for sequence diagram messages are now drawn above the message.
Also added some extra type information and removed some unused code.
BTW. The image was copied straight out of Gaphor into the browser. Works like a charm 😄
> Message name align

- .github/workflows/full-build.yml
The self-test on macOS also shows something seemingly related:
```
(gaphor:9836): Gtk-WARNING **: 12:53:06.960: Theme parser error: (null): Error loading image 
'resource:///org/gnome/Adwaita/styles/assets/devel-symbolic.svg': 
(gaphor:9836): Gtk-CRITICAL **: 12:53:07.504: gtk_css_section_get_bytes: assertion 'section != NULL' failed
```
Something's off with the produced app as well:
Icons are bundled, though:
```
./Resources/gaphor/ui/icons/hicolor/scalable/actions/gaphor-abstract-operational-situation-symbolic.svg
./Resources/gaphor/ui/icons/hicolor/scalable/actions/gaphor-accept-event-action-symbolic.svg
...
./Resources/share/icons/Adwaita/symbolic/actions/format-indent-more-symbolic.svg …
```
> Fix build error on macOS

- gaphor/application.py
- gaphor/event.py
- gaphor/ui/filemanager.py
- gaphor/ui/mainwindow.py
- gaphor/ui/tests/test_lifecycle.py
- tests/test_session_recovery.py
Ctrl-Q didn't work when the greeter window was opened. The quit logic checked of there were any non-session windows opened and then refused to quit.
It has been fixed by providing a bit more context to session shutdown events. They can now tell the event is intended to quit the application.
> Fix quit behavior for greeter

- gaphor/ui/modelbrowser.py
The "New Package" popup menu item in the Model Browser is disabled.
Issue Number: fixes #3931
It works again. Dropped "New", as we did with all other items.
> Enable the (New) Package menu item again

- gaphor/UML/tests/test_treemodel.py
- gaphor/UML/tests/test_umlfmt.py
- gaphor/UML/treemodel.py
- gaphor/UML/umlfmt.py
This feature builds on #3827.
Related names in the model browser are not updated.
Issue Number: Fixes #3791, #2852. Closes #3827.
Synchronize related elements in the Model browser, so everything looks up to date.
I took @mvinca's PR and simplified it a bit. It now works for ActivityParameterNode's and Properties (any Typed Element).
This makes the UI behave more consistently. If I missed a case, I think it's best to just add it to `TreeModel.sync()`.
Thanks again @mvinca for your work. It helped a lot in shaping this solution.
> Update activity parameter node name and types in Model browser 

- gaphor/C4Model/c4model.py
- gaphor/RAAML/raaml.py
- gaphor/SysML/blocks/block.py
- gaphor/SysML/blocks/group.py
- gaphor/SysML/blocks/interfaceblock.py
- gaphor/SysML/blocks/property.py
- gaphor/SysML/blocks/tests/test_connectors.py
- gaphor/SysML/blocks/tests/test_group.py
- gaphor/SysML/propertypages.py
- gaphor/SysML/requirements/requirement.py
- gaphor/SysML/sysml.py
- gaphor/SysML/tests/test_propertypages.py
- gaphor/UML/classes/stereotype.py
- gaphor/UML/uml.py
- gaphor/codegen/coder.py
- gaphor/codegen/tests/test_coder.py
- gaphor/core/modeling/coremodel.py
- gaphor/core/modeling/elementfactory.py
- models/C4Model.gaphor
- models/RAAML.gaphor
- models/SysML.gaphor
- models/SysML.override
- models/UML.override
Builds on #3979 
Models are a bit loose (e.g. you can import `Class` from the SysML model, although it's defined in UML).
This breaks as soon as we add another modeling language: KerML or SysMLv2.
This PR creates some prerequisites needed to make working with KerML and SysML2 models easier. Those models have similarly named types as our current UML/SysML model and should therefore be strictly namespaced.
The import mechanism has been simplified: imported packages should exist in a package with a name similar to the model name (entry point name). This makes importing types from super-models more predictable.
You can only import classes from their authoritative model.
> Only import classes from their authoritative model

- docs/conf.py
I noticed that our docs builds were failing due to a 404 redirect. This PR updates the PyGObject API docs to the new home.
> Fix PyGObject API docs location

- gaphor/UML/classes/tests/test_classespropertypages.py
- gaphor/core/modeling/collection.py
- gaphor/core/modeling/event.py
- gaphor/core/modeling/properties.py
- gaphor/core/modeling/tests/test_collection.py
Reordering for attributes of a class does not work from the property editor.
Issue Number: fixes #4001 
It works again.
> Fix reordering of class' attributes
